<?php

/**
 * Implementation hook_menu().
 */

function oficinasecretaria_menu() {
 $items=array();

$items['oficinasecretaria/oficina_principal']=array(
	'title' => 'Oficina Principal',
	'access arguments' => array('Estudiantes'),
	'page callback' => 'oficinasecretaria_estudiantes',
	'access callback'=> TRUE,
	'type' => MENU_NORMAL_ITEM,
	);	
 
$items['oficinasecretaria/oficina_principal/estudiantes']=array(
	'title' => 'Estudiantes',
	'access arguments'=> array('Estudiantes'),
	'type'=> MENU_DEFAULT_LOCAL_TASK,
	'weight'=> 0,
	);
$items['oficinasecretaria/oficina_principal/docentes']=array(
	'title' => 'Docentes',
	'access arguments'=> array('Docentes'),
	'page callback' => 'oficinasecretaria_docentes',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 1,
	);	
$items['oficinasecretaria/oficina_principal/materias']=array(
	'title' => 'Materias',
	'access arguments'=> array('materias'),
	'page callback' => 'oficinasecretaria_materias',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 2,
	);	
/*$items['oficinasecretaria/oficina_principal/departamentos']=array(
	'title' => 'Departamentos',
	'access arguments'=> array('Departamentos'),
	'page callback' => 'oficinasecretaria_departamentos',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 3,
	);
*/
$items['oficinasecretaria/departamentos']=array(
	'title' => 'Departamentos',
	'access arguments' => array('Departamentos'),
	'page callback' => 'saludo',
	'access callback'=> TRUE,
	'type' => MENU_NORMAL_ITEM,
	'weight'=>-2,
	);	
 
return $items;

}

/**
 * Page callback
 */

function oficinasecretaria_estudiantes(){
return "Hola";
}

function oficinasecretaria_docentes(){
}

function oficinasecretaria_materias(){
return "Hola1";
}

function oficinasecretaria_departamentos(){
return "Hola2";
}

function saludo(){

return "Esto es una prueba de página";
}