<?php


/**
 * Implementation hook_menu().
 */
 function oficina_menu() {
 $items=array();

 $items['oficina/cursos_oficiales'] = array(	//Cursos Académicos
 'title' => 'CURSOS OFICIALES',
 'page callback' => 'agregare',
 'page arguments' => array('Unidades'),
 'access callback' => TRUE,
 'type' => MENU_NORMAL_ITEM,
 'weight' => -1,
 );
 $items['oficina/cursos_oficiales/unidades'] = array(
 'title' => 'Unidades',
 'access arguments' => array('Unidades'),
 'type' => MENU_DEFAULT_LOCAL_TASK,
 'weight' => 0,
 );
 $items['oficina/cursos_oficiales/cursos'] = array(
 'title' => 'Cursos',
 'access arguments' => array('Cursos'),
 'page callback' => 'agregare',
 'type' => MENU_LOCAL_TASK,
 'weight' => 1,
 ); 
$items['oficina/cursos_oficiales/niveles'] = array(
 'title' => 'Niveles',
 'access arguments' => array('Niveles'),
 'page callback' => 'agregare',
 'type' => MENU_LOCAL_TASK,
 'weight' => 2,
 );

$items['oficina/cursos_oficiales/cursos/listar_cursos'] = array(
 'title' => 'Listar Cursos',
 'access arguments' => array('Cursos'),
 'page callback' => 'listare',
 'page arguments' => array(2),
 'type' => MENU_LOCAL_TASK,
 'weight'=> 0,
 ); 
$items['oficina/cursos_oficiales/cursos/alta_curso'] = array(
 'title' => 'Alta Curso',
 'access arguments' => array('Cursos'),
 'page callback' => 'listare',
 'page arguments' => array(2), 
 'type' => MENU_LOCAL_TASK,
 'weight'=> 2,	
 );
 $items['oficina/cursos_oficiales/cursos/baja_curso'] = array(
 'title' => 'Baja Curso',
 'access arguments' => array('Cursos'),
 'page callback' => 'baja_est',
 'page arguments' => array(2), 
 'type' => MENU_LOCAL_TASK,
 'weight'=> 3,
 );
$items['oficina/cursos_oficiales/cursos/modificar_curso'] = array(
 'title' => 'Modificar Curso',
 'access arguments' => array('Cursos'),
 'page callback' => 'listare',
 'page arguments' => array(2),
 'type' => MENU_LOCAL_TASK,
 'weight'=> 1,
 );


$items['oficina/cursos_oficiales/niveles/listar_niveles'] = array(
 'title' => 'Listar Niveles',
 'access arguments' => array('Niveles'),
 'page callback' => 'listare',
 'page arguments' => array(2),
 'type' => MENU_LOCAL_TASK,
 'weight'=> 0,
 ); 
$items['oficina/cursos_oficiales/niveles/alta_nivel'] = array(
 'title' => 'Alta Nivel',
 'access arguments' => array('Niveles'),
 'page callback' => 'al_departamento',
 'page arguments' => array(2), 
 'type' => MENU_LOCAL_TASK,
 'weight'=> 2,
 );
 $items['oficina/cursos_oficiales/niveles/baja_nivel'] = array(
 'title' => 'Baja Nivel',
 'access arguments' => array('Niveles'),
 'page callback' => 'ba_departamento',
 'page arguments' => array(2), 
 'type' => MENU_LOCAL_TASK,
 'weight'=> 3,
 );
$items['oficina/cursos_oficiales/niveles/modificar_nivel'] = array(
 'title' => 'Modificar Nivel',
 'access arguments' => array('Niveles'),
 'page callback' => 'mo_departamento',
 'page arguments' => array(2),
 'type' => MENU_LOCAL_TASK,
 'weight'=> 1,
 );

$items['oficina/cursos_oficiales/unidades/listar_unidades'] = array(
 'title' => 'Listar Unidades',
 'access arguments' => array('Unidades'),
 'page callback' => 'listare',
 'page arguments' => array(2),
 'type' => MENU_LOCAL_TASK,
 'weight'=> 0,
 ); 
$items['oficina/cursos_oficiales/unidades/alta_unidad'] = array(
 'title' => 'Alta Unidad',
 'access arguments' => array('Unidades'),
 'page callback' => 'al_departamento',
 'page arguments' => array(2), 
 'type' => MENU_LOCAL_TASK,
 'weight'=> 2,
 );
 $items['oficina/cursos_oficiales/unidades/baja_unidad'] = array(
 'title' => 'Baja Unidad',
 'access arguments' => array('Unidades'),
 'page callback' => 'ba_departamento',
 'page arguments' => array(2), 
 'type' => MENU_LOCAL_TASK,
 'weight'=> 3,
 );
$items['oficina/cursos_oficiales/unidades/modificar_unidad'] = array(
 'title' => 'Modificar Unidad',
 'access arguments' => array('Unidades'),
 'page callback' => 'mo_departamento',
 'page arguments' => array(2), 
 'type' => MENU_LOCAL_TASK,
 'weight'=> 1,
 );

$items['oficina/departamentos']=array(		//Departamentos
	'title' => 'DEPARTAMENTOS',
	'access arguments'=> array('Listar Departamentos'),
	'page callback' => 'listar_docentes',
	'access callback'=> TRUE,
	'type'=> MENU_NORMAL_ITEM,
	'weight'=> -1,
	);

$items['oficina/departamentos/listar_departamentos']=array(
	'title' => 'Listar Departamentos',
	'access arguments'=> array('Listar Departamentos'),
	'type'=> MENU_DEFAULT_LOCAL_TASK,
	'weight'=> 0,
	);
$items['oficina/departamentos/alta_departamento'] = array(
 	'title' => 'Alta Departamento',
 	'access arguments' => array('Alta Departamento'),
 	'page callback' => 'al_departamento',
 	'page arguments' => array(2),
 	'type' => MENU_LOCAL_TASK,
	'weight'=> 1,
 	); 
$items['oficina/departamentos/baja_departamentos']=array(
	'title' => 'Baja Departamento',
	'access arguments'=> array('Baja Departamento'),
	'access callback'=> TRUE,
	'page callback' => 'ba_departamento',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 2,
	);
$items['oficina/departamentos/modificar_departamento']=array(
	'title' => 'Modificar Departamento',
	'access arguments'=> array('Modificar Departamento'),
	'access callback'=> TRUE,
	'page callback' => 'mo_departamento',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 3,
	);

$items['oficina/docentes']=array(	//Docentes
	'title' => 'DOCENTES',
	'access arguments'=> array('Listar Docentes'),
	'page callback' => 'listar_docentes',
	'access callback'=> TRUE,
	'type'=> MENU_NORMAL_ITEM,
	'weight'=> -1,
	);
$items['oficina/docentes/listar_docentes']=array(
	'title' => 'Listar Docentes',
	'access arguments'=> array('Listar Docentes'),
	'type'=> MENU_DEFAULT_LOCAL_TASK,
	'weight'=> 0,
	);
$items['oficina/docentes/alta_docente']=array(
	'title' => 'Alta Docente',
	'access arguments'=> array('Alta Docente'),
	'access callback'=> TRUE,
	'page callback' => 'alta_docente',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 1,
	);
$items['oficina/docentes/baja_docente']=array(
	'title' => 'Baja Docente',
	'access arguments'=> array('Baja Docente'),
	'access callback'=> TRUE,
	'page callback' => 'baja_docente',
	'type'=> MENU_LOCAL_TASK,
 	'weight'=> 2,
	);
$items['oficina/docentes/modificar_docente']=array(
	'title' => 'Modificar Docente',
	'access arguments'=> array('Modificar Docente'),
	'access callback'=> TRUE,
	'page callback' => 'modificar_docente',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 3,
	);	

$items['oficina/estudiantes']=array(		//Estudiantes
	'title' => 'ESTUDIANTES',
	'access arguments'=> array('Listar estudiantes'),
	'page callback' => 'alta_estudiante',
	'access callback'=> TRUE,
	'type'=> MENU_NORMAL_ITEM,
	'weight'=> -1,
	);
$items['oficina/estudiantes/listar_estudiantes']=array(
	'title' => 'Listar Estudiantes',
	'access arguments'=> array('Listar estudiantes'),
	'type'=> MENU_DEFAULT_LOCAL_TASK,
	'weight'=> 0,
	);
$items['oficina/estudiantes/alta_estudiante']=array(
	'title' => 'Alta Estudiante',
	'access arguments'=> array('Alta Estudiante'),
	'access callback'=> TRUE,
	'page callback' => 'alta_estudiante',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 1,
	);
$items['oficina/estudiantes/baja_estudiante']=array(
	'title' => 'Baja Estudiante',
	'access arguments'=> array('Baja Estudiante'),
	'access callback'=> TRUE,
	'page callback' => 'baja_estudiante',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 2,
	);
$items['oficina/estudiantes/modificar_estudiante']=array(
	'title' => 'Modificar Estudiante',
	'access arguments'=> array('Modificar Estudiante'),
	'access callback'=> TRUE,
	'page callback' => 'modificar_estudiante',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 3,
	);	

$items['oficina/historial_de_expedientes']=array(		//Expedientes 
	'title' => 'HISTORIAL DE EXPEDIENTES',
	'access arguments' => array('Historial de Expedientes'),
	'page callback' => 'expedientes_academicos',
	'access callback'=> TRUE,
	'type' => MENU_NORMAL_ITEM,
	'weight'=> -1,
	);

$items['oficina/materias']=array(		//Materias
	'title' => 'MATERIAS',
	'access arguments'=> array('Listar Materias'),
	'page callback' => 'alta_materia',
	'access callback'=> TRUE,
	'type'=> MENU_NORMAL_ITEM,
	'weight'=> -1,
	);	
$items['oficina/materias/listar_materias']=array(
	'title' => 'Listar Materias',
	'access arguments'=> array('Listar Materias'),
	'type'=> MENU_DEFAULT_LOCAL_TASK,
	'weight'=> 0,
	);
$items['oficina/materias/alta_materia']=array(
	'title' => 'Alta Materia',
	'access arguments'=> array('Alta Materia'),
	'access callback'=> TRUE,
	'page callback' => 'alta_materia',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 1,
	);
$items['oficina/materias/baja_materia']=array(
	'title' => 'Baja Materia',
	'access arguments'=> array('Baja Materia'),
	'access callback'=> TRUE,
	'page callback' => 'baja_materia',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 2,
	);
$items['oficina/materias/modificar_materia']=array(
	'title' => 'Modificar Materia',
	'access arguments'=> array('Modificar Materia'),
	'access callback'=> TRUE,
	'page callback' => 'modificar_materia',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 3,
	);
$items['oficina/registro_de_cursos']=array(		//Registro (matrículas)
	'title' => 'REGISTRO DE CURSOS',
	'access arguments'=> array('Registro de Cursos'),
	'page callback' => 'alta_materia',
	'access callback'=> TRUE,
	'type'=> MENU_NORMAL_ITEM,
	'weight'=> -1,
	);	
$items['oficina/registro_de_cursos/alta_registro']=array(
	'title' => 'Alta Registro',
	'access arguments'=> array('Alta Registro'),
	'type'=> MENU_DEFAULT_LOCAL_TASK,
	'weight'=> 0,
	);
$items['oficina/registro_de_cursos/baja_registro']=array(
	'title' => 'Baja Registro',
	'access arguments'=> array('Baja Registro'),
	'access callback'=> TRUE,
	'page callback' => 'baja_materia',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 1,
	);
$items['oficina/registro_de_cursos/modificar_registro']=array(
	'title' => 'Modificar Registro',
	'access arguments'=> array('Modificar Registro'),
	'access callback'=> TRUE,
	'page callback' => 'modificar_materia',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 2,
	);
$items['oficina/registro_de_cursos/Listar_registros']=array(
	'title' => 'Listar Registros',
	'access arguments'=> array('Listar Registros'),
	'access callback'=> TRUE,
	'page callback' => 'modificar_materia',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 3,
	);
 return $items;
 }

/**
 * Page callback
 
function menufun_greeting($first_name = '', $last_name = ''){
 return t('Hello @first_name @last_name', array('@first_name' => $first_name, '@last_name' => $last_name));
}*/

function overvie() {
 $output = t('The following flavors are available...');
 // ... more code here
 return $output;
 }
 
 function agregare() {

if (!$_POST){
$output='<form id="formAlta" action="http://localhost/drupal/colegio/inicia/dptos" method="post" accept-charset="UTF-8">
	<p>
	<fieldset form="formAlta">
	<legend align="left"><SPAN style="text-align:top">Introducir el nuevo departamento</SPAN></legend>
       <br><br>
	<p><SPAN style="text-align:center">   Nombre:   <input type="text" name="nombDpto" size="70"></SPAN></p>
	</fieldset>
	</p>
	<p><input type="submit" value="Grabar" style="font-weight:bold; color:black">  <input type="reset" value="Borrar" style="font-weight:bold; color:black">  <input type="button" style="font-wight:bold" value="Salir">
	</p>
	</form>';
}
else{

$output = "Departamento nuevo: " . $_POST["nombDpto"];
}
 //return t('A handy form to add flavors might go here...');
return $output;
 }
 
 function listare($type) {
 return t('List @type flavors', array('@type' => $type));
 }
function baja_est() {
 return ('hola');
 }

function al_departamento() {
 return ('alta dpto');
 }
function ba_departamento() {
 return ('baja departameno');
 }
function mo_departamento() {
 return ('modificar departamento');
 }

function listar_docentes() {
 return ('listar docentes');
 }
function alta_docente() {
 return ('alta docente');
 }
function baja_docente() {
 return ('baja docente');
 }
function modificar_docente() {
 return ('modificar docente');
 }

function alta_estudiante() {
 return ('alta estudiante');
 }
function baja_estudiante() {
 return ('baja estudiante');
 }
function modificar_estudiante() {
 return ('modificar estudiante');
 }

function alta_materia() {
$output="";

if (!$_POST){
$output='<form id="formAltaMateria" action="http://localhost/drupal/oficina/materias" method="post" accept-charset="UTF-8">
	<p>
	<fieldset form="formAltaMateria">
	<legend align="left"><SPAN style="text-align:top">Introducir una materia nueva</SPAN></legend>
       <br><br>
	<p><SPAN style="text-align:center">   Nombre:   <input type="text" name="nombMateria" size="70"></SPAN></p>
	</fieldset>
	</p>
	<p><input type="submit" value="Grabar" style="font-weight:bold; color:black">  <input type="reset" value="Borrar" style="font-weight:bold; color:black">  
	</p>
	</form>';
 } 
	else{
		$nombre=$_POST["nombMateria"];
		//$sql="INSERT INTO MATERIAS (ID_MATERIA, NOMBRE) VALUES (NULL, $nombre)";
		//$results=db_query($sql);

		$output= "Se ha insertado satisfactoriamente una nueva materia con el nombre: " . $nombre . "<br><br>";
		$output= $output . '<p>Si desea agragar otra materia <a href="http://localhost/drupal/oficina/materias"> pulse aqu&iacute;</a></p>';	
	}
return $output;


// return ('alta materia');
 }
function baja_materia() {
 return ('baja materia');
 }
function modificar_materia() {
 return ('modificar materia');
 }
function expedientes_academicos() {
 return ('expedientes acad&eacute;micos ññññ');
 }

function oficina_matriculas() {
GLOBAL $items;
$acento=utf8_encode('Matrículas ñ');
 return $acento . $items['oficina/matrículas']['title'];
 }