
<?php


/**
 * Implementation hook_menu().
 */
 function oficina_menu() {
 $items=array();

 $items['oficina/cursos_oficiales'] = array(	/************** Cursos Académicos **************/
 'title' => 'CURSOS OFICIALES',
 'page callback' => 'listar_unidades',
 'page arguments' => array('Unidades'),
 'access callback' => TRUE,
 'type' => MENU_NORMAL_ITEM,
 'weight' => -1,
 );
 $items['oficina/cursos_oficiales/unidades'] = array(
 'title' => 'Unidades',
 'access arguments' => array('Unidades'),
 'type' => MENU_DEFAULT_LOCAL_TASK,
 'weight' => 0,
 );
 $items['oficina/cursos_oficiales/cursos'] = array(
 'title' => 'Cursos',
 'access arguments' => array('Cursos'),
 'page callback' => 'listar_cursos',
 'type' => MENU_LOCAL_TASK,
 'weight' => 1,
 ); 
$items['oficina/cursos_oficiales/ciclos'] = array(
 'title' => 'Ciclos',
 'access arguments' => array('Ciclos'),
 'page callback' => 'listar_ciclos',
 'type' => MENU_LOCAL_TASK,
 'weight' => 2,
 );

$items['oficina/cursos_oficiales/cursos/listar_cursos'] = array(
 'title' => 'Listar Cursos',
 'access arguments' => array('Cursos'),
 'page callback' => 'listar_cursos',
 'page arguments' => array(2),
 'type' => MENU_LOCAL_TASK,
 'weight'=> 0,
 ); 
$items['oficina/cursos_oficiales/cursos/alta_curso'] = array(
 'title' => 'Alta Curso',
 'access arguments' => array('Cursos'),
 'page callback' => 'alta_curso',//50
 'page arguments' => array(2), 
 'type' => MENU_LOCAL_TASK,
 'weight'=> 2,	
 );
 $items['oficina/cursos_oficiales/cursos/baja_curso'] = array(
 'title' => 'Baja Curso',
 'access arguments' => array('Cursos'),
 'page callback' => 'baja_curso',
 'page arguments' => array(2), 
 'type' => MENU_LOCAL_TASK,
 'weight'=> 3,
 );
$items['oficina/cursos_oficiales/cursos/modificar_curso'] = array(
 'title' => 'Modificar Curso',
 'access arguments' => array('Cursos'),
 'page callback' => 'modificar_curso',
 'page arguments' => array(2),
 'type' => MENU_LOCAL_TASK,
 'weight'=> 1,
 );
			/******** Ciclos ********/

$items['oficina/cursos_oficiales/ciclos/listar_ciclos'] = array(
 'title' => 'Listar Ciclos',
 'access arguments' => array('Ciclos'),
 'page callback' => 'listar_ciclos',
 'page arguments' => array(2),
 'type' => MENU_LOCAL_TASK,
 'weight'=> 0,
 ); 
$items['oficina/cursos_oficiales/ciclos/alta_ciclo'] = array(
 'title' => 'Alta Ciclo',
 'access arguments' => array('ciclos'),
 'page callback' => 'alta_ciclo',
 'page arguments' => array(2), 
 'type' => MENU_LOCAL_TASK,
 'weight'=> 2,
 );
 $items['oficina/cursos_oficiales/ciclos/baja_ciclo'] = array(
 'title' => 'Baja Ciclo',
 'access arguments' => array('Ciclos'),
 'page callback' => 'baja_ciclo',
 'page arguments' => array(2), 
 'type' => MENU_LOCAL_TASK,
 'weight'=> 3,
 );
$items['oficina/cursos_oficiales/ciclos/modificar_ciclo'] = array(
 'title' => 'Modificar Ciclo',
 'access arguments' => array('Ciclos'),
 'page callback' => 'modificar_ciclo',//100
 'page arguments' => array(2),
 'type' => MENU_LOCAL_TASK,
 'weight'=> 1,
 );

$items['oficina/cursos_oficiales/unidades/listar_unidades'] = array(
 'title' => 'Listar Unidades',
 'access arguments' => array('Unidades'),
 'page callback' => 'listar_unidades',
 'page arguments' => array(2),
 'type' => MENU_LOCAL_TASK,
 'weight'=> 0,
 ); 
$items['oficina/cursos_oficiales/unidades/alta_unidad'] = array(
 'title' => 'Alta Unidad',
 'access arguments' => array('Unidades'),
 'page callback' => 'alta_unidad',
 'page arguments' => array(2), 
 'type' => MENU_LOCAL_TASK,
 'weight'=> 2,
 );
 $items['oficina/cursos_oficiales/unidades/baja_unidad'] = array(
 'title' => 'Baja Unidad',
 'access arguments' => array('Unidades'),
 'page callback' => 'baja_unidad',
 'page arguments' => array(2), 
 'type' => MENU_LOCAL_TASK,
 'weight'=> 3,
 );
$items['oficina/cursos_oficiales/unidades/modificar_unidad'] = array(
 'title' => 'Modificar Unidad',
 'access arguments' => array('Unidades'),
 'page callback' => 'modificar_unidad',
 'page arguments' => array(2), 
 'type' => MENU_LOCAL_TASK,
 'weight'=> 1,
 );

$items['oficina/departamentos']=array(		/*************** Departamentos *****************/
	'title' => 'DEPARTAMENTOS',
	'access arguments'=> array('Listar Departamentos'),
	'page callback' => 'listar_departamentos',
	'access callback'=> TRUE,
	'type'=> MENU_NORMAL_ITEM,
	'weight'=> -1,
	);

$items['oficina/departamentos/listar_departamentos']=array(
	'title' => 'Listar Departamentos',
	'access arguments'=> array('Listar Departamentos'),//150
	'type'=> MENU_DEFAULT_LOCAL_TASK,
	'weight'=> 0,
	);
$items['oficina/departamentos/alta_departamento'] = array(
 	'title' => 'Alta Departamento',
 	'access arguments' => array('Alta Departamento'),
 	'page callback' => 'alta_departamento',
 	'type' => MENU_LOCAL_TASK,
	'weight'=> 1,
 	); 
$items['oficina/departamentos/baja_departamento']=array(
	'title' => 'Baja Departamento',
	'access arguments'=> array('Baja Departamento'),
	'access callback'=> TRUE,
	'page callback' => 'baja_departamento',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 2,
	);
$items['oficina/departamentos/modificar_departamento']=array(
	'title' => 'Modificar Departamento',
	'access arguments'=> array('Modificar Departamento'),
	'access callback'=> TRUE,
	'page callback' => 'modificar_departamento',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 3,
	);

$items['oficina/docentes']=array(	//Docentes
	'title' => 'DOCENTES',
	'access arguments'=> array('Listar Docentes'),
	'page callback' => 'listar_docentes',
	'access callback'=> TRUE,
	'type'=> MENU_NORMAL_ITEM,
	'weight'=> -1,
	);
$items['oficina/docentes/listar_docentes']=array(
	'title' => 'Listar Docentes',
	'access arguments'=> array('Listar Docentes'),
	'type'=> MENU_DEFAULT_LOCAL_TASK,
	'weight'=> 0,
	);
$items['oficina/docentes/alta_docente']=array(
	'title' => 'Alta Docente',
	'access arguments'=> array('Alta Docente'),
	'access callback'=> TRUE,
	'page callback' => 'alta_docente',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 1,
	);//200
$items['oficina/docentes/baja_docente']=array(
	'title' => 'Baja Docente',
	'access arguments'=> array('Baja Docente'),
	'access callback'=> TRUE,
	'page callback' => 'baja_docente',
	'type'=> MENU_LOCAL_TASK,
 	'weight'=> 2,
	);
$items['oficina/docentes/modificar_docente']=array(
	'title' => 'Modificar Docente',
	'access arguments'=> array('Modificar Docente'),
	'access callback'=> TRUE,
	'page callback' => 'modificar_docente',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 3,
	);	

$items['oficina/estudiantes']=array(		/****************** Estudiantes ******************/
	'title' => 'ESTUDIANTES',
	'access arguments'=> array('Listar estudiantes'),
	'page callback' => 'listar_estudiantes',
	'access callback'=> TRUE,
	'type'=> MENU_NORMAL_ITEM,
	'weight'=> -1,
	);
$items['oficina/estudiantes/listar_estudiantes']=array(
	'title' => 'Listar Estudiantes',
	'access arguments'=> array('Listar estudiantes'),
	'type'=> MENU_DEFAULT_LOCAL_TASK,
	'weight'=> 0,
	);
$items['oficina/estudiantes/alta_estudiante']=array(
	'title' => 'Alta Estudiante',
	'access arguments'=> array('Alta Estudiante'),
	'access callback'=> TRUE,
	'page callback' => 'alta_estudiante',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 1,
	);
$items['oficina/estudiantes/baja_estudiante']=array(
	'title' => 'Baja Estudiante',
	'access arguments'=> array('Baja Estudiante'),
	'access callback'=> TRUE,
	'page callback' => 'baja_estudiante',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 2,
	);
$items['oficina/estudiantes/modificar_estudiante']=array(
	'title' => 'Modificar Estudiante',
	'access arguments'=> array('Modificar Estudiante'),//250
	'access callback'=> TRUE,
	'page callback' => 'modificar_estudiante',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 3,
	);	

$items['oficina/historial_de_expedientes']=array(	/***************** Expedientes  *************/
	'title' => 'HISTORIAL DE EXPEDIENTES',
	'access arguments' => array('Historial de Expedientes'),
	'page callback' => 'expedientes_academicos',
	'access callback'=> TRUE,
	'type' => MENU_NORMAL_ITEM,
	'weight'=> -1,
	);

$items['oficina/materias']=array(	/**************** Materias *****************/
	'title' => 'MATERIAS',
	'access arguments'=> array('Listar Materias'),
	'page callback' => 'listar_materias',
	'access callback'=> TRUE,
	'type'=> MENU_NORMAL_ITEM,
	'weight'=> -1,
	);	
$items['oficina/materias/listar_materias']=array(
	'title' => 'Listar Materias',
	'access arguments'=> array('Listar Materias'),
	'type'=> MENU_DEFAULT_LOCAL_TASK,
	'weight'=> 0,
	);
$items['oficina/materias/alta_materia']=array(
	'title' => 'Alta Materia',
	'access arguments'=> array('Alta Materia'),
	'access callback'=> TRUE,
	'page callback' => 'alta_materia',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 1,
	);
$items['oficina/materias/baja_materia']=array(
	'title' => 'Baja Materia',
	'access arguments'=> array('Baja Materia'),
	'access callback'=> TRUE,
	'page callback' => 'baja_materia',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 2,
	);
$items['oficina/materias/modificar_materia']=array(
	'title' => 'Modificar Materia',
	'access arguments'=> array('Modificar Materia'),
	'access callback'=> TRUE,
	'page callback' => 'modificar_materia',//300
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 3,
	);
$items['oficina/registro_de_estudiantes']=array(	/************** Registro (matrículas) *************/
	'title' => 'REGISTRO DE ESTUDIANTES',
	'access arguments'=> array('Registro de Cursos'),
	'page callback' => 'alta_materia',
	'access callback'=> TRUE,
	'type'=> MENU_NORMAL_ITEM,
	'weight'=> -1,
	);	
$items['oficina/registro_de_estudiantes/alta_registro']=array(
	'title' => 'Alta Registro',
	'access arguments'=> array('Alta Registro'),
	'type'=> MENU_DEFAULT_LOCAL_TASK,
	'weight'=> 0,
	);
$items['oficina/registro_de_estudiantes/baja_registro']=array(
	'title' => 'Baja Registro',
	'access arguments'=> array('Baja Registro'),
	'access callback'=> TRUE,
	'page callback' => 'baja_materia',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 1,
	);
$items['oficina/registro_de_estudiantes/modificar_registro']=array(
	'title' => 'Modificar Registro',
	'access arguments'=> array('Modificar Registro'),
	'access callback'=> TRUE,
	'page callback' => 'modificar_materia',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 2,
	);
$items['oficina/registro_de_estudiantes/Listar_registros']=array(
	'title' => 'Listar Registros',
	'access arguments'=> array('Listar Registros'),
	'access callback'=> TRUE,
	'page callback' => 'modificar_materia',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 3,
	);
 return $items;
 }

/**
 * Page callback
**/
/*function menufun_greeting($first_name = '', $last_name = ''){
 return t('Hello @first_name @last_name', array('@first_name' => $first_name, '@last_name' => $last_name));
}*/ 
//351

function overvie() {
 $output = t('The following flavors are available...');
 // ... more code here
 return $output;
 }
 
function agregare() {

if (!$_POST){
$output='<form id="formAlta" action="http://localhost/drupal/colegio/inicia/dptos" method="post" accept-charset="UTF-8">
	<p>
	<fieldset form="formAlta">
	<legend align="left"><SPAN style="text-align:top">Introducir el nuevo departamento</SPAN></legend>
       <br><br>
	<p><SPAN style="text-align:center">   Nombre:   <input type="text" name="nombDpto"></SPAN></p>
	</fieldset>
	</p>
	<p><input type="submit" value="Grabar" style="font-weight:bold; color:black">  <input type="reset" value="Borrar" style="font-weight:bold; color:black">  <input type="button" style="font-wight:bold" value="Salir">
	</p>
	</form>';
}
else{

$output = "Departamento nuevo: " . $_POST["nombDpto"];
}
 //return t('A handy form to add flavors might go here...');
return $output;
 }
 
 function listare($type) {
 return t('List @type flavors', array('@type' => $type));
 }
function baja_est() {
 return ('hola');
 }
/*********************
		**** Base de Datos Externa *****
						*******************************/
function bdexterna(){
$conn=mysqli_connect("localhost", "colegio", "colegio", "colegio");
	if (!$conn){
		die("Conexión ha fallado:" . mysqli_connect_error());
	}
mysqli_select_db($conn, "colegio");	
return($conn);
}

/**********
		*********************** Cursos oficiales ***********************
***********/

/******** Ciclos **********/

function listar_ciclos(){
$output="";
$tamano_pagina="2";

if(array_key_exists('pagina', $_GET)){
	$pagina=$_GET["pagina"];
}
else{
	$pagina=1;
}

$conexion=bdexterna();

$sql="SELECT * FROM ciclos";
$result=mysqli_query($conexion, $sql);
$total_filas=mysqli_num_rows($result);
$total_paginas=ceil($total_filas / $tamano_pagina);

$sql="SELECT * FROM ciclos LIMIT " . (($pagina-1) * $tamano_pagina) . "," . $tamano_pagina;
$result=mysqli_query($conexion, $sql);
$output='<p align="center"><b><font size="4">Listado de los Ciclos del centro</font></b></p>';
$output=$output . '<table border="2"><tr><th><font size="3">Identificador</font></th><th><font size="3">Nombre Ciclo</font></th></th><th><font size="3">N&uacute;mero Convocatorias</font></th></tr>';
if($total_filas > 0){
	while ($row=mysqli_fetch_assoc($result)){
		$output=$output . '<tr><td><font color="blue" size="2">'. $row["ID_CICLO"] . '</font></td><td><font color="blue" size="2">' . $row["NOMBRE"] . '</font></td><td><font color="blue" size="2">' . $row["NUM_CONV"] . '</font></td></tr>';
	}
	$output=$output . '</table><br>';
}

mysqli_close($conexion);

if ($total_paginas > 1){
	for ($i=1;$i<=$total_paginas;$i++){
		if($pagina == $i){
			$output=$output . 'P&aacute;gina ' . $pagina . "&nbsp;&nbsp;";
		}
		else{
			$output=$output . '<a href="http://localhost/drupal/oficina/cursos_oficiales/ciclos/listar_ciclos?pagina=' . $i . '">P&aacute;gina ' . $i . '</a>&nbsp;&nbsp;';
		}

	}
}

return $output;
} 	/** end listar_ciclos **/


function alta_ciclo(){
$output="";//400

if (!$_POST){
	$output='<form id="formAltaCiclo" action="" method="post" accept-charset="UTF-8" size="100%">
	<p>
	<fieldset form="formAltaCiclo">
	<legend align="left"><SPAN style="text-align:top">Introducir un nuevo ciclo</SPAN></legend>
        <br><br>
	<p><SPAN style="text-align:center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nombre de Ciclo:&nbsp;<input type="text" style="color:blue" name="nombCiclo" required autofocus></SPAN></p>
	<p><SPAN style="text-align:center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;N&uacute;mero de Convocatorias:&nbsp;<input type="number" style="color:blue" name="numConv" min="1" max="3" required></SPAN></p>
	</fieldset>
	</p>
	<p><input type="submit" value="Agregar" style="font-weight:bold; color:black">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" value="Limpiar" style="font-weight:bold; color:black">  
	</p>
	</form>';
 }elseif ($_POST["nombCiclo"] == ""){
		$output='<br><b>Atenci&oacute;n</b><br><br><p>No puede dar de alta un Ciclo sin nombre</p><p>Para volver hacia atr&aacute;s&nbsp;<a href="http://localhost/drupal/oficina/cursos_oficiales/ciclos/alta_ciclo">pulse aqu&iacute;</a></p>'; 

	}
/*elseif ((ereg("^[1-3], $_POST["numConv"])) {
	$output='<br><b>Atenci&oacute;n</b><br><br><p>El numero de convocatorias tiene que ser un numero entre 1 y 3.</p>';
}*/
else{
	$conexion=bdexterna();

	$nombre=$_POST["nombCiclo"];
	$Conv=$_POST["numConv"];
	
	mysqli_select_db($conexion, "colegio");
	$sql="INSERT INTO ciclos (ID_CICLO, NOMBRE, NUM_CONV) VALUES (NULL, '$nombre', '$Conv')";
	
	if(mysqli_query($conexion, $sql)){
		$ant_id=mysqli_insert_id($conexion);
		$output= '<p><b>Nuevo ciclo registrado satisfactoriamente con:</b></p>
		<p>Identificador&nbsp;<b>' . $ant_id . '</b></p> 
		<p>Nombre&nbsp; <b>' . $nombre . '</b></p>
		<p>N&uacute;mero de convocatorias&nbsp; <b>' . $Conv . '</b></p>
		<br><br>
		<p align="center">Si desea agregar otro ciclo <a href="http://localhost/drupal/oficina/cursos_oficiales/ciclos/alta_ciclo">pulse aqu&iacute;</a></p>'; 
	}
	
	mysqli_close($conexion);
}

return $output;

} 	/** end alta_ciclo **/


function baja_ciclo(){
$output="";
$conexion=bdexterna();	

if (!$_POST){
	$output='<form id="formBajaCiclo" action="" method="post" accept-charset="UTF-8" size="100%">
	<p>
	<fieldset form="formBajaCiclo">
	<legend align="left"><SPAN style="text-align:top">Eliminar un ciclo</SPAN></legend>
        <br><br>
	<p><SPAN style="text-align:top">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Seleccionar un ciclo:&nbsp;<p align="center"><select name="nombCiclo" size="2">';
	
	$sql="SELECT nombre FROM ciclos";
	$result=mysqli_query($conexion, $sql);
	if (mysqli_num_rows($result) > 0){
		while($row=mysqli_fetch_assoc($result)){
			$output= $output . '<option>' . $row["nombre"] . '</option>';
		}//501
	}
	else{
		  $output= $output . '<option></option>';
	}
	$output= $output . '</p></select></fieldset>
	</p>
	<p><input type="submit" value="Eliminar" style="font-weight:bold; color:black">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" value="Limpiar" style="font-weight:bold; color:black">  
	</p>
	</form>';
} 
else{
	$nombre=$_POST["nombCiclo"];
	$sql="SELECT ID_CICLO FROM ciclos WHERE NOMBRE='$nombre'";
	$result=mysqli_query($conexion, $sql);
	$id=mysqli_fetch_array($result);
	$sql="DELETE FROM ciclos WHERE NOMBRE='$nombre'";
	if(mysqli_query($conexion, $sql)){	
		$output= '<p><b>El ciclo seleccionado se ha borrado satisfactoriamente con:</b></p>
		<p>Identificador&nbsp;<b>' .$id[0] . '</b></p> 
		<p>Nombre&nbsp;<b>' . $nombre . '</b></p><br><br>';
		$output=$output . '<p align="center">Si desea eliminar otro ciclo&nbsp;<a href="http://localhost/drupal/oficina/cursos_oficiales/ciclos/baja_ciclo">pulse aqu&iacute;</a></p>';		
	}
	else{
		$output='<p><b>Error al eliminar el registro con el nombre:&nbsp;' . $nombre . '<b></p>';
		$output=$output . '<p>'. mysqli_error($conexion) . '</p>';
	}

}
mysqli_close($conexion);
return $output;

} 	/** end baja_ciclo **/

	
function modificar_ciclo(){
$output="";
$error=false;

$conexion=bdexterna();
if (!$_POST){
	$output='<form id="formModCiclo" action="" method="post" accept-charset="UTF-8" size="100%">
	<p>
	<fieldset form="formModCiclo">
	<legend align="left"><SPAN style="text-align:top">Cambiar un ciclo</SPAN></legend>
        <br><br>
	<SPAN style="text-align:center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Seleccionar un ciclo:&nbsp;<p align="center"><select name="nombCiclo" size="5" required>';
	
	$sql="SELECT nombre, num_conv FROM ciclos";
	$result=mysqli_query($conexion, $sql);
	if (mysqli_num_rows($result) > 0){
		while($row=mysqli_fetch_assoc($result)){
			$output= $output . '<option>' . $row["nombre"] . '</option>';
			//$id=$row["id_ciclo"];$conv=$row["num_conv"];
		}
	}
	else{
		  $output= $output . '<option></option>';
	}
	$output= $output . '</select></p></SPAN>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Introducir datos a modificar:</p>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nombre:&nbsp;<input type="text" style="color:blue" name="nuevoNomb"></p>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Convocatorias:&nbsp;<input type="number" style="color:blue" name="nuevoConv" placeholder="N&uacute;merico entre 1 y 3"></p>';
	

/*<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Indicar los datos a modificar:&nbsp;<p align="center"><select name="campo" size="1">
	<option selected>Elegir...</option>
	<option>Nombre</option>
	<option>N&uacute;mero Convocatorias</option>
	</select>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nuevo dato a cambiar:&nbsp;<input type="text" style="color:blue" name="nuevo"></p></p><br>';
	if ($_POST["campo"]=="Nombre"){
		$output=$output . '<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Indicar el nuevo nombre:&nbsp; <input type="text" style="color:blue" name="nuevoNomb"></p>';
	}else{
		$output=$output . '<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Indicar el nuevo n&uacute;mero de convocatorias:&nbsp; <input type="text" style="color:blue" name="nuevoConv"></p>';
}*/

	$output=$output . '</fieldset>
	</p>
	<p><input type="submit" value="Grabar" style="font-weight:bold; color:black">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" value="Limpiar" style="font-weight:bold; color:black">  
	</p>
	</form>';

} 
else{
	$nombre=$_POST["nombCiclo"];
	$nombnuevo=$_POST["nuevoNomb"];
	$convnuevo=$_POST["nuevoConv"];
	
	//mysqli_select_db($conexion, "colegio");
	$sql="SELECT ID_CICLO FROM ciclos WHERE NOMBRE='$nombre'";
	$result=mysqli_query($conexion, $sql);
	$id=mysqli_fetch_array($result);
	$num=$id[0];

	if (($nombnuevo == "") && ($convnuevo == "")){
		$output='<br><br><font color="red"><b>Atenci&oacute;n</b></font><br><br><p>No ha introducido ning&uacute;n dato para actualizar el registro seleccionado:&nbsp;<b>' . $nombre . '</b></p>&nbsp;';
		$output=$output . '<br><p align="center">Para volver a intentarlo&nbsp;<a href="http://localhost/drupal/oficina/cursos_oficiales/ciclos/modificar_ciclo">pulse aqu&iacute;</a></p>';
	} 
	else{
		$output= '<br><br><p><b>Actualizaci&oacute;n del registro seleccionado.</b></p>'; 
		if ($nombnuevo == ""){
			if (($convnuevo < "1") || ($convnuevo >="3")){
				$output= $output . '<p>El rango n&uacute;merico introducido para el campo convocatorias no es correcto</p>';
				$output= $output . '<br><p align="center">Para volver a modificarlo,&nbsp;<a href="http://localhost/drupal/oficina/cursos_oficiales/ciclos/modificar_ciclo">pulse aqu&iacute;</a></p>';
			}else{
				$sql="UPDATE ciclos SET NUM_CONV='$convnuevo' WHERE ID_CICLO= '$id[0]'";
				if(mysqli_query($conexion, $sql)){	
					$output=$output . '<p>El registro seleccionado, se ha actualizado con el n&uacute;mero de convocatorias igual a:&nbsp;<b>' . $convnuevo . '</b></p>';
					$output=$output . '<br><p align="center">Si desea modificar otro departamento&nbsp;<a href="http://localhost/drupal/oficina/cursos_oficiales/ciclos/modificar_ciclo">pulse aqu&iacute;</a></p>';
				}
				else{
					$error=true;
				}
			}
		}elseif ($convnuevo == ""){
			$sql="UPDATE ciclos SET NOMBRE='$nombnuevo' WHERE ID_CICLO= '$id[0]'";
			if(mysqli_query($conexion, $sql)){	
				$output=$output . '<p>El registro seleccionado, se ha actualizado con el nuevo nombre:&nbsp;<b>' . $nombnuevo . '</b></p>';
				$output=$output . '<br><p align="center">Si desea modificar otro departamento&nbsp;<a href="http://localhost/drupal/oficina/cursos_oficiales/ciclos/modificar_ciclo">pulse aqu&iacute;</a></p>';
			}
			else{
				$error=true;
			}
		}else{
			if (($convnuevo >= "1") || ($convnuevo <="3")){
				$output= $output . '<p>El rango n&uacute;merico introducido para el campo convocatorias no es correcto</p>';
				$output= $output . '<br><p align="center">Para volver a modificarlo,&nbsp;<a href="http://localhost/drupal/oficina/cursos_oficiales/ciclos/modificar_ciclo">pulse aqu&iacute;</a></p>';
			}else{
				$sql="UPDATE ciclos SET NOMBRE='$nombnuevo', NUM_CONV='$nombnuevo' WHERE ID_CICLO= '$id[0]'";
				if(mysqli_query($conexion, $sql)){	
					$output=$output . '<p>El registro seleccionado, se ha actualizado con:</p>'; 
					$output=$output . '<p>Nuevo nombre&nbsp;<b>' . $nombnuevo .'</b></p><p>N&uacute;mero de convocatorias&nbsp;<b>' . $convnuevo . '</b></p>';
					$output=$output . '<br><p align="center">Si desea modificar otro departamento&nbsp;<a href="http://localhost/drupal/oficina/cursos_oficiales/ciclos/modificar_ciclo">pulse aqu&iacute;</a></p>';
				}
				else{
					$error=true;
				}
			}
		}
	}
	if ($error){
		$output='<p><b>Se ha producido un Error al actualizar el registro con el nombre:&nbsp;' . $nombre . '</b></p>';
		$output=$output . '<p>'. mysqli_error($conexion) . '</p>';
	}

} 
mysqli_close($conexion);
return $output;

} 	/** end modificar_ciclo **/


/******** Cursos **********/

function listar_cursos(){
$output="";
$tamano_pagina="10";

if(array_key_exists('pagina', $_GET)){
	$pagina=$_GET["pagina"];
}
else{
	$pagina=1;
}

$conexion=bdexterna();

$sql="SELECT * FROM cursos";
$result=mysqli_query($conexion, $sql);
$total_filas=mysqli_num_rows($result);
$total_paginas=ceil($total_filas / $tamano_pagina);

$sql="SELECT * FROM cursos LIMIT " . (($pagina-1) * $tamano_pagina) . "," . $tamano_pagina;
$result=mysqli_query($conexion, $sql);
$output='<p align="center"><b><font size="4">Listado de los Cursos del centro</font></b></p>';
$output=$output . '<table border="2"><tr><th><font size="3">Identificador</font></th><th><font size="3">Nombre Curso</font></th></tr>';
if($total_filas > 0){
	while ($row=mysqli_fetch_assoc($result)){
		$output=$output . '<tr><td><font color="blue" size="2">'. $row["ID_CURSO"] . '</font></td><td><font color="blue" size="2">' . $row["NOMBRE"] . '</font></td></tr>';
	}
	$output=$output . '</table><br>';
}

mysqli_close($conexion);

if ($total_paginas > 1){
	for ($i=1;$i<=$total_paginas;$i++){
		if($pagina == $i){
			$output=$output . 'P&aacute;gina ' . $pagina . "&nbsp;&nbsp;";
		}
		else{
			$output=$output . '<a href="http://localhost/drupal/oficina/cursos_oficiales/cursos/listar_cursos?pagina=' . $i . '">P&aacute;gina ' . $i . '</a>&nbsp;&nbsp;';
		}

	}
}

return $output;
} 	/** end listar_cursos **/


function alta_curso(){
$output="";

$conexion=bdexterna();

if (!$_POST){
	$output='<form id="formAltaCurso" action="" method="post" accept-charset="UTF-8" size="100%">
	<p>
	<fieldset form="formAltaCurso">
	<legend align="left"><SPAN style="text-align:top">Introducir un nuevo curso</SPAN></legend>
        <br><br>
	<p><SPAN style="text-align:center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nombre de Curso:&nbsp;<input type="text" style="color:blue" name="nombCurso" required autofocus></SPAN></p>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Asignar un Ciclo:&nbsp;<p align="center"><select name="Ciclo" required size="4">';
	$sql="SELECT nombre FROM ciclos";
	$result=mysqli_query($conexion, $sql);
	if (mysqli_num_rows($result) > 0){
		while($row=mysqli_fetch_assoc($result)){
			$output= $output . '<option>' . $row["nombre"] . '</option>';
		}
	}
	else{
		  $output= $output . '<option></option>';
	}
	$output=$output . '</select></p>
	</fieldset>
	</p>
	<p><input type="submit" value="Agregar" style="font-weight:bold; color:black">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" value="Limpiar" style="font-weight:bold; color:black">  
	</p>
	</form>';
 }elseif ($_POST["nombCurso"] == ""){
		$output='<br><b>Atenci&oacute;n</b><br><br><p>No puede dar de alta un Curso sin nombre</p><p>Para volver hacia atr&aacute;s&nbsp;<a href="http://localhost/drupal/oficina/cursos_oficiales/cursos/alta_curso">pulse aqu&iacute;</a></p>'; 

}
else{
	$nombre=$_POST["nombCurso"];
	$nombCiclo=$_POST["Ciclo"];
	$sql="SELECT ID_CICLO FROM ciclos WHERE NOMBRE='$nombCiclo'";
	$result=mysqli_query($conexion, $sql);
	$idCiclo=mysqli_fetch_array($result);
	$sql="INSERT INTO cursos (ID_CURSO, NOMBRE, ID_CICLO) VALUES (NULL, '$nombre', '$idCiclo[0]')";
	if(mysqli_query($conexion, $sql)){
		$ant_id=mysqli_insert_id($conexion);
		$output= '<p><b>Nuevo curso registrado satisfactoriamente con:</b></p>
		<p>Identificador&nbsp;<b>' . $ant_id . '</b></p> 
		<p>Nombre&nbsp; <b>' . $nombre . '</b></p>
		<p>Ciclo del curso&nbsp; <b>' . $nombCiclo . '</b></p>
		<br><br>
		<p align="center">Si desea agregar otro curso <a href="http://localhost/drupal/oficina/cursos_oficiales/cursos/alta_curso">pulse aqu&iacute;</a></p>'; 
	}	
}
mysqli_close($conexion);
return $output;

} 	/** end alta_curso **/


function baja_curso(){
$output="";
$conexion=bdexterna();

if (!$_POST){
	$output='<form id="formBajaCurso" action="" method="post" accept-charset="UTF-8" size="100%">
	<p>
	<fieldset form="formBajaCurso">
	<legend align="left"><SPAN style="text-align:top">Eliminar un ciclo</SPAN></legend>
        <br><br>
	<p><SPAN style="text-align:top">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Seleccionar un curso:&nbsp;<p align="center"><select name="nombCurso" size="5">';
	
	$sql="SELECT nombre FROM cursos";
	$result=mysqli_query($conexion, $sql);
	if (mysqli_num_rows($result) > 0){
		while($row=mysqli_fetch_assoc($result)){
			$output= $output . '<option>' . $row["nombre"] . '</option>';
		}
	}
	else{
		  $output= $output . '<option></option>';
	}
	$output= $output . '</select></p></SPAN></p></fieldset>
	</p>
	<p><input type="submit" value="Eliminar" style="font-weight:bold; color:black">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" value="Limpiar" style="font-weight:bold; color:black">  
	</p>
	</form>';
} 
else{
	$nombre=$_POST["nombCurso"];
	//mysqli_select_db($conexion, "colegio");
	$sql="SELECT ID_CURSO FROM cursos WHERE NOMBRE='$nombre'";
	$result=mysqli_query($conexion, $sql);
	$id=mysqli_fetch_array($result);
	$sql="DELETE FROM cursos WHERE NOMBRE='$nombre'";
	if(mysqli_query($conexion, $sql)){	
		$output= '<p><b>El curso seleccionado se ha borrado satisfactoriamente con:</b></p>
		<p>Identificador&nbsp;<b>' . $id[0] . '</b></p> 
		<p>Nombre&nbsp;<b>' . $nombre . '</b></p><br><br>';
		$output=$output . '<p align="center">Si desea eliminar otro curso&nbsp;<a href="http://localhost/drupal/oficina/cursos_oficiales/cursos/baja_curso">pulse aqu&iacute;</a></p>';		
	}
	else{
		$output='<p><b>Error al eliminar el registro con el nombre:&nbsp;' . $nombre . '<b></p>';
		$output=$output . '<p>'. mysqli_error($conexion) . '</p>';
	}

}
mysqli_close($conexion);
return $output;

} 	/** end baja_curso **/

	
function modificar_curso(){
$output="";

$conexion=bdexterna();

if (!$_POST){
	$output='<form id="formModCurso" action="" method="post" accept-charset="UTF-8" size="100%">
	<p>
	<fieldset form="formModCurso">
	<legend align="left"><SPAN style="text-align:top">Cambiar un ciclo</SPAN></legend>
        <br><br>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Seleccionar un Curso:&nbsp;<p align="center"><select name="nombCurso" size="5" required>';
	
	$sql="SELECT nombre FROM cursos";
	$result=mysqli_query($conexion, $sql);
	if (mysqli_num_rows($result) > 0){
		while($row=mysqli_fetch_assoc($result)){
			$output= $output . '<option>' . $row["nombre"] . '</option>';
		}
	}
	else{
		  $output= $output . '<option></option>';
	}
	$output= $output . '</select></p>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Indicar el nuevo nombre del curso:&nbsp;<input type="text" style="color:blue" name="nuevoNomb" required></p>
	</fieldset>
	<p><input type="submit" value="Grabar" style="font-weight:bold; color:black">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" value="Limpiar" style="font-weight:bold; color:black">  
	</p>
	</form>';

} 
else{
	$nombre=$_POST["nombCurso"];
	$nombnuevo=$_POST["nuevoNomb"];
	//mysqli_select_db($conexion, "colegio");
	$sql="SELECT ID_CURSO FROM cursos WHERE NOMBRE='$nombre'";
	$result=mysqli_query($conexion, $sql);
	$id=mysqli_fetch_array($result);
	$num=$id[0];

	if ($nombnuevo == ""){
		$output='<br><br><font color="red"><b>Atenci&oacute;n</b></font><br><br><p>No ha introducido ning&uacute;n dato para actualizar el registro seleccionado:&nbsp;<b>' . $nombre . '</b></p>&nbsp;';
		$output=$output . '<br><p align="center">Para volver a intentarlo&nbsp;<a href="http://localhost/drupal/oficina/cursos_oficiales/cursos/modificar_curso">pulse aqu&iacute;</a></p>';
	} 
	else{
		$output= '<br><br><p><b>Actualizaci&oacute;n del registro seleccionado.</b></p>'; 
		$sql="UPDATE cursos SET NOMBRE='$nombnuevo' WHERE ID_CURSO= '$id[0]'";
			if(mysqli_query($conexion, $sql)){	
				$output=$output . '<p>El registro seleccionado, se ha actualizado con el nuevo nombre:&nbsp;<b>' . $nombnuevo . '</b></p>';
				$output=$output . '<br><p align="center">Si desea modificar otro Curso&nbsp;<a href="http://localhost/drupal/oficina/cursos_oficiales/cursos/modificar_curso">pulse aqu&iacute;</a></p>';
			}
			else{
				$output='<p><b>Se ha producido un Error al actualizar el registro con el nombre:&nbsp;' . $nombre . '</b></p>';
				$output=$output . '<p>'. mysqli_error($conexion) . '</p>';
			}
	}
} 
mysqli_close($conexion);
return $output;

} 	/** end modificar_curso **/



/******** Unidades **********/

function listar_unidades(){
$output="";
$tamano_pagina="10";

if(array_key_exists('pagina', $_GET)){
	$pagina=$_GET["pagina"];
}
else{
	$pagina=1;
}

$conexion=bdexterna();

$sql="SELECT * FROM grupos_a";
$result=mysqli_query($conexion, $sql);
$total_filas=mysqli_num_rows($result);
$total_paginas=ceil($total_filas / $tamano_pagina);

$sql="SELECT * FROM grupos_a LIMIT " . (($pagina-1) * $tamano_pagina) . "," . $tamano_pagina;
$result=mysqli_query($conexion, $sql);
$output='<p align="center"><b><font size="4">Listado de las Unidades del centro</font></b></p>';
$output=$output . '<table border="2"><tr><th><font size="3">Identificador</font></th><th><font size="3">Nombre Unidad</font></th><th><font size="3">Aula</font></th><th><font size="3">Dia de Tutoria</font></th><th><font size="3">Hora de Tutoria</font></th></tr>';
if($total_filas > 0){
	while ($row=mysqli_fetch_assoc($result)){
		$output=$output . '<tr><td><font color="blue" size="2">'. $row["ID_GRUPOSA"] . '</font></td><td><font color="blue" size="2">' . $row["NOMBRE"] . '</font></td><td><font color="blue" size="2">' . $row["AULA"] . '</font></td><td><font color="blue" size="2">' . $row["DIA_TUTORIA"] . '</font></td><td><font color="blue" size="2">' . $row["HORA_TUTORIA"] . '</font></td></tr>';
	}
	$output=$output . '</table><br>';
}

mysqli_close($conexion);

if ($total_paginas > 1){
	for ($i=1;$i<=$total_paginas;$i++){
		if($pagina == $i){
			$output=$output . 'P&aacute;gina ' . $pagina . "&nbsp;&nbsp;";
		}
		else{
			$output=$output . '<a href="http://localhost/drupal/oficina/cursos_oficiales/unidades/listar_unidades?pagina=' . $i . '">P&aacute;gina ' . $i . '</a>&nbsp;&nbsp;';
		}

	}
}

return $output;
} 	/** end listar_unidades **/


function alta_unidad(){
$output="";

$conexion=bdexterna();

if (!$_POST){
	$output='<form id="formAltaUnidad" action="" method="post" accept-charset="UTF-8" size="100%">
	<p>
	<fieldset form="formAltaUnidad">
	<legend align="left"><SPAN style="text-align:top">Introducir una nueva unidad</SPAN></legend>
        <br><br>
	<p><SPAN style="text-align:center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nombre de Unidad:&nbsp;<input type="text" style="color:blue" name="nombUnidad" required autofocus></SPAN></p>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Asignar un Curso:&nbsp;<p align="center"><select name="Curso" required size="4">';
	$sql="SELECT nombre FROM cursos";
	$result=mysqli_query($conexion, $sql);
	if (mysqli_num_rows($result) > 0){
		while($row=mysqli_fetch_assoc($result)){
			$output= $output . '<option>' . $row["nombre"] . '</option>';
		}
	}
	else{
		  $output= $output . '<option></option>';
	}
	$output=$output . '</select></p>
	<p><SPAN style="text-align:center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Aula aignada:&nbsp;<input type="text" style="color:blue" name="Aula"></SPAN></p>
	<p><SPAN style="text-align:center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;D&iacute;a de Tutor&iacute;a:&nbsp;<input type="text" style="color:blue" name="diaTutoria"></SPAN></p>
	<p><SPAN style="text-align:center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Hora de Tutor&iacute;a:&nbsp;<input type="time" style="color:blue" name="horaTutoria"></SPAN></p>
	</fieldset>
	</p>
	<p><input type="submit" value="Agregar" style="font-weight:bold; color:black">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" value="Limpiar" style="font-weight:bold; color:black">  
	</p>
	</form>';
 }elseif ($_POST["nombUnidad"] == ""){
		$output='<br><b>Atenci&oacute;n</b><br><br><p>No puede dar de alta una Unidad sin nombre</p><p>Para volver hacia atr&aacute;s&nbsp;<a href="http://localhost/drupal/oficina/cursos_oficiales/unidades/alta_unidad">pulse aqu&iacute;</a></p>'; 

}
else{
	$nombre=$_POST["nombUnidad"];
	$nombCurso=$_POST["Curso"];
	$aula=$_POST["Aula"];
	$diat=$_POST["diaTutoria"];
	$horat=$_POST["horaTutoria"];
	$sql="SELECT ID_CURSO FROM cursos WHERE NOMBRE='$nombCurso'";
	$result=mysqli_query($conexion, $sql);
	$idCurso=mysqli_fetch_array($result);

	$sql="INSERT INTO grupos_a (ID_GRUPOSA, ID_CURSO, NOMBRE, AULA, DIA_TUTORIA, HORA_TUTORIA) VALUES (NULL, '$idCurso[0]', '$nombre', '$aula', '$diat', '$horat')";
	if(mysqli_query($conexion, $sql)){
		$ant_id=mysqli_insert_id($conexion);
		$output= '<br><p><b>Nueva unidad registrada satisfactoriamente con:</b></p>
		<p>Identificador&nbsp;<b>' . $ant_id . '</b></p> 
		<p>Unidad&nbsp; <b>' . $nombre . '</b></p>
		<p>Curso de la Unidad&nbsp; <b>' . $nombCurso . '</b></p>
		<p>Aula de la unidad&nbsp; <b>' . $aula . '</b></p>
		<p>D&iacute;a de la semana de tutor&iacute;a&nbsp; <b>' . $diat . '</b></p>
		<p>Hora de tutor&iacute;a&nbsp;<b>' . $horat . '</b></p>
		<br><br>
		<p align="center">Si desea agregar otra unidad <a href="http://localhost/drupal/oficina/cursos_oficiales/unidades/alta_unidad">pulse aqu&iacute;</a></p>'; 
	}	
}
mysqli_close($conexion);
return $output;

} 	/** end alta_unidad **/

function baja_unidad(){
$output="";
$conexion=bdexterna();

if (!$_POST){
	$output='<form id="formBajaUnidad" action="" method="post" accept-charset="UTF-8" size="100%">
	<p>
	<fieldset form="formBajaUnidad">
	<legend align="left"><SPAN style="text-align:top">Eliminar una unidad</SPAN></legend>
        <br><br>
	<p><SPAN style="text-align:top">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Seleccionar una unidad:&nbsp;<p align="center"><select name="nombUnidad" size="2">';
	
	$sql="SELECT nombre FROM grupos_a";
	$result=mysqli_query($conexion, $sql);
	if (mysqli_num_rows($result) > 0){
		while($row=mysqli_fetch_assoc($result)){
			$output= $output . '<option>' . $row["nombre"] . '</option>';
		}//501
	}
	else{
		  $output= $output . '<option></option>';
	}
	$output= $output . '</select></p></p></fieldset>
	</p>
	<p><input type="submit" value="Eliminar" style="font-weight:bold; color:black">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" value="Limpiar" style="font-weight:bold; color:black">  
	</p>
	</form>';
} 
else{
	$nombre=$_POST["nombUnidad"];
	$sql="SELECT ID_GRUPOSA FROM grupos_a WHERE NOMBRE='$nombre'";
	$result=mysqli_query($conexion, $sql);
	$id=mysqli_fetch_array($result);
	$sql="DELETE FROM unidades WHERE NOMBRE='$nombre'";
	if(mysqli_query($conexion, $sql)){	
		$output= '<p><b>La unidad seleccionada se ha borrado satisfactoriamente con:</b></p>
		<p>Identificador&nbsp;<b>' .$id[0] . '</b></p> 
		<p>Nombre&nbsp;<b>' . $nombre . '</b></p><br><br>';
		$output=$output . '<p align="center">Si desea eliminar otra unidad&nbsp;<a href="http://localhost/drupal/oficina/cursos_oficiales/unidades/baja_unidad">pulse aqu&iacute;</a></p>';		
	}
	else{
		$output='<p><b>Error al eliminar el registro con el nombre:&nbsp;' . $nombre . '<b></p>';
		$output=$output . '<p>'. mysqli_error($conexion) . '</p>';
	}

}
mysqli_close($conexion);
return $output;

}        /** end baja_unidad  **/


function modificar_unidad(){
$output="";
$error=false;

$conexion=bdexterna();

if (!$_POST){
	$output='<form id="formModUnidad" action="" method="post" accept-charset="UTF-8" size="100%">
	<p>
	<fieldset form="formModUnidad">
	<legend align="left"><SPAN style="text-align:top">Cambiar un unidad</SPAN></legend>
        <br><br>
	<SPAN style="text-align:center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Seleccionar una unidad:&nbsp;<p><select name="nombUnidad" size="5" required>';
	
	$sql="SELECT nombre FROM grupos_a";
	$result=mysqli_query($conexion, $sql);
	if (mysqli_num_rows($result) > 0){
		while($row=mysqli_fetch_assoc($result)){
			$output= $output . '<option>' . $row["nombre"] . '</option>';
			//$id=$row["id_ciclo"];$conv=$row["num_conv"];
		}
	}
	else{
		  $output= $output . '<option></option>';
	}
	$output= $output . '</select></p></SPAN>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Introducir datos a modificar:</p>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nombre:&nbsp;<input type="text" style="color:blue" name="nuevoNomb"></p>
	<p><SPAN style="text-align:center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Aula aignada:&nbsp;<input type="text" style="color:blue" name="Aula"></SPAN></p>
	<p><SPAN style="text-align:center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;D&iacute;a de Tutor&iacute;a:&nbsp;<input type="text" style="color:blue" name="diaTutoria"></SPAN></p>
	<p><SPAN style="text-align:center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Hora de Tutor&iacute;a:&nbsp;<input type="time" style="color:blue" name="horaTutoria"></SPAN></p>';
	$output=$output . '</fieldset>
	</p>
	<p><input type="submit" value="Grabar" style="font-weight:bold; color:black">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" value="Limpiar" style="font-weight:bold; color:black">  
	</p>
	</form>';
} 
else{
	$nombre=$_POST["nombUnidad"];
	$nombnuevo=$_POST["nuevoNomb"];
	$aula=$_POST["Aula"];
	$diat=$_POST["diaTutoria"];
	$horat=$_POST["horaTutoria"];
	//mysqli_select_db($conexion, "colegio");
	$sql="SELECT ID_GRUPOSA FROM grupos_a WHERE NOMBRE='$nombre'";
	$result=mysqli_query($conexion, $sql);
	$id=mysqli_fetch_array($result);
	$num=$id[0];

	if (($nombnuevo == "") && ($aula == "") && ($diat == "") && ($horat == "")){
		$output='<br><br><font color="red"><b>Atenci&oacute;n</b></font><br><br><p>No ha introducido ning&uacute;n dato para actualizar el registro seleccionado:&nbsp;<b>' . $nombre . '</b></p>&nbsp;';
		$output=$output . '<br><p align="center">Para volver a intentarlo&nbsp;<a href="http://localhost/drupal/oficina/cursos_oficiales/unidades/modificar_unidad">pulse aqu&iacute;</a></p>';
	} 
	else{
		$output= '<br><br><p><b>Actualizaci&oacute;n del registro seleccionado.</b></p>'; 
		if ($nombnuevo <> ""){
			$sql="UPDATE grupos_a SET NOMBRE= '$nombnuevo' WHERE ID_GRUPOSA= '$id[0]'";
			if(mysqli_query($conexion, $sql)){
				$output=$output . '<p>Nombre actualizado:&nbsp;<b>' . $nombnuevo . '</b></p>';
			} 
			else{
				$error=true;	 
			}
		} 
		if ($aula <> ""){
			$sql="UPDATE grupos_a SET AULA= '$aula' WHERE ID_GRUPOSA= '$id[0]'";
			if(mysqli_query($conexion, $sql)){
				$output= $output . '<p>Aula actualizada::&nbsp;<b>' . $aula . '</b></p>';
			} 
			else{
				$error=true;	 
			}
		} 
		if ($diat <> ""){	
			$sql="UPDATE grupos_a SET DIA_TUTORIA= '$diat' WHERE ID_GRUPOSA= '$id[0]'";
			if(mysqli_query($conexion, $sql)){
				$output=$output . '<p>D&iacute;a de tutor&iacute;a actualizado:&nbsp;<b>' . $diat . '</b></p>';
			} 
			else{
				$error=true;	 
			}
		} 
		if ($horat <> ""){	
			$sql="UPDATE grupos_a SET HORA_TUTORIA= '$horat' WHERE ID_GRUPOSA= '$id[0]'";
			if(mysqli_query($conexion, $sql)){
				$output=$output . '<p>Hora de tutor&iacute;a actualizado:&nbsp;<b>' . $horat . '</b></p>';
			} 
			else{
				$error=true;	 
			}
		}

		if ($error){
			$output='<p><b>Se ha producido un Error al actualizar el registro con el nombre:&nbsp;' . $nombre . '</b></p>';
			$output=$output . '<p>'. mysqli_error($conexion) . '</p>';
		}
		else{
			$output=$output . '<br><p align="center">Si desea modificar otra Uniad&nbsp;<a href="http://localhost/drupal/oficina/cursos_oficiales/unidades/modificar_unidad">pulse aqu&iacute;</a></p>';
		}
	}
	
} 
mysqli_close($conexion);
return $output;

}	/** end modificar_unidad **/

/**********
		*********************** Departamentos ***********************
***********/

function listar_departamentos() {
$output="";
$tamano_pagina="15";

if(array_key_exists('pagina', $_GET)){
	$pagina=$_GET["pagina"];
}
else{
	$pagina=1;
}

$conexion=bdexterna();

$sql="SELECT * FROM departamentos";
$result=mysqli_query($conexion, $sql);
$total_filas=mysqli_num_rows($result);
$total_paginas=ceil($total_filas / $tamano_pagina);

$sql="SELECT * FROM departamentos LIMIT " . (($pagina-1) * $tamano_pagina) . "," . $tamano_pagina;
$result=mysqli_query($conexion, $sql);
$output='<p align="center"><b><font size="4">Listado de los Departamentos activos en el centro</font></b></p>';
$output=$output . '<table border="2"><tr><th><font size="2">Identificador</font></th><th><font size="2">Nombre Departamento</font></th></tr>';
if($total_filas > 0){
	while ($row=mysqli_fetch_assoc($result)){
		$output=$output . '<tr><td><font color="blue" size="2">'. $row["ID_DPTO"] . '</font></td><td><font color="blue" size="2">' . $row["NOMBRE"] . '</font></td></tr>';
	}
	$output=$output . '</table><br>';
}

mysqli_close($conexion);

if ($total_paginas > 1){
	for ($i=1;$i<=$total_paginas;$i++){
		if($pagina == $i){
			$output=$output . 'P&aacute;gina ' . $pagina . "&nbsp;&nbsp;";
		}
		else{
			$output=$output . '<a href="http://localhost/drupal/oficina/departamentos/listar_departamentos?pagina=' . $i . '">P&aacute;gina ' . $i . '</a>&nbsp;&nbsp;';
		}

	}
}

return $output;
}  /** end listar_departamentos **/

function alta_departamento() {
$output="";

if (!$_POST){
$output='<form id="formAltaDpto" action="" method="post" accept-charset="UTF-8" size="100%">
	<p>
	<fieldset form="formAltaDpto">
	<legend align="left"><SPAN style="text-align:top">Introducir un nuevo departamento</SPAN></legend>
        <br><br>
	<p><SPAN style="text-align:center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nombre Departamento:&nbsp;<input type="text" style="color:blue" name="nombDpto" required autofocus></SPAN></p>
	</fieldset>
	</p>
	<p><input type="submit" value="Agregar" style="font-weight:bold; color:black">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" value="Limpiar" style="font-weight:bold; color:black">  
	</p>
	</form>';
 }
elseif ($_POST["nombDpto"] == ""){
		$output='<br><b>Atenci&oacute;n</b><br><br><p>No puede dar de alta un Departamento sin nombre</p><p>Para volver hacia atr&aacute;s&nbsp;<a href="http://localhost/drupal/oficina/departamentos/alta_departamento">pulse aqu&iacute;</a></p>'; 

} 
else{
	$conexion=bdexterna();
	$nombre=$_POST["nombDpto"];
	mysqli_select_db($conexion, "colegio");
	$sql="INSERT INTO departamentos (ID_DPTO, NOMBRE) VALUES (NULL, '$nombre')";
	
	if(mysqli_query($conexion, $sql)){
		$ant_id=mysqli_insert_id($conexion);
		$output= '<p><b>Nuevo departamento registrado satisfactoriamente</b>.</p><p>Identificador de nuevo registro: <b>' . $ant_id . '</b></p> 
		<p>Nombre del nuevo registro: <b>' . $nombre . '</b></p><br><br>
		<p align="center">Si desea agregar otro departamento <a href="http://localhost/drupal/oficina/departamentos/alta_departamento">pulse aqu&iacute;</a></p>'; 
	}
	
	mysqli_close($conexion);
}

return $output;
} /** end alta_departamento **/



function baja_departamento() {
$output="";
$conexion=bdexterna();	

if (!$_POST){
	$output='<form id="formBajaDpto" action="" method="post" accept-charset="UTF-8" size="100%">
	<p>
	<fieldset form="formBajaDpto">
	<legend align="left"><SPAN style="text-align:top">Eliminar un departamento</SPAN></legend>
        <br><br>
	<p><SPAN style="text-align:top">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Seleccionar un Departamento:&nbsp;<p align="center"><select name="nombDpto" size="5" required>';
	
	$sql="SELECT nombre FROM departamentos";
	$result=mysqli_query($conexion, $sql);
	if (mysqli_num_rows($result) > 0){
		while($row=mysqli_fetch_assoc($result)){
			$output= $output . '<option>' . $row["nombre"] . '</option>';
		}
	}
	else{
		  $output= $output . '<option></option>';
	}
	$output= $output . '</p></select></fieldset>
	</p>
	<p><input type="submit" value="Eliminar" style="font-weight:bold; color:black">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" value="Limpiar" style="font-weight:bold; color:black">  
	</p>
	</form>';
} 
else{
	$nombre=$_POST["nombDpto"];
	//mysqli_select_db($conexion, "colegio");
	$sql="SELECT ID_DPTO FROM departamentos WHERE NOMBRE='$nombre'";
	$result=mysqli_query($conexion, $sql);
	$id=mysqli_fetch_array($result);
	$sql="DELETE FROM departamentos WHERE NOMBRE='$nombre'";
	if(mysqli_query($conexion, $sql)){	
		$output= '<p><b>El departamento seleccionado se ha borrado satisfactoriamente</b>.</p>
		<p>Identificador del registro: <b>' .$id[0] . '</b></p> 
		<p>Nombre del registro: <b>' . $nombre . '</b></p><br><br>';
		$output=$output . '<p align="center">Si desea eliminar otro departamento&nbsp;<a href="http://localhost/drupal/oficina/departamentos/baja_departamento">pulse aqu&iacute;</a></p>';		
	}
	else{
		$output='<p><b>Error al eliminar el registro con el nombre:&nbsp;' . $nombre . '<b></p>';
		$output=$output . '<p>'. mysqli_error($conexion) . '</p>';
	}
}
mysqli_close($conexion);
return $output;
 }  /** end baja_departamento **/


function modificar_departamento() {
$output="";

$conexion=bdexterna();	

if (!$_POST){
	$output='<form id="formModDpto" action="" method="post" accept-charset="UTF-8" size="100%">
	<p>
	<fieldset form="formModDpto">
	<legend align="left"><SPAN style="text-align:top">Cambiar un departamento</SPAN></legend>
        <br><br>
	<p><SPAN style="text-align:center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Seleccionar un Departamento:&nbsp;<p align="center"><select name="nombDpto" size="5" required>';
	
	$sql="SELECT nombre FROM departamentos";
	$result=mysqli_query($conexion, $sql);
	if (mysqli_num_rows($result) > 0){
		while($row=mysqli_fetch_assoc($result)){
			$output= $output . '<option>' . $row["nombre"] . '</option>';
			//$id=$row["id_dpto"];
		}
	}
	else{
		  $output= $output . '<option></option>';
	}
	$output= $output . '</p></select>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Indicar el nuevo nombre de departamento:&nbsp; <input type="text" style="color:blue" name="nuevo" required></p></fieldset>
	</p>
	<p><input type="submit" value="Grabar" style="font-weight:bold; color:black">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" value="Limpiar" style="font-weight:bold; color:black">  
	</p>
	</form>';
} 
else{
	$nombre=$_POST["nombDpto"];
	$nombnuevo=$_POST["nuevo"];
	mysqli_select_db($conexion, "colegio");
	$sql="SELECT ID_DPTO FROM departamentos WHERE NOMBRE='$nombre'";
	$result=mysqli_query($conexion, $sql);
	$id=mysqli_fetch_array($result);
	//$num=$id[0];
	if ($nombnuevo == ""){
		$output='<br><br><font color="red"><b>Atenci&oacute;n</b></font><br><br><p>No ha introducido ning&uacute;n dato para actualizar el registro seleccionado:&nbsp;<b>' . $nombre . '</b></p>&nbsp;';
		$output=$output . '<br><p align="center">Para volver a intentarlo&nbsp;<a href="http://localhost/drupal/oficina/departamentos/modificar_departamento">pulse aqu&iacute;</a></p>';
	} 
	else{
		$sql="UPDATE departamentos SET NOMBRE='$nombnuevo' WHERE ID_DPTO= '$id[0]'";
		if(mysqli_query($conexion, $sql)){
			$output= '<p><b>El departamento seleccionado se ha actualizado satisfactoriamente.</b></p> 
			<p>Nombre anterior del registro: <b>' . $_POST["nombDpto"] . '</b></p><p>Se ha actualizado por el nombre: <b>' . $_POST["nuevo"] . '</b></p>
			<p>Identificador de registro: <b>' . $id[0] . '</b></p><br>';
			$output=$output . '<p align="center">Si desea modificar otro departamento&nbsp;<a href="http://localhost/drupal/oficina/departamentos/modificar_departamento">pulse aqu&iacute;</a></p>'; 
		}
		else{
			$output='<p><b>Error al actualizar el registro con el nombre:&nbsp;' . $nombre . '<b></p>';
			$output=$output . '<p>'. mysqli_error($conexion) . '</p>';
		}
	}
} 
mysqli_close($conexion);
return $output;

}  /** end modificar_departamento  **/

/**********
		*********************** Docentes ***********************
***********/

function listar_docentes() {
$output="";
$tamano_pagina="2";

if(array_key_exists('pagina', $_GET)){
	$pagina=$_GET["pagina"];
}
else{
	$pagina=1;
}

$conexion=bdexterna();

$sql="SELECT * FROM docentes";
$result=mysqli_query($conexion, $sql);
$total_filas=mysqli_num_rows($result);
$total_paginas=ceil($total_filas / $tamano_pagina);

$sql="SELECT * FROM docentes LIMIT " . (($pagina-1) * $tamano_pagina) . "," . $tamano_pagina;
$result=mysqli_query($conexion, $sql);
$output='<p align="center"><b><font size="4">Listado de los Docentes del centro</font></b></p>';
$output=$output . '<table border="2"><tr>
<th><font size="2">Identificador</font></th>
<th><font size="2">DNI</font></th>
<th><font size="2">Nombre</font></th>
<th><font size="2">Apellidos</font></th></tr>';
if($total_filas > 0){
	while ($row=mysqli_fetch_assoc($result)){
		$output=$output . '<tr>
		<td><font color="blue" size="2">'. $row["ID_DOCENTES"] . '</font></td>
		<td><font color="blue" size="2">' . $row["DNI_D"] . '</font></td>
		<td><font color="blue" size="2">'. $row["NOMBRE"] . '</font></td>
		<td><font color="blue" size="2">'. $row["APELLIDOS"] . '</font></td></tr>';
	}
	$output=$output . '</table><br>';
}



if ($total_paginas > 1){
	for ($i=1;$i<=$total_paginas;$i++){
		if($pagina == $i){
			$output=$output . 'P&aacute;gina ' . $pagina . "&nbsp;&nbsp;";
		}
		else{
			$output=$output . '<a href="http://localhost/drupal/oficina/docentes/listar_docentes?pagina=' . $i . '">P&aacute;gina ' . $i . '</a>&nbsp;&nbsp;';
		}

	}
}

if (!$_POST){
	$output=$output . '<form id="formBuscarDocente" action="" method="post" accept-charset="UTF-8" size="100%">
	<br><br><p>Datos de un docente de la lista:&nbsp;&nbsp;&nbsp;<input style="color:blue" type="text" name="buscardni" placeholder="D.N.I." required>&nbsp;&nbsp;&nbsp;
	<input type="submit" value="Buscar" style="font-weight:bold; color:black"></form>';
}
else{
	
	$dni=$_POST["buscardni"];
	$output= '<br><p align="center"><b>DATOS DE DOCENTE CON DNI ' . $dni . '</b>.</p>';
	$sql="SELECT * FROM docentes WHERE dni_d='$dni'";
	$result=mysqli_query($conexion, $sql);
	$row=mysqli_fetch_assoc($result);
	if ($row["NOMBRE"]==""){ 
		$output=$output . '<p align="center"><b><font color="red">Error:&nbsp;</font></b>el dni&nbsp;<b>' . $dni . '</b>&nbsp;no es de la lista de docentes</p>';
	}else{
		$dpto=$row["ID_DPTO"];
		if ($result){
			$output=$output . '<p>Nombre:&nbsp;<b>' . $row["NOMBRE"] . '</b></p>
			<p>Apellidos:&nbsp;<b>' . $row["APELLIDOS"] . '</b></p>
			<p>Direcci&oacute;n:&nbsp;<b>' . $row["DIRECCION"] . '</b></p>
			<p>Localidad:&nbsp;<b>' . $row["LOCALIDAD"] . '</b></p>
			<p>Provincia:&nbsp;<b>' . $row["PROVINCIA"] . '</b></p>
			<p>C&oacute;digo Postal:&nbsp;<b>' . $row["CODIGO_P"] . '</b></p>
			<p>Tel&eacute;fono:&nbsp;<b>' . $row["TELF_FIJO"] . '</b></p>
			<p>M&oacute;vil:&nbsp;<b>' . $row["MOVIL"] . '</b></p>
			<p>Direcci&oacute;n de correo:&nbsp;<b>' . $row["EMAIL"] . '</b></p>
			<p>Categor&iacute;a:&nbsp;<b>' . $row["TIPO_D"] . '</b></p>';
			$jefe=$row["JEFE_DPTO"];
			//mysqli_select_db($conexion, "colegio");
			$sql="SELECT * FROM departamentos WHERE id_dpto='$dpto'";
			$result=mysqli_query($conexion, $sql);
			$nombDpto=mysqli_fetch_assoc($result);
		
			if ($jefe=='1'){
				$output=$output . '<p>Jefe de Departamento:&nbsp;<b>' . $nombDpto["NOMBRE"] . '</b></p>';
			}else{
				$output=$output . '<p>Departamento:&nbsp;<b>' . $nombDpto["NOMBRE"] . '</b></p>';
			}
		 
		}else{
			$output=$output . '<p align="center"><b>Incorrecto el DNI, no se encuentra</b></p>';
		}
	}
	
}

mysqli_close($conexion);

return $output;
}	/** end listar_docentes **/


function alta_docente() {
$output="";
$conexion=bdexterna();

if (!$_POST){
$output='<form id="formAltaDocente" action="" method="post" accept-charset="UTF-8" size="100%">
	<p>
	<fieldset form="formAltaDocente">
	<legend align="left"><SPAN style="text-align:top">Introducir datos personales del nuevo docente</SPAN></legend>
        <br><br>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DNI/NIF:&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" style="color:blue" name="dniDocente" maxlength="9" required autofocus>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nombre:&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" style="color:blue" name="nombDocente" required></p>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Apellidos:&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" style="color:blue" name="apellidosDocente" required>	
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Direcci&oacute;n:&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" style="color:blue" name="dirDocente"></p>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Localidad:&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" style="color:blue" name="localidadDocente">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Provincia:&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" style="color:blue" name="provDocente"></p>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;C&oacute;digo Postal:&nbsp;&nbsp;&nbsp;&nbsp;<input type="num" style="color:blue" name="cpDocente" maxlength="5">		
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tel&eacute;fono fijo:&nbsp;&nbsp;&nbsp;&nbsp;<input type="tel" style="color:blue" name="telDocente" maxlength="9"></p>	
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;M&oacute;vil:&nbsp;&nbsp;&nbsp;&nbsp;<input type="tel" style="color:blue" name="movilDocente" maxlength="9">		
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Email:&nbsp;&nbsp;&nbsp;&nbsp;<input type="email" style="color:blue" name="emailDocente"></p>	
	</fieldset>
	</p>
	<p>
	<fieldset form="formAltaDocente">
	<legend align="left"><SPAN style="text-align:top">Introducir datos profesionales del nuevo docente</SPAN></legend>
        <br><br>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Seleccionar categor&iacute;a:&nbsp;<p align="center"><select name="categoriaDocente" required size="2">
		<option>Maestro/a</option><option>Profresor/a</option></select></p>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Seleccionar Departamento:&nbsp;<p align="center"><select name="dptoDocente" required size="6">';
	
	$sql="SELECT nombre FROM departamentos";
	$result=mysqli_query($conexion, $sql);
	if (mysqli_num_rows($result) > 0){
		while($row=mysqli_fetch_assoc($result)){
			$output= $output . '<option>' . $row["nombre"] . '</option>';
		}
	}
	else{
		  $output= $output . '<option></option>';
	}

	$output=$output . '</select></p>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Jefe de Departamento:&nbsp;&nbsp;&nbsp;&nbsp;
		<input type="radio" name="jefeDptoDocente" value="0" checked>&nbsp;&nbsp;&nbspNo&nbsp;&nbsp;&nbsp;
		<input type="radio" name="jefeDptoDocente" value="1">&nbsp;&nbsp;&nbspSi</p>		
	</fieldset>
	</p>
	<p><input type="submit" value="Agregar" style="font-weight:bold; color:black">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" value="Limpiar" style="font-weight:bold; color:black">  
	</p>
	</form>';
 }
elseif (($_POST['dniDocente'] == "") && ($_POST['nombDocente'] == "") && ($_POST['apellidosDocente'] == "")){
		$output='<br><font color="red"><b>Atenci&oacute;n</b></font><br><br><p>No puede dar de alta un Docente sin introducir los datos requeridos (DNI, NOMBRE, APELLIDOS)</p><p align="center">Para volver hacia atr&aacute;s&nbsp;<a href="http://localhost/drupal/oficina/docentes/alta_docente">pulse aqu&iacute;</a></p>'; 

} 
else{
	$nombDpto=$_POST["dptoDocente"];$dniD=$_POST["dniDocente"];$nombD=$_POST["nombDocente"];$apellD=$_POST["apellidosDocente"];$dirD=$_POST["dirDocente"];$localidadD=$_POST["localidadDocente"];
	$provD=$_POST["provDocente"];$cpD=$_POST["cpDocente"];$telD=$_POST["telDocente"];$movilD=$_POST["movilDocente"];$emailD=$_POST["emailDocente"];$categoriaD=$_POST["categoriaDocente"];$jefeD=$_POST["jefeDptoDocente"];
	$sql="SELECT id_dpto FROM departamentos WHERE nombre='$nombDpto'";//1499
	$result=mysqli_query($conexion, $sql);
	$idDpto=mysqli_fetch_array($result);
	$sql="INSERT INTO docentes (ID_DOCENTES, ID_DPTO, DNI_D, NOMBRE, APELLIDOS, TIPO_D, JEFE_DPTO, MOVIL, DIRECCION, LOCALIDAD, CODIGO_P, PROVINCIA, EMAIL, TELF_FIJO) VALUES (NULL, '$idDpto[0]', '$dniD', '$nombD', '$apellD', '$categoriaD', '$jefeD', '$movilD', '$dirD', '$localidadD', '$cpD', '$provD', '$emailD', '$telD')";
	if(mysqli_query($conexion, $sql)){
		$ant_id=mysqli_insert_id($conexion);
		$output= '<p><b>Nuevo Docente registrado satisfactoriamente</b>.</p><p>Identificador de nuevo registro:&nbsp<b>' . $ant_id . '</b></p> 
		<p>Nombre:&nbsp<b>' . $_POST["nombDocente"] . '</b></p>
		<p>Apellidos:&nbsp<b>' . $_POST["apellidosDocente"] . '</b></p>
		<p>D.N.I.:&nbsp<b>' . $_POST["dniDocente"] . '</b></p>
		<p>Direcci&oacute;n:&nbsp<b>' . $_POST["dirDocente"] . '</b></p>
		<p>Localidad:&nbsp<b>' . $_POST["localidadDocente"] . '</b></p>
		<p>Provincia:&nbsp<b>' . $_POST["provDocente"] . '</b></p>
		<p>C&oacute;digo Postal:&nbsp<b>' . $_POST["cpDocente"] . '</b></p>
		<p>Tel&eacute;fono:&nbsp<b>' . $_POST["telDocente"] . '</b></p>
		<p>M&oacute;vil:&nbsp<b>' . $_POST["movilDocente"] . '</b></p>
		<p>Direcci&oacute;n de correo:&nbsp<b>' . $_POST["emailDocente"] . '</b></p>
		<p>Categor&iacute;a:&nbsp<b>' . $_POST["categoriaDocente"] . '</b></p>
		<p>Departamento:&nbsp<b>' . $_POST["dptoDocente"] . '</b></p>
		<p>Jefe de Departamento:&nbsp';
		if ($_POST["jefeDptoDocente"]){
			 	$output= $output . '<b>Si</b></p>';
			}
			else{
				$output= $output . '<b>No</b></p>';
			}
		$output= $output . '<br><br>
		<p align="center">Si desea agregar otro departamento <a href="http://localhost/drupal/oficina/docentes/alta_docente">pulse aqu&iacute;</a></p>'; 
	}
	
}

mysqli_close($conexion);

return $output;
}	/** end alta_docente  **/


function baja_docente() {
$output="";
$conexion=bdexterna();

if (!$_POST){
	$output='<form id="formBajaDocente" action="" method="post" accept-charset="UTF-8" size="100%">
	<p>
	<fieldset form="formBajaDocente">
	<legend align="left"><SPAN style="text-align:top">Eliminar un docente</SPAN></legend>
        <br><br>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Seleccionar D.N.I. de docente:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<p align="center">
	<select required name="dniDocente" size="6">';
	$sql="SELECT * FROM docentes";
	$result=mysqli_query($conexion, $sql);
	if (mysqli_num_rows($result) > 0){
		while($row=mysqli_fetch_assoc($result)){
			$output= $output . '<option>' . $row["DNI_D"] . '</option>';
		}
	}
	else{
		  $output= $output . '<option></option>';
	}

	$output=$output . '</select></p></p>
	</fieldset>
	<p><input type="submit" value="Eliminar" style="font-weight:bold; color:black">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" value="Limpiar" style="font-weight:bold; color:black">  
	</p>
	</form>';
} 
else{
	$dni=$_POST["dniDocente"];
	$sql="SELECT * FROM docentes WHERE dni_d='$dni'";
	$result=mysqli_query($conexion, $sql);
	$id=mysqli_fetch_array($result);
	//$sql="DELETE FROM docentes WHERE ID_DOCENTES='$id[0]'";
			//if(mysqli_query($conexion, $sql)){	
				$output= $output .'<p><b>El docente seleccionado se ha borrado satisfactoriamente</b>.</p>
				<p>Identificador del registro: <b>' .$id[0] . '</b></p> 
				<p>DNI del docente: <b>' . $id[2] . '</b></p>
				<p>Nombre del docente: <b>' . $id[3] . '</b></p>
				<p>Apellidos del docente: <b>' . $id[4] . '</b></p><br><br>';
				$output=$output . '<p align="center">Si desea eliminar otro docente&nbsp;<a href="http://localhost/drupal/oficina/docentes/baja_docente">pulse aqu&iacute;</a></p>';		
			//}
			//else{
			//	$output='<p><b>Error al eliminar el registro con el D.N.I.:&nbsp;' . $dni . '<b></p>';
			//	$output=$output . '<p>'. mysqli_error($conexion) . '</p>';
			//}
}

mysqli_close($conexion);
return $output;

}	/** end baja_docente  **/


function modificar_docente() {
$output="";
$conexion=bdexterna();

if (!$_POST){
	
	$output='<form id="formModDocente" action="" method="post" accept-charset="UTF-8" size="100%">
	<p>
	<fieldset form="formModDocente">
	<legend align="left"><SPAN style="text-align:top">Cambiar datos de un docente</SPAN></legend>
        <br><br>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Seleccionar un D.N.I. de docente:&nbsp;<p align="center"><select name="dniDocente" size="5" required>';
	
	$sql="SELECT dni_d FROM docentes";
	$result=mysqli_query($conexion, $sql);
	if (mysqli_num_rows($result) > 0){
		while($row=mysqli_fetch_assoc($result)){
			$output= $output . '<option>' . $row["dni_d"] . '</option>';
		}
	}
	else{
		  $output= $output . '<option></option>';
	}
	$output= $output . '</select></p>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Indicar tipo de datos a modificar:&nbsp;<p align="center"><select name="tipoDatos" size="2" required>
	<option>Personales</option><option>Profesionales</option></select>
	</p>
	</fieldset>
	</p>
	<p><input type="submit" name="Siguiente" value="Siguiente" style="font-weight:bold; color:black">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	<input type="reset" value="Limpiar" style="font-weight:bold; color:black"></p>';
} 
elseif (isset($_POST["Siguiente"])){
	$dni=$_POST["dniDocente"];
	$tipod=$_POST["tipoDatos"];
	
	$sql="SELECT * FROM docentes WHERE dni_d='$dni'";
	$result=mysqli_query($conexion, $sql);
	$row=mysqli_fetch_array($result);
	$output='<form id="formAltaDocS" action="" method="post" accept-charset="UTF-8" size="100%">
	<p><fieldset form="formAltaDocS">';
	if ($tipod == "Personales"){
		$output=$output . '<legend align="left"><SPAN style="text-align:top">Modificar datos personales del docente</SPAN></legend>
        	<br><br>
		<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DNI/NIF:&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" style="color:blue" name="dniDocente" maxlength="9" value="' . $row[2] . '" required autofocus>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nombre:&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" style="color:blue" name="nombDocente" value="' . $row[3] . '"required></p>
		<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Apellidos:&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" style="color:blue" name="apellidosDocente" value="' . $row[4] . '"required>	
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Direcci&oacute;n:&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" style="color:blue" name="dirDocente" value="' . $row[8] . '"></p>
		<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Localidad:&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" style="color:blue" name="localidadDocente" value="' . $row[9] . '">
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Provincia:&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" style="color:blue" name="provDocente" value="' . $row[11] . '"></p>
		<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;C&oacute;digo Postal:&nbsp;&nbsp;&nbsp;&nbsp;<input type="num" style="color:blue" name="cpDocente" maxlength="5" value="' . $row[10] . '">		
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tel&eacute;fono fijo:&nbsp;&nbsp;&nbsp;&nbsp;<input type="tel" style="color:blue" name="telDocente" maxlength="9" value="' . $row[13] . '"></p>	
		<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;M&oacute;vil:&nbsp;&nbsp;&nbsp;&nbsp;<input type="tel" style="color:blue" name="movilDocente" maxlength="9" value="' . $row[7] . '">		
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Email:&nbsp;&nbsp;&nbsp;&nbsp;<input type="email" style="color:blue" name="emailDocente" value="' . $row[12] . '"></p>
		<input type="hidden" name="oculto" value="Personales"><input type="hidden" value="' . $row[0] . '" name="idDocente">';	
	}
	else{
		if($row[5]=="Maestro/a"){
			$cadena1='<option selected>Maestro/a</option><option>Profresor/a</option></select>';
		}
		else{
			$cadena1='<option>Maestro/a</option><option selected>Profresor/a</option></select>';
		}
		if($row[6]=='1'){
			$cadena2='<input type="radio" name="jefeDptoDocente" value="No" >&nbsp;&nbsp;&nbspNo&nbsp;&nbsp;&nbsp;
				<input type="radio" name="jefeDptoDocente" value="Si" checked>&nbsp;&nbsp;&nbspSi</p>';
		}
		else{
			$cadena2='<input type="radio" name="jefeDptoDocente" value="0" checked>&nbsp;&nbsp;&nbspNo&nbsp;&nbsp;&nbsp;
				<input type="radio" name="jefeDptoDocente" value="1">&nbsp;&nbsp;&nbspSi</p>';
		}
		$output=$output . '<legend align="left"><SPAN style="text-align:top">Modificar datos profesionales del docente</SPAN></legend>
        	<br><br>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Categor&iacute;a:&nbsp;<p align="center"><select name="categoriaDocente" required size="2">' . $cadena1 . '</p>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Departamento:&nbsp;<p align="center"><select name="dptoDocente" required size="6">';
	
		$sql="SELECT id_dpto, nombre FROM departamentos";
		$result=mysqli_query($conexion, $sql);
		if (mysqli_num_rows($result) > 0){
			while($dpto=mysqli_fetch_assoc($result)){
				if($row[1]==$dpto["id_dpto"]){
					$output= $output . '<option selected>' . $dpto["nombre"] . '</option>';
				}
				else{
					$output= $output . '<option>' . $dpto["nombre"] . '</option>';
				}
			}
		}
		else{
		  	$output= $output . '<option></option>';
		}

		$output=$output . '</select></p>
		<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Jefe de Departamento:&nbsp;&nbsp;&nbsp;&nbsp;' . $cadena2 . '<input type="hidden" name="oculto" value="Profesinales">
		<input type="hidden" name="idDocente" value="' . $row[0] . '">';		
	}
	$output=$output . '</fieldset>
	</p><input type="submit" value="Grabar" name="Grabar"style="font-weight:bold; color:black"></form>';
	
	//$output='<br><br><font color="red"><b>Atenci&oacute;n</b></font><br><br><p>No ha introducido ning&uacute;n dato para actualizar el registro seleccionado:&nbsp;<b>' . $nombre . '</b></p>&nbsp;';
		//$output=$output . '<br><p align="center">Para volver a intentarlo&nbsp;<a href="http://localhost/drupal/oficina/departamentos/modificar_departamento">pulse aqu&iacute;</a></p>';
}elseif (isset($_POST["Grabar"])){
	if ($_POST["oculto"]=="Personales"){//1800
		$id=$_POST["idDocente"];$dni=$_POST["dniDocente"];$dir=$_POST["dirDocente"];$localidad=$_POST["localidadDocente"];$cp=$_POST["cpDocente"];$email=$_POST["emailDocente"];
		$apellidos=$_POST["apellidosDocente"];$nombre=$_POST["nombDocente"];$prov=$_POST["provDocente"];$telf=$_POST["telDocente"];$movil=$_POST["movilDocente"];
		$sql="UPDATE docentes SET DNI_D='$dni', NOMBRE='$nombre', APELLIDOS='$apellidos', MOVIL='$movil', DIRECCION='$dir', LOCALIDAD='$localidad', CODIGO_P='$cp', PROVINCIA='$prov', EMAIL='$email', TELF_FIJO='$telf' WHERE ID_DOCENTES='$id'";
		if(mysqli_query($conexion, $sql)){
			$output= $output . '<p><b>El docente seleccionado se ha actualizado satisfactoriamente.</b></p>
			<p>Los datos personales grabados son:</p>
			<p>Nombre:&nbsp<b>' . $_POST["nombDocente"] . '</b></p>
			<p>Apellidos:&nbsp<b>' . $_POST["apellidosDocente"] . '</b></p>
			<p>D.N.I.:&nbsp<b>' . $_POST["dniDocente"] . '</b></p>
			<p>Direcci&oacute;n:&nbsp<b>' . $_POST["dirDocente"] . '</b></p>
			<p>Localidad:&nbsp<b>' . $_POST["localidadDocente"] . '</b></p>
			<p>Provincia:&nbsp<b>' . $_POST["provDocente"] . '</b></p>
			<p>C&oacute;digo Postal:&nbsp<b>' . $_POST["cpDocente"] . '</b></p>
			<p>Tel&eacute;fono:&nbsp<b>' . $_POST["telDocente"] . '</b></p>
			<p>M&oacute;vil:&nbsp<b>' . $_POST["movilDocente"] . '</b></p>
			<p>Direcci&oacute;n de correo:&nbsp<b>' . $_POST["emailDocente"] . '</b></p>
			<br><br>
			<p align="center">Si desea modificar otro docente <a href="http://localhost/drupal/oficina/docentes/modificar_docente">pulse aqu&iacute;</a></p>'; 
		}
		else{
			$output='<p><b>Error al actualizar el registro de docente<b></p>';
			$output=$output . '<p>'. mysqli_error($conexion) . '</p>';
		}
	}
	else{
		$id=$_POST["idDocente"];$categoria=$_POST["categoriaDocente"];$ndpto=$_POST["dptoDocente"];$jefe=$_POST["jefeDptoDocente"];
		$sql="SELECT id_dpto FROM departamentos WHERE nombre='$ndpto'";
		$idDpto=mysqli_fetch_array(mysqli_query($conexion, $sql));
		$sql="SELECT dni_d FROM docentes WHERE id_docentes='$id'";
		$dni=mysqli_fetch_array(mysqli_query($conexion, $sql));
		$sql="UPDATE docentes SET  ID_DPTO='$idDpto[0]', TIPO_D='$categoria', JEFE_DPTO='$jefe' WHERE ID_DOCENTES='$id'";
		if(mysqli_query($conexion, $sql)){
			$output= $output . '<p><b>El docente seleccionado con D.N.I.&nbsp;' . $dni[0] . '&nbsp;se ha actualizado satisfactoriamente.</b></p>
			<p>Los datos profesionales grabados son:</p>
			<p>Categor&iacute;a:&nbsp<b>' . $_POST["categoriaDocente"] . '</b></p>
			<p>Departamento:&nbsp<b>' . $_POST["dptoDocente"] . '</b></p>
			<p>Jefe de Departamento:&nbsp;';
			if ($_POST["jefeDptoDocente"]){
			 	$output= $output . '<b>Si</b></p>';
			}
			else{
				$output= $output . '<b>No</b></p>';
			}
			$output= $output . '<br><br>
			<p align="center">Si desea modificar otro docente <a href="http://localhost/drupal/oficina/docentes/modificar_docente">pulse aqu&iacute;</a></p>'; 
		}
		else{
			$output='<p><b>Error al actualizar el registro de docente<b></p>';
			$output=$output . '<p>'. mysqli_error($conexion) . '</p>';
		}
	}
	
} 

mysqli_close($conexion);
return $output;

}	/** end modificar_docente **/



/****************
			******************* Estudiantes *********************
*****************/
function listar_estudiantes(){
$output="";
$tamano_pagina="2";

if(array_key_exists('pagina', $_GET)){
	$pagina=$_GET["pagina"];
}
else{
	$pagina=1;
}

$conexion=bdexterna();

$sql="SELECT * FROM estudiantes";
$result=mysqli_query($conexion, $sql);
$total_filas=mysqli_num_rows($result);
$total_paginas=ceil($total_filas / $tamano_pagina);

$sql="SELECT * FROM estudiantes LIMIT " . (($pagina-1) * $tamano_pagina) . "," . $tamano_pagina;
$result=mysqli_query($conexion, $sql);
$output='<p align="center"><b><font size="4">Listado de los Estudiantes del centro</font></b></p>';
$output=$output . '<table border="2"><tr>
<th><font size="2">Identificador</font></th>
<th><font size="2">DNI</font></th>
<th><font size="2">Nombre</font></th>
<th><font size="2">Apellidos</font></th></tr>';
if($total_filas > 0){
	while ($row=mysqli_fetch_assoc($result)){
		$output=$output . '<tr>
		<td><font color="blue" size="2">'. $row["ID_EST"] . '</font></td>
		<td><font color="blue" size="2">' . $row["DNI"] . '</font></td>
		<td><font color="blue" size="2">'. $row["NOMBRE"] . '</font></td>
		<td><font color="blue" size="2">'. $row["APELLIDOS"] . '</font></td></tr>';
	}
	$output=$output . '</table><br>';
}



if ($total_paginas > 1){
	for ($i=1;$i<=$total_paginas;$i++){
		if($pagina == $i){
			$output=$output . 'P&aacute;gina ' . $pagina . "&nbsp;&nbsp;";
		}
		else{
			$output=$output . '<a href="http://localhost/drupal/oficina/estudiantes/listar_estudiantes?pagina=' . $i . '">P&aacute;gina ' . $i . '</a>&nbsp;&nbsp;';
		}

	}
}

if (!$_POST){
	$output=$output . '<form id="formBuscarEst" action="" method="post" accept-charset="UTF-8" size="100%">
	<br><br><p>Indroducir identificador de estudiante:&nbsp;&nbsp;&nbsp;<input style="color:blue" type="text" name="buscarid" placeholder="Identificador" required></p>
	<p>Seleccionar datos:&nbsp;&nbsp;&nbsp;<select name="datos"><option selected>Estudiante</option><option>Padres</option></select></p>
	<input type="submit" value="Buscar Datos" style="font-weight:bold; color:black"></form>';
}
else{
	$id=$_POST["buscarid"];
	$sql="SELECT * FROM estudiantes WHERE id_est='$id'";
	$result=mysqli_query($conexion, $sql);
	$row=mysqli_fetch_assoc($result);
	
	if ($row["NOMBRE"]==""){ 
		$output='<p align="center"><b><font color="red">Error:&nbsp;</font></b>el identificador&nbsp;<b>' . $id . '</b>&nbsp;no es de la lista de estudiantes</p>';
	}
	else{
		if ($_POST["datos"]=="Estudiante"){
			$output= '<br><p align="center"><b>DATOS DE ESTUDIANTE CON IDENTIFICADOR ' . $id . '</b>.</p>';
			if ($result){
				$output=$output . '<p>Nombre:&nbsp;<b>' . $row["NOMBRE"] . '</b></p>
				<p>Apellidos:&nbsp;<b>' . $row["APELLIDOS"] . '</b></p>
				<p>Direcci&oacute;n:&nbsp;<b>' . $row["DIRECCION"] . '</b></p>
				<p>Localidad:&nbsp;<b>' . $row["LOCALIDAD"] . '</b></p>
				<p>Provincia:&nbsp;<b>' . $row["PROVINCIA"] . '</b></p>
				<p>C&oacute;digo Postal:&nbsp;<b>' . $row["CPOSTAL"] . '</b></p>
				<p>Tel&eacute;fono:&nbsp;<b>' . $row["SEXO"] . '</b></p>
				<p>Fecha de Nacimiento:&nbsp;<b>' . $row["FECHA_NACIMIENTO"] . '</b></p>';
				if($row["DNI"]==""){
					$output=$output . '<p>D.N.I.:&nbsp;<b>' . $row["DNI"] . '</b></p>';
				}
				$output= $output . '<br>
				<p align="center">Si desea volver al listado de estudiantes&nbsp;<a href="http://localhost/drupal/oficina/estudiantes/listar_estudiantes">pulse aqu&iacute;</a></p>'; 
			}
			else{
				$output=$output . '<p align="center"><b>Fallo del sistema al realizar la consulta, puede intentarlo m&aacute;s tarde</b></p>';
			}
		
		}
		else{
			$id_p=$row["ID_PADRES"];
			$output='<br><p align="center"><b>DATOS FAMILIARES DEL ESTUDIANTE ' . $row["NOMBRE"] . ' ' . $row["APELLIDOS"] .'</b>.</p>';
			$sql1="SELECT * FROM padres WHERE id_padres='$id_p'";
			$result1=mysqli_query($conexion, $sql1);
			$row1=mysqli_fetch_assoc($result1);
			if ($result1){
				$output=$output . '<p><u>DATOS DEL PADRE</u></p>
				<p>Nombre:&nbsp;<b>' . $row1["NOMB_PADRE"] . '</b>&emsp;&emsp;Apellidos:&nbsp;<b>' . $row1["APEL_PADRE"] . '</b></p>
				<p>D.N.I.:&nbsp;<b>' . $row1["DNI_P"] . '</b>&emsp;&emsp;Fecha nacimiento:&nbsp;<b>' . $row1["F_NAC_PADRE"] . '</b></p>
				<p>Profesi&oacute;n:&nbsp;<b>' . $row1["PROF_PADRE"] . '</b>&emsp;&emsp;M&oacute;vil:&nbsp;<b>' . $row1["MOVIL_PADRE"] . '</b></p>
				<p><u>DATOS DE LA MADRE</u></p>
				<p>Nombre:&nbsp;<b>' . $row1["NOMB_MADRE"] . '</b>&emsp;&emsp;Apellidos:&nbsp;<b>' . $row1["APEL_MADRE"] . '</b></p>
				<p>D.N.I.:&nbsp;<b>' . $row1["DNI_M"] . '</b>&emsp;&emsp;Fecha nacimiento:&nbsp;<b>' . $row1["F_NAC_MADRE"] . '</b></p>
				<p>Profesi&oacute;n:&nbsp;<b>' . $row1["PROF_MADRE"] . '</b>&emsp;&emsp;M&oacute;vil:&nbsp;<b>' . $row1["MOVIL_MADRE"] . '</b></p>';
				$output= $output . '<br>
				<p align="center">Si desea volver al listado de estudiantes&nbsp;<a href="http://localhost/drupal/oficina/estudiantes/listar_estudiantes">pulse aqu&iacute;</a></p>'; 
			}
			else{
				$output=$output . '<p align="center"><b>Fallo del sistema al realizar la consulta, puede intentarlo m&aacute;s tarde</b></p>';
			}
		

		}


	}
}

mysqli_close($conexion);

return $output;
}	/** end listar_estudiantes **/

function alta_estudiante() {
$output="";$padres=[];$est=[];
$conexion=bdexterna();

if (!$_POST){
$output='<form id="formAltaEstudiante" action="" method="post" accept-charset="UTF-8" size="100%">
	<p>
	<fieldset form="formAltaEstudiante">
	<legend align="left"><SPAN style="text-align:top">Introducir datos del nuevo estudiante</SPAN></legend>
        <br><br>
	<p>&emsp;&emsp;Nombre:&emsp;<input type="text" style="color:blue" name="nombEst" required autofocus>
	&emsp;&emsp;&emsp;&emsp;&ensp;Apellidos:&emsp;<input type="text" style="color:blue" name="apellidosEst" required></p>
	<p>&emsp;&emsp;Fecha Nacimiento:&emsp;<input type="date" style="color:blue" name="fechaNacEst" required>
	&emsp;&emsp;&emsp;&emsp;G&eacute;nero:&emsp;<input type="radio" name="sexoEst" value="Femenino">&emsp;Femenino&emsp;<input type="radio" name="sexoEst" value="Masculino">&emsp;Masculino</p>
	<p>&emsp;&emsp;DNI&emsp;<input type="text" style="color:blue" name="dniEst" maxlength="9">	
	&emsp;&emsp;&emsp;&emsp;&ensp;Direcci&oacute;n:&emsp;<input type="text" style="color:blue" name="dirEst"></p>
	<p>&emsp;&emsp;Localidad:&emsp;<input type="text" style="color:blue" name="localidadEst">
	&emsp;&emsp;&emsp;&emsp;&ensp;Provincia:&emsp;<input type="text" style="color:blue" name="provEst"></p>
	<p>&emsp;&emsp;C&oacute;digo Postal:&emsp;<input type="num" style="color:blue" name="cpEst" maxlength="5">		
	&emsp;&emsp;&emsp;&emsp;&ensp;Tel&eacute;fono fijo:&nbsp;&nbsp;&nbsp;&nbsp;<input type="tel" style="color:blue" name="telEst" maxlength="9"></p>	
	</fieldset>
	</p>
	<p>
	<fieldset form="formAltaEstudiante">
	<legend align="left"><SPAN style="text-align:top">Introducir datos del padre<SPAN></legend>
        <br><br>
	<p>&emsp;&emsp;Nombre:&emsp;<input type="text" style="color:blue" name="nombP" required>
	&emsp;&emsp;&emsp;&emsp;&ensp;Apellidos:&emsp;<input type="text" style="color:blue" name="apellidosP" required></p>
	<p>&emsp;&emsp;Fecha Nacimiento:&emsp;<input type="date" style="color:blue" name="fechaNacP" required>
	&emsp;&emsp;&emsp;&emsp;&ensp;DNI:&emsp;<input type="text" style="color:blue" name="dniP" maxlength="9" required></p>
	<p>&emsp;&emsp;Profesi&oacute;n:&emsp;<input type="text" style="color:blue" name="profP">			
	&emsp;&emsp;&emsp;&emsp;&ensp;M&oacute;vil:&emsp;<input type="tel" style="color:blue" name="movilP" maxlength="9"></p>			
	</fieldset>
	</p>
	<p>
	<fieldset form="formAltaEstudiante">
	<legend align="left"><SPAN style="text-align:top">Introducir datos de la madre<SPAN></legend>
        <br><br>
	<p>&emsp;&emsp;Nombre:&emsp;<input type="text" style="color:blue" name="nombM" required>
	&emsp;&emsp;&emsp;&emsp;&ensp;Apellidos:&emsp;<input type="text" style="color:blue" name="apellidosM" required></p>
	<p>&emsp;&emsp;Fecha Nacimiento:&emsp;<input type="date" style="color:blue" name="fechaNacM" required>
	&emsp;&emsp;&emsp;&emsp;&ensp;DNI:&emsp;<input type="text" style="color:blue" name="dniM" maxlength="9" required></p>
	<p>&emsp;&emsp;Profesi&oacute;n:&emsp;<input type="text" style="color:blue" name="profM">			
	&emsp;&emsp;&emsp;&emsp;&ensp;M&oacute;vil:&emsp;<input type="tel" style="color:blue" name="movilM" maxlength="9"></p>			
	</fieldset>
	</p>
	<p>&nbsp;<b>Observaciones:</b><textarea name="observaciones" style="color:blue" rows="4" cols="103"></textarea></p>  
	<p><input type="submit" value="Agregar" style="font-weight:bold; color:black">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" value="Limpiar" style="font-weight:bold; color:black"></p>  
	</p>
	</form>';
 }
elseif (($_POST['nombEst'] == "") && ($_POST['apellidosEst'] == "") && ($_POST['fechaNacEst'] == "") &($_POST['dniP'] == "") && 
	($_POST['nombP'] == "") && ($_POST['apellidosP'] == "") && ($_POST['fechaNacP'] == "") && ($_POST['dniM'] == "") && 
	($_POST['nombM'] == "") &&($_POST['apellidosM'] == "") && ($_POST['fechaNacM'] == "")){
		$output='<br><font color="red"><b>Atenci&oacute;n</b></font><br><br><p>No puede dar de alta un Estudiante sin introducir los datos requeridos:</p>
			<p>Estudiante (NOMBRE, APELLIDOS, FECHA NACIMIENTO)</p>
			<p>Padre y Madre (DNI, NOMBRE, APELLIDOS, FECHA NACIMIENTO)</p>
			<p align="center">Para volver hacia atr&aacute;s&nbsp;<a href="http://localhost/drupal/oficina/estudiantes/alta_estudiante">pulse aqu&iacute;</a></p>'; 

} 
else{
	$padres[0]=$_POST["nombP"];$padres[1]=$_POST["apellidosP"];$padres[2]=$_POST["fechaNacP"];$padres[3]=$_POST["dniP"];
	$padres[4]=$_POST["profP"];$padres[5]=$_POST["movilP"];$padres[6]=$_POST["nombM"];$padres[7]=$_POST["apellidosM"];
	$padres[8]=$_POST["fechaNacM"];$padres[9]=$_POST["dniM"];$padres[10]=$_POST["profM"];$padres[11]=$_POST["movilM"];
	$padres[12]=$_POST["observaciones"];

	preg_match("/([0-9]{1,2})\/([0-9]{1,2})\/([0-9]{4})/", $padres[2], $nfecha);
	$fechaP=$nfecha[3] . "-" . $nfecha[2] . "-" . $nfecha[1];
	preg_match("/([0-9]{1,2})\/([0-9]{1,2})\/([0-9]{4})/", $padres[8], $nfecha);
	$fechaM=$nfecha[3] . "-" . $nfecha[2] . "-" . $nfecha[1];

	$sql="INSERT INTO padres (ID_PADRES, NOMB_PADRE, APEL_PADRE, F_NAC_PADRE, DNI_P, PROF_PADRE, MOVIL_PADRE, NOMB_MADRE, APEL_MADRE, F_NAC_MADRE, DNI_M, PROF_MADRE, MOVIL_MADRE,  OBSERVACIONES) 
	VALUES (NULL, '$padres[0]', '$padres[1]', '$fechaP', '$padres[3]', '$padres[4]', '$padres[5]', '$padres[6]', '$padres[7]', '$fechaM', '$padres[9]', '$padres[10]', '$padres[11]', '$padres[12]')";
	if(mysqli_query($conexion, $sql)){
		$id_padres=mysqli_insert_id($conexion);
		$output= $output . '<p><b>Padres registrados satisfactoriamente</b>.</p><p>Identificador de nuevo registro:&nbsp<b>' . $id_padres . '</b></p> 
		<p><b>Datos del padre:</b></p>';
		for ($i=0;$i<6;$i++){
			if($padres[$i]<>""){
				$output= $output . '<p>&nbsp;&nbsp;&nbsp;&nbsp;' . $padres[$i] . '</p>';	
			}
		}
		$output= $output . '<p><b>Datos de la madre:</b></p>';
		for ($i=6;$i<12;$i++){
			if($padres[$i]<>""){
				$output= $output . '<p>&nbsp;&nbsp;&nbsp;&nbsp;' . $padres[$i] . '</p>';	
			}
		}
		if ($_POST["observaciones"]<>""){
			$output= $output . '<p>Observaciones:&nbsp;&nbsp;' . $padres[12] . '</p>';
		}
	}
	$est[0]=$_POST["nombEst"];$est[1]=$_POST["apellidosEst"];$est[2]=$_POST["dirEst"];$est[3]=$_POST["localidadEst"];$est[4]=$_POST["provEst"];
	$est[5]=$_POST["cpEst"];$est[6]=$_POST["telEst"];$est[7]=$_POST["sexoEst"];$est[8]=$_POST["fechaNacEst"];$est[9]=$_POST["dniEst"];

	preg_match("/([0-9]{1,2})\/([0-9]{1,2})\/([0-9]{4})/", $est[8], $nfecha);
	$fecha=$nfecha[3] . "-" . $nfecha[2] . "-" . $nfecha[1];

	$sql1="INSERT INTO estudiantes (ID_EST, ID_PADRES, NOMBRE, APELLIDOS, DIRECCION, LOCALIDAD, PROVINCIA, CPOSTAL, TELF, SEXO, FECHA_NACIMIENTO, DNI) 
	VALUES (NULL, '$id_padres', '$est[0]', '$est[1]', '$est[2]', '$est[3]', '$est[4]', '$est[5]', '$est[6]', '$est[7]', '$fecha', '$est[9]')";
	if(mysqli_query($conexion, $sql1)){
		$id_est=mysqli_insert_id($conexion);
		$output= $output . '<p><b>Estudiante registrado satisfactoriamente</b>.</p><p>Identificador de nuevo registro:&nbsp<b>' . $id_est . '</b></p> 
		<p><b>Datos del estudiante:&nbsp;</b></p>';
		for ($i=0;$i<10;$i++){
			if($est[$i]<>""){
				$output= $output . '<p>&nbsp;&nbsp;&nbsp;&nbsp;' . $est[$i] . '</p>';	
			}
		}
		$output= $output . '<br>
		<p align="center">Si desea agregar otro estudiante <a href="http://localhost/drupal/oficina/estudiantes/alta_estudiante">pulse aqu&iacute;</a></p>'; 
	}	
}

mysqli_close($conexion);

return $output;
}	/** end alta_estudiante  **/


function baja_estudiante() {
$output="";
$conexion=bdexterna();

if (!$_POST){
	$output='<form id="formBajaEst" action="" method="post" accept-charset="UTF-8" size="100%">
	<p>
	<fieldset form="formBajaEst">
	<legend align="left"><SPAN style="text-align:top">Eliminar un estudiante</SPAN></legend>
        <br><br>
	<p>&emsp;&emsp;&nbsp;Seleccionar Nombre completo del Estudiante:&emsp;&emsp;&emsp;<p align="center">
	<select required name="Estudiante" size="6">';
	$sql="SELECT * FROM estudiantes";
	$result=mysqli_query($conexion, $sql);
	if (mysqli_num_rows($result) > 0){
		while($row=mysqli_fetch_assoc($result)){
			$output= $output . '<option>' . $row["APELLIDOS"] . ', ' . $row["NOMBRE"] . '</option>';
		}
	}
	else{
		  $output= $output . '<option></option>';
	}

	$output=$output . '</select></p></p>
	<p>&emsp;&emsp;&nbsp;Datos a eliminar del estudiante:&emsp;&emsp;&emsp;<p align="center">
	<select required name="datos" size="2"><option selected value="Parciales">Parciales:solo datos del estudiante</option>
	<option value="Totales">Totales:datos del estudiante y familiares</option></select></p>
	</fieldset>
	<p><input type="submit" value="Eliminar" name="Eliminar" style="font-weight:bold; color:black">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" value="Limpiar" style="font-weight:bold; color:black">  
	</p>
	</form>';
} 
elseif(isset($_POST["Eliminar"])){
	$est=$_POST["Estudiante"];
	if($_POST["datos"]=="Totales"){
		$datos=$_POST["datos"] . ": Datos de estudiante y familiares";
	}else{
		$datos=$_POST["datos"] . ": Datos de estudiante";
	}
	
	$output='<form id="formConfirmar" action="" method="post" accept-charset="UTF-8">
	<p>
	<fieldset form="formConfirma">
	<legend align="left"><SPAN style="text-align:top">Confirmar Baja</SPAN></legend>
        <br><br><p align="center"> Seguro que desea dar de baja al estudiante<b>&nbsp;' . $est . '</b></p>
	<p align="center">A eliminar con los siguiente datos<b>&nbsp;' . $datos . '</b></p>
	<p align="center"><input type="submit" value="Aceptar" name="Aceptar" style="font-weight:bold; color:black">&emsp;
	<input type="submit" name="Cancelar" value="Cancelar" style="font-weight:bold; color:black">
	<input type="hidden" name="est" value="' . $est . '"><input type="hidden" name="datos" value="' . $_POST["datos"] . '">
	</p></fieldset></p></form>';
}else{
	$est=$_POST["est"];
	$datos=$_POST["datos"];
	if(isset($_POST["Aceptar"])){
		$nombre=substr($est, (strpos($est, ",")+1));
		$long=strlen($nombre);
		$nombre=ltrim($nombre);
		$apellidos=substr($est, 0, -($long+1));
		$apellidos=ltrim($apellidos);

		$sql="SELECT * FROM estudiantes WHERE apellidos='$apellidos' AND nombre='$nombre'";
		$result=mysqli_query($conexion, $sql);
		$regEst=mysqli_fetch_array($result);
		
		if($datos=="Parciales"){
			$sql1="SELECT id_padres FROM estudiantes WHERE id_padres='$regEst[1]'";
			$result1=mysqli_query($conexion, $sql1);
			$total_filas=mysqli_num_rows($result1);
			if($total_filas==1){
				$output='<br><p align="center"><font color="red"><b>Atenci&oacute;n:</b>&nbsp;El estudiante seleccionado no tiene hermanos/as en este centro.</font></p>
				<p align="center">Debe seleccionar la opci&oacute;n de elimniar estudiante con datos <b>TOTALES</b></p>
				<p align="center"> Para volver atr&aacute;s&nbsp;<a href="http://localhost/drupal/oficina/estudiantes/baja_estudiante">pulse aqu&iacute;</a></p>';
			}
			else{
				$sql2="DELETE FROM estudiantes WHERE ID_EST='$regEst[0]'";
				if(mysqli_query($conexion, $sql2)){//2114
					$output='<p><b>El estudiante seleccionado se ha borrado satisfactoriamente</b>.</p>
					<p>Identificador del registro: <b>' . $regEst[0] . '</b></p> 
					<p>Nombre:<b>' . $regEst[2] . '</b></p>
					<p>Apellidos del docente:<b>' . $regEst[3] . '</b></p><br><br>
					<p align="center">Si desea eliminar otro estudiante&nbsp;<a href="http://localhost/drupal/oficina/estudiantes/baja_estudiante">pulse aqu&iacute;</a></p>';		
				}
				else{
					$output='<p><b>Error al eliminar el registro con el nombre:&nbsp;' . $regEst[2] . '<b>&nbsp;y apellido:&nbsp;<b>' . $regEst[3] . '</b></p>';
					$output=$output . '<p>'. mysqli_error($conexion) . '</p>';
				}
			}
		}
		if($datos=="Totales"){
			$sql1="SELECT id_padres FROM estudiantes WHERE id_padres='$regEst[1]'";
			$result1=mysqli_query($conexion, $sql1);
			$total_filas=mysqli_num_rows($result1);

			if($total_filas > 1){
				$output='<br><p align="cener"><font color="red"><b>Atenci&oacute;n:</b>&nbsp;El estudiante seleccionado tiene hermanos/as en este centro.</font></p>
				<p align="center">Debe seleccionar la opci&oacute;n de elimniar con datos PARCIALES</p>
				<p align="center"> Para volver atr&aacute;s&nbsp;<a href="http://localhost/drupal/oficina/estudiantes/baja_estudiante">pulse aqu&iacute;</a></p>';
			}
			else{
				//$output='<p>'. $regEst[1] . ' y ' . $regEst[0];
				$sql2="DELETE FROM estudiantes WHERE ID_EST='$regEst[0]'"; $result2=mysqli_query($conexion, $sql2);
				$sql1="DELETE FROM padres WHERE ID_PADRES='$regEst[1]'"; $result1=mysqli_query($conexion, $sql1);
				if(($result1)&&($result2)){
					$output=$output . '<p><b>El estudiante seleccionado se ha eliminado satisfactoriamente con los datos familiares</b></p>
					<p>Identificador del registro: <b>' . $regEst[0] . '</b></p> 
					<p>Identificador familiar:<b>' . $regEst[1] . '</b></p>
					<p>Nombre:<b>' . $regEst[2] . '</b></p>
					<p>Apellidos del docente:<b>' . $regEst[3] . '</b></p><br><br>
					<p align="center">Si desea eliminar otro estudiante&nbsp;<a href="http://localhost/drupal/oficina/estudiantes/baja_estudiante">pulse aqu&iacute;</a></p>';
				}
				else{
					$output= $output . '<p><b>Error al eliminar el registro con el nombre:&nbsp;' . $regEst[2] . '<b>&nbsp;y apellido:&nbsp;<b>' . $regEst[3] . '</b></p>';//2148
					$output=$output . '<p>'. mysqli_error($conexion) . '</p>';
				}
			}	
		}
	}else{
		$output='<br><br><p align="center"><b>Operaci&oacute;n de eliminar estudiante&nbsp;<font color="red">' . $est . '</font>&nbsp;cancelada</b></font>
		<br>
		<p align="center">Si desea volver al apartado "Baja Estudiante"&nbsp;<a href="http://localhost/drupal/oficina/estudiantes/baja_estudiante">pulse aqu&iacute;</a></p>'; 
	}

}

mysqli_close($conexion);
return $output;
}	/** end baja_estudiante  **/


function modificar_estudiante() {
$output="";


return $output;
}	/** end modificar_estudiante  **/



/**********
		************************** Materias *************************
***********/

function listar_materias(){
$output="";
$tamano_pagina="5";

if(array_key_exists('pagina', $_GET)){
	$pagina=$_GET["pagina"];
}
else{
	$pagina=1;
}

$conexion=bdexterna();

$sql="SELECT * FROM materias";
$result=mysqli_query($conexion, $sql);
$total_filas=mysqli_num_rows($result);
$total_paginas=ceil($total_filas / $tamano_pagina);

$sql="SELECT * FROM materias LIMIT " . (($pagina-1) * $tamano_pagina) . "," . $tamano_pagina;
$result=mysqli_query($conexion, $sql);
$output='<p align="center"><b><font size="4">Listado de las Materias que se imparten en el centro</font></b></p>';
$output=$output . '<table border="2"><tr><th><font size="2">Identificador</font></th><th><font size="3">Nombre Materia</font></th></tr>';
if($total_filas > 0){
	while ($row=mysqli_fetch_assoc($result)){
		$output=$output . '<tr><td><font color="blue" size="2">'. $row["ID_MATERIA"] . '</font></td><td><font color="blue" size="2">' . $row["NOMBRE"] . '</font></td></tr>';
	}
	$output=$output . '</table><br>';
}

mysqli_close($conexion);

if ($total_paginas > 1){
	for ($i=1;$i<=$total_paginas;$i++){
		if($pagina == $i){
			$output=$output . 'P&aacute;gina ' . $pagina . "&nbsp;&nbsp;";
		}
		else{
			$output=$output . '<a href="http://localhost/drupal/oficina/materias/listar_materias?pagina=' . $i . '">P&aacute;gina ' . $i . '</a>&nbsp;&nbsp;';
		}

	}
}

return $output;

}   /** end listar_materias **/


function alta_materia() {
$output="";

$conexion=bdexterna();

if (!$_POST){
	$output='<form id="formAltaMateria" action="" method="post" accept-charset="UTF-8">
	<p>
	<fieldset form="formAltaMateria">
	<legend align="left"><SPAN style="text-align:top">Introducir una materia nueva</SPAN></legend>
        <br><br>
	<p><SPAN style="text-align:center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nombre:&nbsp;<input type="text" name="nombMateria" required autofocus></SPAN></p>
	<p><SPAN style="text-align:top">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Seleccionar un Departamento:</p><p align="center"><select name="nombDpto" size="6" required>';
	
	$sql="SELECT nombre FROM departamentos";
	$result=mysqli_query($conexion, $sql);
	if (mysqli_num_rows($result) > 0){
		while($row=mysqli_fetch_assoc($result)){
			$output= $output . '<option>' . $row["nombre"] . '</option>';
		}
	}
	else{
		  $output= $output . '<option></option>';
	}

	 $output= $output . '</select></p>
	</fieldset>
	</p>
	<p><input type="submit" value="Agregar" style="font-weight:bold; color:black">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" value="Limpiar" style="font-weight:bold; color:black">  
	</p>
	</form>';
}elseif ($_POST["nombMateria"] == ""){
		$output='<br><b>Atenci&oacute;n</b><br><br><p>No puede dar de alta una Materia sin nombre</p><p>Para volver hacia atr&aacute;s&nbsp;<a href="http://localhost/drupal/oficina/materias/alta_materia">pulse aqu&iacute;</a></p>'; 
}
else{
	$nombre=$_POST["nombMateria"];
	$nom_dpto=$_POST["nombDpto"];
	
	$sql="SELECT ID_DPTO FROM departamentos WHERE NOMBRE='$nom_dpto'";	
	$result=mysqli_query($conexion, $sql);
	$id_dpto=mysqli_fetch_array($result);
	$sql="INSERT INTO materias (ID_MATERIA, ID_DPTO, NOMBRE) VALUES (NULL, '$id_dpto[0]', '$nombre')";
		
	if(mysqli_query($conexion, $sql)){
		$ant_id=mysqli_insert_id($conexion);
		$output= '<p><b>Nueva materia registrada satisfactoriamente</b>.</p><p>Identificador de nuevo registro:&nbsp;<b>' . $ant_id . '</b></p> 
		<p>Nombre del nuevo registro:&nbsp;<b>' . $nombre . '</b></p>
		<p>Identificador de departamento&nbsp;<b>' . $id_dpto[0] . '</b></p>
		<p>Nombre del departamento:&nbsp;<b>' . $nom_dpto . '</b></p><br><br>
		<p align="center">Si desea agregar otra materia&nbsp;<a href="http://localhost/drupal/oficina/materias/alta_materia">pulse aqu&iacute;</a></p>'; 
	}
	
	
}
	
mysqli_close($conexion);	
return $output;

}   /** end alta_materia **/

function baja_materia() {
$output="";
$conexion=bdexterna();	

if (!$_POST){
	$output='<form id="formBajaMateria" action="" method="post" accept-charset="UTF-8" size="100%">
	<p>
	<fieldset form="formBajaMateria">
	<legend align="left"><SPAN style="text-align:top">Eliminar una materia</SPAN></legend>
        <br><br>
	<p><SPAN style="text-align:top">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Seleccionar una Materia:&nbsp;<p align="center"><select name="nombMateria" size="8">';
	
	$sql="SELECT nombre FROM materias";
	$result=mysqli_query($conexion, $sql);
	if (mysqli_num_rows($result) > 0){
		while($row=mysqli_fetch_assoc($result)){
			$output= $output . '<option>' . $row["nombre"] . '</option>';
		}
	}
	else{
		  $output= $output . '<option></option>';
	}
	$output= $output . '</p></select></fieldset>
	</p>
	<p><input type="submit" value="Eliminar" style="font-weight:bold; color:black">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" value="Limpiar" style="font-weight:bold; color:black">  
	</p>
	</form>';
} 
else{
	$nombre=$_POST["nombMateria"];
	mysqli_select_db($conexion, "colegio");
	$sql="SELECT ID_MATERIA FROM departamentos WHERE NOMBRE='$nombre'";
	$result=mysqli_query($conexion, $sql);
	$id=mysqli_fetch_array($result);
	//$sql="DELETE FROM materias WHERE NOMBRE='$nombre'";
	if(mysqli_query($conexion, $sql)){
	//if($result){	
		$output= '<p><b>La materia seleccionada se ha borrado satisfactoriamente</b>.</p>
		<p>Identificador del registro: <b>' .$id[0] . '</b></p> 
		<p>Nombre del registro: <b>' . $nombre . '</b></p><br><br>';
		$output=$output . '<p align="center">Si desea eliminar otra materia&nbsp;<a href="http://localhost/drupal/oficina/materias/baja_materia">pulse aqu&iacute;</a></p>';		
	}
	else{
		$output='<p><b>Error al eliminar el registro con el nombre:&nbsp;' . $nombre . '<b></p>';
		$output=$output . '<p>'. mysqli_error($conexion) . '</p>';
	}
}
mysqli_close($conexion);
return $output;

}   /** end baja_materia **/


function modificar_materia() {
$output="";

$conexion=bdexterna();

if (!$_POST){
	$output='<form id="formModMateria" action="" method="post" accept-charset="UTF-8" size="100%">
	<p>
	<fieldset form="formModMateria">
	<legend align="left"><SPAN style="text-align:top">Cambiar nombre de una materia</SPAN></legend>
        <br><br>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Seleccionar una Materia:&nbsp;<p align="center"><select name="nombMateria" size="5" required>';
	
	$sql="SELECT nombre FROM materias";
	$result=mysqli_query($conexion, $sql);
	if (mysqli_num_rows($result) > 0){
		while($row=mysqli_fetch_assoc($result)){
			$output= $output . '<option>' . $row["nombre"] . '</option>';
			//$id=$row["id_dpto"];
		}
	}
	else{
		  $output= $output . '<option></option>';
	}
	$output= $output . '</p></select></p>
	<br><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Indicar el nuevo nombre de materia:&nbsp; <input type="text" style="color:blue" name="nuevo" required></p>
	</fieldset>
	</p>
	<p><input type="submit" value="Grabar" style="font-weight:bold; color:black">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" value="Limpiar" style="font-weight:bold; color:black">  
	</p>
	</form>';
} 
else{
	$nombre=$_POST["nombMateria"];
	$nombnuevo=$_POST["nuevo"];
	mysqli_select_db($conexion, "colegio");
	$sql="SELECT ID_MATERIA FROM materias WHERE NOMBRE='$nombre'";
	$result=mysqli_query($conexion, $sql);
	$id=mysqli_fetch_array($result);
	//$num=$id[0];
	if ($nombnuevo == ""){
		$output='<br><br><font color="red"><b>Atenci&oacute;n</b></font><br><br><p>No ha introducido ning&uacute;n dato para actualizar el registro seleccionado:&nbsp;<b>' . $nombre . '</b></p>&nbsp;';
		$output=$output . '<br><p align="center">Para volver a intentarlo&nbsp;<a href="http://localhost/drupal/oficina/materias/modificar_materia">pulse aqu&iacute;</a></p>';
	} 
	else{
		$sql="UPDATE materias SET NOMBRE='$nombnuevo' WHERE ID_MATERIA= '$id[0]'";
		if(mysqli_query($conexion, $sql)){
			$output= '<p><b>La materia seleccionada se ha actualizado satisfactoriamente.</b></p> 
			<p>Nombre anterior del registro: <b>' . $_POST["nombMateria"] . '</b></p><p>Se ha actualizado por el nombre: <b>' . $_POST["nuevo"] . '</b></p>
			<p>Identificador de registro: <b>' . $id[0] . '</b></p><br>';
			$output=$output . '<p align="center">Si desea modificar otra materia&nbsp;<a href="http://localhost/drupal/oficina/materias/modificar_materia">pulse aqu&iacute;</a></p>'; 
		}
		else{
			$output='<p><b>Error al actualizar el registro con el nombre:&nbsp;' . $nombre . '<b></p>';
			$output=$output . '<p>'. mysqli_error($conexion) . '</p>';
		}
	}
} 
mysqli_close($conexion);
return $output;

}  /** end modificar_materia **/


function expedientes_academicos() {
 return ('expedientes acad&eacute;micos ññññ');
 }

function oficina_matriculas() {

$acento=utf8_encode('Matrículas ñ');
 return $acento;
}