
<?php


/**
 * Implementation hook_menu().
 */
 function oficina_menu() {
 $items=array();

 $items['oficina/cursos_oficiales'] = array(	/************** Cursos Académicos **************/
 'title' => 'CURSOS OFICIALES',
 'page callback' => 'agregare',
 'page arguments' => array('Unidades'),
 'access callback' => TRUE,
 'type' => MENU_NORMAL_ITEM,
 'weight' => -1,
 );
 $items['oficina/cursos_oficiales/unidades'] = array(
 'title' => 'Unidades',
 'access arguments' => array('Unidades'),
 'type' => MENU_DEFAULT_LOCAL_TASK,
 'weight' => 0,
 );
 $items['oficina/cursos_oficiales/cursos'] = array(
 'title' => 'Cursos',
 'access arguments' => array('Cursos'),
 'page callback' => 'listar_cursos',
 'type' => MENU_LOCAL_TASK,
 'weight' => 1,
 ); 
$items['oficina/cursos_oficiales/ciclos'] = array(
 'title' => 'Ciclos',
 'access arguments' => array('Ciclos'),
 'page callback' => 'listar_ciclos',
 'type' => MENU_LOCAL_TASK,
 'weight' => 2,
 );

$items['oficina/cursos_oficiales/cursos/listar_cursos'] = array(
 'title' => 'Listar Cursos',
 'access arguments' => array('Cursos'),
 'page callback' => 'listar_cursos',
 'page arguments' => array(2),
 'type' => MENU_LOCAL_TASK,
 'weight'=> 0,
 ); 
$items['oficina/cursos_oficiales/cursos/alta_curso'] = array(
 'title' => 'Alta Curso',
 'access arguments' => array('Cursos'),
 'page callback' => 'alta_curso',//50
 'page arguments' => array(2), 
 'type' => MENU_LOCAL_TASK,
 'weight'=> 2,	
 );
 $items['oficina/cursos_oficiales/cursos/baja_curso'] = array(
 'title' => 'Baja Curso',
 'access arguments' => array('Cursos'),
 'page callback' => 'baja_curso',
 'page arguments' => array(2), 
 'type' => MENU_LOCAL_TASK,
 'weight'=> 3,
 );
$items['oficina/cursos_oficiales/cursos/modificar_curso'] = array(
 'title' => 'Modificar Curso',
 'access arguments' => array('Cursos'),
 'page callback' => 'modificar_curso',
 'page arguments' => array(2),
 'type' => MENU_LOCAL_TASK,
 'weight'=> 1,
 );
			/******** Ciclos ********/

$items['oficina/cursos_oficiales/ciclos/listar_ciclos'] = array(
 'title' => 'Listar Ciclos',
 'access arguments' => array('Ciclos'),
 'page callback' => 'listar_ciclos',
 'page arguments' => array(2),
 'type' => MENU_LOCAL_TASK,
 'weight'=> 0,
 ); 
$items['oficina/cursos_oficiales/ciclos/alta_ciclo'] = array(
 'title' => 'Alta Ciclo',
 'access arguments' => array('ciclos'),
 'page callback' => 'alta_ciclo',
 'page arguments' => array(2), 
 'type' => MENU_LOCAL_TASK,
 'weight'=> 2,
 );
 $items['oficina/cursos_oficiales/ciclos/baja_ciclo'] = array(
 'title' => 'Baja Ciclo',
 'access arguments' => array('Ciclos'),
 'page callback' => 'baja_ciclo',
 'page arguments' => array(2), 
 'type' => MENU_LOCAL_TASK,
 'weight'=> 3,
 );
$items['oficina/cursos_oficiales/ciclos/modificar_ciclo'] = array(
 'title' => 'Modificar Ciclo',
 'access arguments' => array('Ciclos'),
 'page callback' => 'modificar_ciclo',//100
 'page arguments' => array(2),
 'type' => MENU_LOCAL_TASK,
 'weight'=> 1,
 );

$items['oficina/cursos_oficiales/unidades/listar_unidades'] = array(
 'title' => 'Listar Unidades',
 'access arguments' => array('Unidades'),
 'page callback' => 'listar_unidades',
 'page arguments' => array(2),
 'type' => MENU_LOCAL_TASK,
 'weight'=> 0,
 ); 
$items['oficina/cursos_oficiales/unidades/alta_unidad'] = array(
 'title' => 'Alta Unidad',
 'access arguments' => array('Unidades'),
 'page callback' => 'alta_unidad',
 'page arguments' => array(2), 
 'type' => MENU_LOCAL_TASK,
 'weight'=> 2,
 );
 $items['oficina/cursos_oficiales/unidades/baja_unidad'] = array(
 'title' => 'Baja Unidad',
 'access arguments' => array('Unidades'),
 'page callback' => 'baja_unidad',
 'page arguments' => array(2), 
 'type' => MENU_LOCAL_TASK,
 'weight'=> 3,
 );
$items['oficina/cursos_oficiales/unidades/modificar_unidad'] = array(
 'title' => 'Modificar Unidad',
 'access arguments' => array('Unidades'),
 'page callback' => 'modificar_unidad',
 'page arguments' => array(2), 
 'type' => MENU_LOCAL_TASK,
 'weight'=> 1,
 );

$items['oficina/departamentos']=array(		/*************** Departamentos *****************/
	'title' => 'DEPARTAMENTOS',
	'access arguments'=> array('Listar Departamentos'),
	'page callback' => 'listar_departamentos',
	'access callback'=> TRUE,
	'type'=> MENU_NORMAL_ITEM,
	'weight'=> -1,
	);

$items['oficina/departamentos/listar_departamentos']=array(
	'title' => 'Listar Departamentos',
	'access arguments'=> array('Listar Departamentos'),//150
	'type'=> MENU_DEFAULT_LOCAL_TASK,
	'weight'=> 0,
	);
$items['oficina/departamentos/alta_departamento'] = array(
 	'title' => 'Alta Departamento',
 	'access arguments' => array('Alta Departamento'),
 	'page callback' => 'alta_departamento',
 	'type' => MENU_LOCAL_TASK,
	'weight'=> 1,
 	); 
$items['oficina/departamentos/baja_departamento']=array(
	'title' => 'Baja Departamento',
	'access arguments'=> array('Baja Departamento'),
	'access callback'=> TRUE,
	'page callback' => 'baja_departamento',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 2,
	);
$items['oficina/departamentos/modificar_departamento']=array(
	'title' => 'Modificar Departamento',
	'access arguments'=> array('Modificar Departamento'),
	'access callback'=> TRUE,
	'page callback' => 'modificar_departamento',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 3,
	);

$items['oficina/docentes']=array(	//Docentes
	'title' => 'DOCENTES',
	'access arguments'=> array('Listar Docentes'),
	'page callback' => 'listar_docentes',
	'access callback'=> TRUE,
	'type'=> MENU_NORMAL_ITEM,
	'weight'=> -1,
	);
$items['oficina/docentes/listar_docentes']=array(
	'title' => 'Listar Docentes',
	'access arguments'=> array('Listar Docentes'),
	'type'=> MENU_DEFAULT_LOCAL_TASK,
	'weight'=> 0,
	);
$items['oficina/docentes/alta_docente']=array(
	'title' => 'Alta Docente',
	'access arguments'=> array('Alta Docente'),
	'access callback'=> TRUE,
	'page callback' => 'alta_docente',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 1,
	);//200
$items['oficina/docentes/baja_docente']=array(
	'title' => 'Baja Docente',
	'access arguments'=> array('Baja Docente'),
	'access callback'=> TRUE,
	'page callback' => 'baja_docente',
	'type'=> MENU_LOCAL_TASK,
 	'weight'=> 2,
	);
$items['oficina/docentes/modificar_docente']=array(
	'title' => 'Modificar Docente',
	'access arguments'=> array('Modificar Docente'),
	'access callback'=> TRUE,
	'page callback' => 'modificar_docente',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 3,
	);	

$items['oficina/estudiantes']=array(		/****************** Estudiantes ******************/
	'title' => 'ESTUDIANTES',
	'access arguments'=> array('Listar estudiantes'),
	'page callback' => 'alta_estudiante',
	'access callback'=> TRUE,
	'type'=> MENU_NORMAL_ITEM,
	'weight'=> -1,
	);
$items['oficina/estudiantes/listar_estudiantes']=array(
	'title' => 'Listar Estudiantes',
	'access arguments'=> array('Listar estudiantes'),
	'type'=> MENU_DEFAULT_LOCAL_TASK,
	'weight'=> 0,
	);
$items['oficina/estudiantes/alta_estudiante']=array(
	'title' => 'Alta Estudiante',
	'access arguments'=> array('Alta Estudiante'),
	'access callback'=> TRUE,
	'page callback' => 'alta_estudiante',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 1,
	);
$items['oficina/estudiantes/baja_estudiante']=array(
	'title' => 'Baja Estudiante',
	'access arguments'=> array('Baja Estudiante'),
	'access callback'=> TRUE,
	'page callback' => 'baja_estudiante',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 2,
	);
$items['oficina/estudiantes/modificar_estudiante']=array(
	'title' => 'Modificar Estudiante',
	'access arguments'=> array('Modificar Estudiante'),//250
	'access callback'=> TRUE,
	'page callback' => 'modificar_estudiante',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 3,
	);	

$items['oficina/historial_de_expedientes']=array(	/***************** Expedientes  *************/
	'title' => 'HISTORIAL DE EXPEDIENTES',
	'access arguments' => array('Historial de Expedientes'),
	'page callback' => 'expedientes_academicos',
	'access callback'=> TRUE,
	'type' => MENU_NORMAL_ITEM,
	'weight'=> -1,
	);

$items['oficina/materias']=array(	/**************** Materias *****************/
	'title' => 'MATERIAS',
	'access arguments'=> array('Listar Materias'),
	'page callback' => 'listar_materias',
	'access callback'=> TRUE,
	'type'=> MENU_NORMAL_ITEM,
	'weight'=> -1,
	);	
$items['oficina/materias/listar_materias']=array(
	'title' => 'Listar Materias',
	'access arguments'=> array('Listar Materias'),
	'type'=> MENU_DEFAULT_LOCAL_TASK,
	'weight'=> 0,
	);
$items['oficina/materias/alta_materia']=array(
	'title' => 'Alta Materia',
	'access arguments'=> array('Alta Materia'),
	'access callback'=> TRUE,
	'page callback' => 'alta_materia',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 1,
	);
$items['oficina/materias/baja_materia']=array(
	'title' => 'Baja Materia',
	'access arguments'=> array('Baja Materia'),
	'access callback'=> TRUE,
	'page callback' => 'baja_materia',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 2,
	);
$items['oficina/materias/modificar_materia']=array(
	'title' => 'Modificar Materia',
	'access arguments'=> array('Modificar Materia'),
	'access callback'=> TRUE,
	'page callback' => 'modificar_materia',//300
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 3,
	);
$items['oficina/registro_de_estudiantes']=array(	/************** Registro (matrículas) *************/
	'title' => 'REGISTRO DE ESTUDIANTES',
	'access arguments'=> array('Registro de Cursos'),
	'page callback' => 'alta_materia',
	'access callback'=> TRUE,
	'type'=> MENU_NORMAL_ITEM,
	'weight'=> -1,
	);	
$items['oficina/registro_de_estudiantes/alta_registro']=array(
	'title' => 'Alta Registro',
	'access arguments'=> array('Alta Registro'),
	'type'=> MENU_DEFAULT_LOCAL_TASK,
	'weight'=> 0,
	);
$items['oficina/registro_de_estudiantes/baja_registro']=array(
	'title' => 'Baja Registro',
	'access arguments'=> array('Baja Registro'),
	'access callback'=> TRUE,
	'page callback' => 'baja_materia',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 1,
	);
$items['oficina/registro_de_estudiantes/modificar_registro']=array(
	'title' => 'Modificar Registro',
	'access arguments'=> array('Modificar Registro'),
	'access callback'=> TRUE,
	'page callback' => 'modificar_materia',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 2,
	);
$items['oficina/registro_de_estudiantes/Listar_registros']=array(
	'title' => 'Listar Registros',
	'access arguments'=> array('Listar Registros'),
	'access callback'=> TRUE,
	'page callback' => 'modificar_materia',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 3,
	);
 return $items;
 }

/**
 * Page callback
**/
/*function menufun_greeting($first_name = '', $last_name = ''){
 return t('Hello @first_name @last_name', array('@first_name' => $first_name, '@last_name' => $last_name));
}*/ 
//351

function overvie() {
 $output = t('The following flavors are available...');
 // ... more code here
 return $output;
 }
 
function agregare() {

if (!$_POST){
$output='<form id="formAlta" action="http://localhost/drupal/colegio/inicia/dptos" method="post" accept-charset="UTF-8">
	<p>
	<fieldset form="formAlta">
	<legend align="left"><SPAN style="text-align:top">Introducir el nuevo departamento</SPAN></legend>
       <br><br>
	<p><SPAN style="text-align:center">   Nombre:   <input type="text" name="nombDpto"></SPAN></p>
	</fieldset>
	</p>
	<p><input type="submit" value="Grabar" style="font-weight:bold; color:black">  <input type="reset" value="Borrar" style="font-weight:bold; color:black">  <input type="button" style="font-wight:bold" value="Salir">
	</p>
	</form>';
}
else{

$output = "Departamento nuevo: " . $_POST["nombDpto"];
}
 //return t('A handy form to add flavors might go here...');
return $output;
 }
 
 function listare($type) {
 return t('List @type flavors', array('@type' => $type));
 }
function baja_est() {
 return ('hola');
 }

/**********
		*********************** Cursos oficiales ***********************
***********/

/******** Ciclos **********/

function listar_ciclos(){
$output="";
$tamano_pagina="2";

if(array_key_exists('pagina', $_GET)){
	$pagina=$_GET["pagina"];
}
else{
	$pagina=1;
}

$conexion=mysqli_connect("localhost", "colegio", "colegio", "colegio");//400
if (!$conexion){
	die("Conexión ha fallado:" . mysqli_connect_error());
}

mysqli_select_db($conexion, "colegio");

$sql="SELECT * FROM ciclos";
$result=mysqli_query($conexion, $sql);
$total_filas=mysqli_num_rows($result);
$total_paginas=ceil($total_filas / $tamano_pagina);

$sql="SELECT * FROM ciclos LIMIT " . (($pagina-1) * $tamano_pagina) . "," . $tamano_pagina;
$result=mysqli_query($conexion, $sql);
$output='<p align="center"><b><font size="4">Listado de los Ciclos del centro</font></b></p>';
$output=$output . '<table border="2"><tr><th><font size="3">Identificador</font></th><th><font size="3">Nombre Ciclo</font></th></th><th><font size="3">N&uacute;mero Convocatorias</font></th></tr>';
if($total_filas > 0){
	while ($row=mysqli_fetch_assoc($result)){
		$output=$output . '<tr><td><font color="blue" size="2">'. $row["ID_CICLO"] . '</font></td><td><font color="blue" size="2">' . $row["NOMBRE"] . '</font></td><td><font color="blue" size="2">' . $row["NUM_CONV"] . '</font></td></tr>';
	}
	$output=$output . '</table><br>';
}

mysqli_close($conexion);

if ($total_paginas > 1){
	for ($i=1;$i<=$total_paginas;$i++){
		if($pagina == $i){
			$output=$output . 'P&aacute;gina ' . $pagina . "&nbsp;&nbsp;";
		}
		else{
			$output=$output . '<a href="http://localhost/drupal/oficina/cursos_oficiales/ciclos/listar_ciclos?pagina=' . $i . '">P&aacute;gina ' . $i . '</a>&nbsp;&nbsp;';
		}

	}
}

return $output;
} 	/** end listar_ciclos **/


function alta_ciclo(){
$output="";//400

if (!$_POST){
	$output='<form id="formAltaCiclo" action="" method="post" accept-charset="UTF-8" size="100%">
	<p>
	<fieldset form="formAltaCiclo">
	<legend align="left"><SPAN style="text-align:top">Introducir un nuevo ciclo</SPAN></legend>
        <br><br>
	<p><SPAN style="text-align:center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nombre de Ciclo:&nbsp;<input type="text" style="color:blue" name="nombCiclo" required autofocus></SPAN></p>
	<p><SPAN style="text-align:center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;N&uacute;mero de Convocatorias:&nbsp;<input type="number" style="color:blue" name="numConv" min="1" max="3" required></SPAN></p>
	</fieldset>
	</p>
	<p><input type="submit" value="Agregar" style="font-weight:bold; color:black">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" value="Limpiar" style="font-weight:bold; color:black">  
	</p>
	</form>';
 }elseif ($_POST["nombCiclo"] == ""){
		$output='<br><b>Atenci&oacute;n</b><br><br><p>No puede dar de alta un Ciclo sin nombre</p><p>Para volver hacia atr&aacute;s&nbsp;<a href="http://localhost/drupal/oficina/cursos_oficiales/ciclos/alta_ciclo">pulse aqu&iacute;</a></p>'; 

	}
/*elseif ((ereg("^[1-3], $_POST["numConv"])) {
	$output='<br><b>Atenci&oacute;n</b><br><br><p>El numero de convocatorias tiene que ser un numero entre 1 y 3.</p>';
}*/
else{
	$conexion=mysqli_connect("localhost", "colegio", "colegio", "colegio");
	if (!$conexion){
		die("Conexión ha fallado:" . mysqli_connect_error());
	}

	$nombre=$_POST["nombCiclo"];
	$Conv=$_POST["numConv"];
	
	mysqli_select_db($conexion, "colegio");
	$sql="INSERT INTO ciclos (ID_CICLO, NOMBRE, NUM_CONV) VALUES (NULL, '$nombre', '$Conv')";
	
	if(mysqli_query($conexion, $sql)){
		$ant_id=mysqli_insert_id($conexion);
		$output= '<p><b>Nuevo ciclo registrado satisfactoriamente con:</b></p>
		<p>Identificador&nbsp;<b>' . $ant_id . '</b></p> 
		<p>Nombre&nbsp; <b>' . $nombre . '</b></p>
		<p>N&uacute;mero de convocatorias&nbsp; <b>' . $Conv . '</b></p>
		<br><br>
		<p align="center">Si desea agregar otro ciclo <a href="http://localhost/drupal/oficina/cursos_oficiales/ciclos/alta_ciclo">pulse aqu&iacute;</a></p>'; 
	}
	
	mysqli_close($conexion);
}

return $output;

} 	/** end alta_ciclo **/


function baja_ciclo(){
$output="";
$conexion=mysqli_connect("localhost", "colegio", "colegio", "colegio");
	if (!$conexion){
		die("Conexión ha fallado:" . mysqli_connect_error());
	}
mysqli_select_db($conexion, "colegio");	

if (!$_POST){
	$output='<form id="formBajaCiclo" action="" method="post" accept-charset="UTF-8" size="100%">
	<p>
	<fieldset form="formBajaCiclo">
	<legend align="left"><SPAN style="text-align:top">Eliminar un ciclo</SPAN></legend>
        <br><br>
	<p><SPAN style="text-align:top">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Seleccionar un ciclo:&nbsp;<p align="center"><select name="nombCiclo" size="2">';
	
	$sql="SELECT nombre FROM ciclos";
	$result=mysqli_query($conexion, $sql);
	if (mysqli_num_rows($result) > 0){
		while($row=mysqli_fetch_assoc($result)){
			$output= $output . '<option>' . $row["nombre"] . '</option>';
		}//501
	}
	else{
		  $output= $output . '<option></option>';
	}
	$output= $output . '</p></select></fieldset>
	</p>
	<p><input type="submit" value="Eliminar" style="font-weight:bold; color:black">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" value="Limpiar" style="font-weight:bold; color:black">  
	</p>
	</form>';
} 
else{
	$nombre=$_POST["nombCiclo"];
	//mysqli_select_db($conexion, "colegio");
	$sql="SELECT ID_CICLO FROM ciclos WHERE NOMBRE='$nombre'";
	$result=mysqli_query($conexion, $sql);
	$id=mysqli_fetch_array($result);
	$sql="DELETE FROM ciclos WHERE NOMBRE='$nombre'";
	if(mysqli_query($conexion, $sql)){	
		$output= '<p><b>El ciclo seleccionado se ha borrado satisfactoriamente con:</b></p>
		<p>Identificador&nbsp;<b>' .$id[0] . '</b></p> 
		<p>Nombre&nbsp;<b>' . $nombre . '</b></p><br><br>';
		$output=$output . '<p align="center">Si desea eliminar otro ciclo&nbsp;<a href="http://localhost/drupal/oficina/cursos_oficiales/ciclos/baja_ciclo">pulse aqu&iacute;</a></p>';		
	}
	else{
		$output='<p><b>Error al eliminar el registro con el nombre:&nbsp;' . $nombre . '<b></p>';
		$output=$output . '<p>'. mysqli_error($conexion) . '</p>';
	}

}
mysqli_close($conexion);
return $output;

} 	/** end baja_ciclo **/

	
function modificar_ciclo(){
$output="";
$error=false;

$conexion=mysqli_connect("localhost", "colegio", "colegio", "colegio");
	if (!$conexion){
		die("Conexión ha fallado:" . mysqli_connect_error());
	}
mysqli_select_db($conexion, "colegio");	
if (!$_POST){
	$output='<form id="formModCiclo" action="" method="post" accept-charset="UTF-8" size="100%">
	<p>
	<fieldset form="formModCiclo">
	<legend align="left"><SPAN style="text-align:top">Cambiar un ciclo</SPAN></legend>
        <br><br>
	<SPAN style="text-align:center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Seleccionar un ciclo:&nbsp;<p align="center"><select name="nombCiclo" size="5" required>';
	
	$sql="SELECT nombre, num_conv FROM ciclos";
	$result=mysqli_query($conexion, $sql);
	if (mysqli_num_rows($result) > 0){
		while($row=mysqli_fetch_assoc($result)){
			$output= $output . '<option>' . $row["nombre"] . '</option>';
			//$id=$row["id_ciclo"];$conv=$row["num_conv"];
		}
	}
	else{
		  $output= $output . '<option></option>';
	}
	$output= $output . '</select></p></SPAN>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Introducir datos a modificar:</p>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nombre:&nbsp;<input type="text" style="color:blue" name="nuevoNomb"></p>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Convocatorias:&nbsp;<input type="number" style="color:blue" name="nuevoConv" placeholder="N&uacute;merico entre 1 y 3"></p>';
	

/*<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Indicar los datos a modificar:&nbsp;<p align="center"><select name="campo" size="1">
	<option selected>Elegir...</option>
	<option>Nombre</option>
	<option>N&uacute;mero Convocatorias</option>
	</select>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nuevo dato a cambiar:&nbsp;<input type="text" style="color:blue" name="nuevo"></p></p><br>';
	if ($_POST["campo"]=="Nombre"){
		$output=$output . '<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Indicar el nuevo nombre:&nbsp; <input type="text" style="color:blue" name="nuevoNomb"></p>';
	}else{
		$output=$output . '<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Indicar el nuevo n&uacute;mero de convocatorias:&nbsp; <input type="text" style="color:blue" name="nuevoConv"></p>';
}*/

	$output=$output . '</fieldset>
	</p>
	<p><input type="submit" value="Grabar" style="font-weight:bold; color:black">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" value="Limpiar" style="font-weight:bold; color:black">  
	</p>
	</form>';

} 
else{
	$nombre=$_POST["nombCiclo"];
	$nombnuevo=$_POST["nuevoNomb"];
	$convnuevo=$_POST["nuevoConv"];
	
	//mysqli_select_db($conexion, "colegio");
	$sql="SELECT ID_CICLO FROM ciclos WHERE NOMBRE='$nombre'";
	$result=mysqli_query($conexion, $sql);
	$id=mysqli_fetch_array($result);
	$num=$id[0];

	if (($nombnuevo == "") && ($convnuevo == "")){
		$output='<br><br><font color="red"><b>Atenci&oacute;n</b></font><br><br><p>No ha introducido ning&uacute;n dato para actualizar el registro seleccionado:&nbsp;<b>' . $nombre . '</b></p>&nbsp;';
		$output=$output . '<br><p align="center">Para volver a intentarlo&nbsp;<a href="http://localhost/drupal/oficina/cursos_oficiales/ciclos/modificar_ciclo">pulse aqu&iacute;</a></p>';
	} 
	else{
		$output= '<br><br><p><b>Actualizaci&oacute;n del registro seleccionado.</b></p>'; 
		if ($nombnuevo == ""){
			if (($convnuevo < "1") || ($convnuevo >="3")){
				$output= $output . '<p>El rango n&uacute;merico introducido para el campo convocatorias no es correcto</p>';
				$output= $output . '<br><p align="center">Para volver a modificarlo,&nbsp;<a href="http://localhost/drupal/oficina/cursos_oficiales/ciclos/modificar_ciclo">pulse aqu&iacute;</a></p>';
			}else{
				$sql="UPDATE ciclos SET NUM_CONV='$convnuevo' WHERE ID_CICLO= '$id[0]'";
				if(mysqli_query($conexion, $sql)){	
					$output=$output . '<p>El registro seleccionado, se ha actualizado con el n&uacute;mero de convocatorias igual a:&nbsp;<b>' . $convnuevo . '</b></p>';
					$output=$output . '<br><p align="center">Si desea modificar otro departamento&nbsp;<a href="http://localhost/drupal/oficina/cursos_oficiales/ciclos/modificar_ciclo">pulse aqu&iacute;</a></p>';
				}
				else{
					$error=true;
				}
			}
		}elseif ($convnuevo == ""){
			$sql="UPDATE ciclos SET NOMBRE='$nombnuevo' WHERE ID_CICLO= '$id[0]'";
			if(mysqli_query($conexion, $sql)){	
				$output=$output . '<p>El registro seleccionado, se ha actualizado con el nuevo nombre:&nbsp;<b>' . $nombnuevo . '</b></p>';
				$output=$output . '<br><p align="center">Si desea modificar otro departamento&nbsp;<a href="http://localhost/drupal/oficina/cursos_oficiales/ciclos/modificar_ciclo">pulse aqu&iacute;</a></p>';
			}
			else{
				$error=true;
			}
		}else{
			if (($convnuevo >= "1") || ($convnuevo <="3")){
				$output= $output . '<p>El rango n&uacute;merico introducido para el campo convocatorias no es correcto</p>';
				$output= $output . '<br><p align="center">Para volver a modificarlo,&nbsp;<a href="http://localhost/drupal/oficina/cursos_oficiales/ciclos/modificar_ciclo">pulse aqu&iacute;</a></p>';
			}else{
				$sql="UPDATE ciclos SET NOMBRE='$nombnuevo', NUM_CONV='$nombnuevo' WHERE ID_CICLO= '$id[0]'";
				if(mysqli_query($conexion, $sql)){	
					$output=$output . '<p>El registro seleccionado, se ha actualizado con:</p>'; 
					$output=$output . '<p>Nuevo nombre&nbsp;<b>' . $nombnuevo .'</b></p><p>N&uacute;mero de convocatorias&nbsp;<b>' . $convnuevo . '</b></p>';
					$output=$output . '<br><p align="center">Si desea modificar otro departamento&nbsp;<a href="http://localhost/drupal/oficina/cursos_oficiales/ciclos/modificar_ciclo">pulse aqu&iacute;</a></p>';
				}
				else{
					$error=true;
				}
			}
		}
	}
	if ($error){
		$output='<p><b>Se ha producido un Error al actualizar el registro con el nombre:&nbsp;' . $nombre . '</b></p>';
		$output=$output . '<p>'. mysqli_error($conexion) . '</p>';
	}

} 
mysqli_close($conexion);
return $output;

} 	/** end modificar_ciclo **/


/******** Cursos **********/

function listar_cursos(){
$output="";
$tamano_pagina="10";

if(array_key_exists('pagina', $_GET)){
	$pagina=$_GET["pagina"];
}
else{
	$pagina=1;
}

$conexion=mysqli_connect("localhost", "colegio", "colegio", "colegio");
if (!$conexion){
	die("Conexión ha fallado:" . mysqli_connect_error());
}

mysqli_select_db($conexion, "colegio");

$sql="SELECT * FROM cursos";
$result=mysqli_query($conexion, $sql);
$total_filas=mysqli_num_rows($result);
$total_paginas=ceil($total_filas / $tamano_pagina);

$sql="SELECT * FROM cursos LIMIT " . (($pagina-1) * $tamano_pagina) . "," . $tamano_pagina;
$result=mysqli_query($conexion, $sql);
$output='<p align="center"><b><font size="4">Listado de los Cursos del centro</font></b></p>';
$output=$output . '<table border="2"><tr><th><font size="3">Identificador</font></th><th><font size="3">Nombre Curso</font></th></tr>';
if($total_filas > 0){
	while ($row=mysqli_fetch_assoc($result)){
		$output=$output . '<tr><td><font color="blue" size="2">'. $row["ID_CURSO"] . '</font></td><td><font color="blue" size="2">' . $row["NOMBRE"] . '</font></td></tr>';
	}
	$output=$output . '</table><br>';
}

mysqli_close($conexion);

if ($total_paginas > 1){
	for ($i=1;$i<=$total_paginas;$i++){
		if($pagina == $i){
			$output=$output . 'P&aacute;gina ' . $pagina . "&nbsp;&nbsp;";
		}
		else{
			$output=$output . '<a href="http://localhost/drupal/oficina/cursos_oficiales/cursos/listar_cursos?pagina=' . $i . '">P&aacute;gina ' . $i . '</a>&nbsp;&nbsp;';
		}

	}
}

return $output;
} 	/** end listar_cursos **/


function alta_curso(){
$output="";

$conexion=mysqli_connect("localhost", "colegio", "colegio", "colegio");
	if (!$conexion){
		die("Conexión ha fallado:" . mysqli_connect_error());
	}
mysqli_select_db($conexion, "colegio");

if (!$_POST){
	$output='<form id="formAltaCurso" action="" method="post" accept-charset="UTF-8" size="100%">
	<p>
	<fieldset form="formAltaCurso">
	<legend align="left"><SPAN style="text-align:top">Introducir un nuevo curso</SPAN></legend>
        <br><br>
	<p><SPAN style="text-align:center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nombre de Curso:&nbsp;<input type="text" style="color:blue" name="nombCurso" required autofocus></SPAN></p>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Asignar un Ciclo:&nbsp;<p align="center"><select name="Ciclo" required size="4">';
	$sql="SELECT nombre FROM ciclos";
	$result=mysqli_query($conexion, $sql);
	if (mysqli_num_rows($result) > 0){
		while($row=mysqli_fetch_assoc($result)){
			$output= $output . '<option>' . $row["nombre"] . '</option>';
		}
	}
	else{
		  $output= $output . '<option></option>';
	}
	$output=$output . '</select></p>
	</fieldset>
	</p>
	<p><input type="submit" value="Agregar" style="font-weight:bold; color:black">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" value="Limpiar" style="font-weight:bold; color:black">  
	</p>
	</form>';
 }elseif ($_POST["nombCurso"] == ""){
		$output='<br><b>Atenci&oacute;n</b><br><br><p>No puede dar de alta un Curso sin nombre</p><p>Para volver hacia atr&aacute;s&nbsp;<a href="http://localhost/drupal/oficina/cursos_oficiales/cursos/alta_curso">pulse aqu&iacute;</a></p>'; 

}
else{
	$nombre=$_POST["nombCurso"];
	$nombCiclo=$_POST["Ciclo"];
	$sql="SELECT ID_CICLO FROM ciclos WHERE NOMBRE='$nombCiclo'";
	$result=mysqli_query($conexion, $sql);
	$idCiclo=mysqli_fetch_array($result);
	$sql="INSERT INTO cursos (ID_CURSO, NOMBRE, ID_CICLO) VALUES (NULL, '$nombre', '$idCiclo[0]')";
	if(mysqli_query($conexion, $sql)){
		$ant_id=mysqli_insert_id($conexion);
		$output= '<p><b>Nuevo curso registrado satisfactoriamente con:</b></p>
		<p>Identificador&nbsp;<b>' . $ant_id . '</b></p> 
		<p>Nombre&nbsp; <b>' . $nombre . '</b></p>
		<p>Ciclo del curso&nbsp; <b>' . $nombCiclo . '</b></p>
		<br><br>
		<p align="center">Si desea agregar otro curso <a href="http://localhost/drupal/oficina/cursos_oficiales/cursos/alta_curso">pulse aqu&iacute;</a></p>'; 
	}	
}
mysqli_close($conexion);
return $output;

} 	/** end alta_curso **/


function baja_curso(){
$output="";
$conexion=mysqli_connect("localhost", "colegio", "colegio", "colegio");
	if (!$conexion){
		die("Conexión ha fallado:" . mysqli_connect_error());
	}
mysqli_select_db($conexion, "colegio");	

if (!$_POST){
	$output='<form id="formBajaCurso" action="" method="post" accept-charset="UTF-8" size="100%">
	<p>
	<fieldset form="formBajaCurso">
	<legend align="left"><SPAN style="text-align:top">Eliminar un ciclo</SPAN></legend>
        <br><br>
	<p><SPAN style="text-align:top">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Seleccionar un curso:&nbsp;<p align="center"><select name="nombCurso" size="5">';
	
	$sql="SELECT nombre FROM cursos";
	$result=mysqli_query($conexion, $sql);
	if (mysqli_num_rows($result) > 0){
		while($row=mysqli_fetch_assoc($result)){
			$output= $output . '<option>' . $row["nombre"] . '</option>';
		}
	}
	else{
		  $output= $output . '<option></option>';
	}
	$output= $output . '</select></p></SPAN></p></fieldset>
	</p>
	<p><input type="submit" value="Eliminar" style="font-weight:bold; color:black">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" value="Limpiar" style="font-weight:bold; color:black">  
	</p>
	</form>';
} 
else{
	$nombre=$_POST["nombCurso"];
	//mysqli_select_db($conexion, "colegio");
	$sql="SELECT ID_CURSO FROM cursos WHERE NOMBRE='$nombre'";
	$result=mysqli_query($conexion, $sql);
	$id=mysqli_fetch_array($result);
	$sql="DELETE FROM cursos WHERE NOMBRE='$nombre'";
	if(mysqli_query($conexion, $sql)){	
		$output= '<p><b>El curso seleccionado se ha borrado satisfactoriamente con:</b></p>
		<p>Identificador&nbsp;<b>' . $id[0] . '</b></p> 
		<p>Nombre&nbsp;<b>' . $nombre . '</b></p><br><br>';
		$output=$output . '<p align="center">Si desea eliminar otro curso&nbsp;<a href="http://localhost/drupal/oficina/cursos_oficiales/cursos/baja_curso">pulse aqu&iacute;</a></p>';		
	}
	else{
		$output='<p><b>Error al eliminar el registro con el nombre:&nbsp;' . $nombre . '<b></p>';
		$output=$output . '<p>'. mysqli_error($conexion) . '</p>';
	}

}
mysqli_close($conexion);
return $output;

} 	/** end baja_curso **/

	
function modificar_curso(){
$output="";

$conexion=mysqli_connect("localhost", "colegio", "colegio", "colegio");
	if (!$conexion){
		die("Conexión ha fallado:" . mysqli_connect_error());
	}
mysqli_select_db($conexion, "colegio");	

if (!$_POST){
	$output='<form id="formModCurso" action="" method="post" accept-charset="UTF-8" size="100%">
	<p>
	<fieldset form="formModCurso">
	<legend align="left"><SPAN style="text-align:top">Cambiar un ciclo</SPAN></legend>
        <br><br>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Seleccionar un Curso:&nbsp;<p align="center"><select name="nombCurso" size="5" required>';
	
	$sql="SELECT nombre FROM cursos";
	$result=mysqli_query($conexion, $sql);
	if (mysqli_num_rows($result) > 0){
		while($row=mysqli_fetch_assoc($result)){
			$output= $output . '<option>' . $row["nombre"] . '</option>';
		}
	}
	else{
		  $output= $output . '<option></option>';
	}
	$output= $output . '</select></p>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Indicar el nuevo nombre del curso:&nbsp;<input type="text" style="color:blue" name="nuevoNomb" required></p>
	</fieldset>
	<p><input type="submit" value="Grabar" style="font-weight:bold; color:black">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" value="Limpiar" style="font-weight:bold; color:black">  
	</p>
	</form>';

} 
else{
	$nombre=$_POST["nombCurso"];
	$nombnuevo=$_POST["nuevoNomb"];
	//mysqli_select_db($conexion, "colegio");
	$sql="SELECT ID_CURSO FROM cursos WHERE NOMBRE='$nombre'";
	$result=mysqli_query($conexion, $sql);
	$id=mysqli_fetch_array($result);
	$num=$id[0];

	if ($nombnuevo == ""){
		$output='<br><br><font color="red"><b>Atenci&oacute;n</b></font><br><br><p>No ha introducido ning&uacute;n dato para actualizar el registro seleccionado:&nbsp;<b>' . $nombre . '</b></p>&nbsp;';
		$output=$output . '<br><p align="center">Para volver a intentarlo&nbsp;<a href="http://localhost/drupal/oficina/cursos_oficiales/cursos/modificar_curso">pulse aqu&iacute;</a></p>';
	} 
	else{
		$output= '<br><br><p><b>Actualizaci&oacute;n del registro seleccionado.</b></p>'; 
		$sql="UPDATE cursos SET NOMBRE='$nombnuevo' WHERE ID_CURSO= '$id[0]'";
			if(mysqli_query($conexion, $sql)){	
				$output=$output . '<p>El registro seleccionado, se ha actualizado con el nuevo nombre:&nbsp;<b>' . $nombnuevo . '</b></p>';
				$output=$output . '<br><p align="center">Si desea modificar otro Curso&nbsp;<a href="http://localhost/drupal/oficina/cursos_oficiales/cursos/modificar_curso">pulse aqu&iacute;</a></p>';
			}
			else{
				$output='<p><b>Se ha producido un Error al actualizar el registro con el nombre:&nbsp;' . $nombre . '</b></p>';
				$output=$output . '<p>'. mysqli_error($conexion) . '</p>';
			}
	}
} 
mysqli_close($conexion);
return $output;

} 	/** end modificar_curso **/



/******** Unidades **********/

function listar_unidades(){
$output="";
$tamano_pagina="10";

if(array_key_exists('pagina', $_GET)){
	$pagina=$_GET["pagina"];
}
else{
	$pagina=1;
}

$conexion=mysqli_connect("localhost", "colegio", "colegio", "colegio");
if (!$conexion){
	die("Conexión ha fallado:" . mysqli_connect_error());
}

mysqli_select_db($conexion, "colegio");

$sql="SELECT * FROM grupos_a";
$result=mysqli_query($conexion, $sql);
$total_filas=mysqli_num_rows($result);
$total_paginas=ceil($total_filas / $tamano_pagina);

$sql="SELECT * FROM grupos_a LIMIT " . (($pagina-1) * $tamano_pagina) . "," . $tamano_pagina;
$result=mysqli_query($conexion, $sql);
$output='<p align="center"><b><font size="4">Listado de las Unidades del centro</font></b></p>';
$output=$output . '<table border="2"><tr><th><font size="3">Identificador</font></th><th><font size="3">Nombre Unidad</font></th><th><font size="3">Aula</font></th><th><font size="3">Dia de Tutoria</font></th><th><font size="3">Hora de Tutoria</font></th></tr>';
if($total_filas > 0){
	while ($row=mysqli_fetch_assoc($result)){
		$output=$output . '<tr><td><font color="blue" size="2">'. $row["ID_GRUPOSA"] . '</font></td><td><font color="blue" size="2">' . $row["NOMBRE"] . '</font></td><td><font color="blue" size="2">' . $row["AULA"] . '</font></td><td><font color="blue" size="2">' . $row["DIA_TUTORIA"] . '</font></td><td><font color="blue" size="2">' . $row["HORA_TUTORIA"] . '</font></td></tr>';
	}
	$output=$output . '</table><br>';
}

mysqli_close($conexion);

if ($total_paginas > 1){
	for ($i=1;$i<=$total_paginas;$i++){
		if($pagina == $i){
			$output=$output . 'P&aacute;gina ' . $pagina . "&nbsp;&nbsp;";
		}
		else{
			$output=$output . '<a href="http://localhost/drupal/oficina/cursos_oficiales/unidades/listar_unidades?pagina=' . $i . '">P&aacute;gina ' . $i . '</a>&nbsp;&nbsp;';
		}

	}
}

return $output;
} 	/** end listar_unidades **/


function alta_unidad(){
$output="";

$conexion=mysqli_connect("localhost", "colegio", "colegio", "colegio");
	if (!$conexion){
		die("Conexión ha fallado:" . mysqli_connect_error());
	}
mysqli_select_db($conexion, "colegio");

if (!$_POST){
	$output='<form id="formAltaUnidad" action="" method="post" accept-charset="UTF-8" size="100%">
	<p>
	<fieldset form="formAltaUnidad">
	<legend align="left"><SPAN style="text-align:top">Introducir una nueva unidad</SPAN></legend>
        <br><br>
	<p><SPAN style="text-align:center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nombre de Unidad:&nbsp;<input type="text" style="color:blue" name="nombUnidad" required autofocus></SPAN></p>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Asignar un Curso:&nbsp;<p align="center"><select name="Curso" required size="4">';
	$sql="SELECT nombre FROM cursos";
	$result=mysqli_query($conexion, $sql);
	if (mysqli_num_rows($result) > 0){
		while($row=mysqli_fetch_assoc($result)){
			$output= $output . '<option>' . $row["nombre"] . '</option>';
		}
	}
	else{
		  $output= $output . '<option></option>';
	}
	$output=$output . '</select></p>
	<p><SPAN style="text-align:center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Aula aignada:&nbsp;<input type="text" style="color:blue" name="Aula"></SPAN></p>
	<p><SPAN style="text-align:center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;D&iacute;a de Tutor&iacute;a:&nbsp;<input type="text" style="color:blue" name="diaTutoria"></SPAN></p>
	<p><SPAN style="text-align:center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Hora de Tutor&iacute;a:&nbsp;<input type="time" style="color:blue" name="horaTutoria"></SPAN></p>
	</fieldset>
	</p>
	<p><input type="submit" value="Agregar" style="font-weight:bold; color:black">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" value="Limpiar" style="font-weight:bold; color:black">  
	</p>
	</form>';
 }elseif ($_POST["nombUnidad"] == ""){
		$output='<br><b>Atenci&oacute;n</b><br><br><p>No puede dar de alta una Unidad sin nombre</p><p>Para volver hacia atr&aacute;s&nbsp;<a href="http://localhost/drupal/oficina/cursos_oficiales/unidades/alta_unidad">pulse aqu&iacute;</a></p>'; 

}
else{
	$nombre=$_POST["nombUnidad"];
	$nombCurso=$_POST["Curso"];
	$aula=$_POST["Aula"];
	$diat=$_POST["diaTutoria"];
	$horat=$_POST["horaTutoria"];
	$sql="SELECT ID_CURSO FROM cursos WHERE NOMBRE='$nombCurso'";
	$result=mysqli_query($conexion, $sql);
	$idCurso=mysqli_fetch_array($result);

	$sql="INSERT INTO grupos_a (ID_GRUPOSA, ID_CURSO, NOMBRE, AULA, DIA_TUTORIA, HORA_TUTORIA) VALUES (NULL, '$idCurso[0]', '$nombre', '$aula', '$diat', '$horat')";
	if(mysqli_query($conexion, $sql)){
		$ant_id=mysqli_insert_id($conexion);
		$output= '<br><p><b>Nueva unidad registrada satisfactoriamente con:</b></p>
		<p>Identificador&nbsp;<b>' . $ant_id . '</b></p> 
		<p>Unidad&nbsp; <b>' . $nombre . '</b></p>
		<p>Curso de la Unidad&nbsp; <b>' . $nombCurso . '</b></p>
		<p>Aula de la unidad&nbsp; <b>' . $aula . '</b></p>
		<p>D&iacute;a de la semana de tutor&iacute;ad&nbsp; <b>' . $diat . '</b></p>
		<p>Hora de tutor&iacute;a&nbsp;<b>' . $horat . '</b></p>
		<br><br>
		<p align="center">Si desea agregar otra unidad <a href="http://localhost/drupal/oficina/cursos_oficiales/unidades/alta_unidad">pulse aqu&iacute;</a></p>'; 
	}	
}
mysqli_close($conexion);
return $output;

} 	/** end alta_unidad **/

function baja_unidad(){
$output="";
$conexion=mysqli_connect("localhost", "colegio", "colegio", "colegio");
	if (!$conexion){
		die("Conexión ha fallado:" . mysqli_connect_error());
	}
mysqli_select_db($conexion, "colegio");	

if (!$_POST){
	$output='<form id="formBajaUnidad" action="" method="post" accept-charset="UTF-8" size="100%">
	<p>
	<fieldset form="formBajaUnidad">
	<legend align="left"><SPAN style="text-align:top">Eliminar una unidad</SPAN></legend>
        <br><br>
	<p><SPAN style="text-align:top">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Seleccionar una unidad:&nbsp;<p align="center"><select name="nombUnidad" size="2">';
	
	$sql="SELECT nombre FROM grupos_a";
	$result=mysqli_query($conexion, $sql);
	if (mysqli_num_rows($result) > 0){
		while($row=mysqli_fetch_assoc($result)){
			$output= $output . '<option>' . $row["nombre"] . '</option>';
		}//501
	}
	else{
		  $output= $output . '<option></option>';
	}
	$output= $output . '</select></p></p></fieldset>
	</p>
	<p><input type="submit" value="Eliminar" style="font-weight:bold; color:black">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" value="Limpiar" style="font-weight:bold; color:black">  
	</p>
	</form>';
} 
else{
	$nombre=$_POST["nombUnidad"];
	$sql="SELECT ID_GRUPOSA FROM unidades WHERE NOMBRE='$nombre'";
	$result=mysqli_query($conexion, $sql);
	$id=mysqli_fetch_array($result);
	$sql="DELETE FROM unidades WHERE NOMBRE='$nombre'";
	if(mysqli_query($conexion, $sql)){	
		$output= '<p><b>La unidad seleccionada se ha borrado satisfactoriamente con:</b></p>
		<p>Identificador&nbsp;<b>' .$id[0] . '</b></p> 
		<p>Nombre&nbsp;<b>' . $nombre . '</b></p><br><br>';
		$output=$output . '<p align="center">Si desea eliminar otra unidad&nbsp;<a href="http://localhost/drupal/oficina/cursos_oficiales/unidades/baja_unidad">pulse aqu&iacute;</a></p>';		
	}
	else{
		$output='<p><b>Error al eliminar el registro con el nombre:&nbsp;' . $nombre . '<b></p>';
		$output=$output . '<p>'. mysqli_error($conexion) . '</p>';
	}

}
mysqli_close($conexion);
return $output;

}        /** end baja_unidad  **/


function modificar_unidad(){
$output="";
$error=false;

$conexion=mysqli_connect("localhost", "colegio", "colegio", "colegio");
	if (!$conexion){
		die("Conexión ha fallado:" . mysqli_connect_error());
	}
mysqli_select_db($conexion, "colegio");	
if (!$_POST){
	$output='<form id="formModUnidad" action="" method="post" accept-charset="UTF-8" size="100%">
	<p>
	<fieldset form="formModUnidad">
	<legend align="left"><SPAN style="text-align:top">Cambiar un unidad</SPAN></legend>
        <br><br>
	<SPAN style="text-align:center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Seleccionar una unidad:&nbsp;<p><select name="nombUnidad" size="5" required>';
	
	$sql="SELECT nombre FROM grupos_a";
	$result=mysqli_query($conexion, $sql);
	if (mysqli_num_rows($result) > 0){
		while($row=mysqli_fetch_assoc($result)){
			$output= $output . '<option>' . $row["nombre"] . '</option>';
			//$id=$row["id_ciclo"];$conv=$row["num_conv"];
		}
	}
	else{
		  $output= $output . '<option></option>';
	}
	$output= $output . '</select></p></SPAN>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Introducir datos a modificar:</p>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nombre:&nbsp;<input type="text" style="color:blue" name="nuevoNomb"></p>
	<p><SPAN style="text-align:center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Aula aignada:&nbsp;<input type="text" style="color:blue" name="Aula"></SPAN></p>
	<p><SPAN style="text-align:center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;D&iacute;a de Tutor&iacute;a:&nbsp;<input type="text" style="color:blue" name="diaTutoria"></SPAN></p>
	<p><SPAN style="text-align:center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Hora de Tutor&iacute;a:&nbsp;<input type="time" style="color:blue" name="horaTutoria"></SPAN></p>';
	$output=$output . '</fieldset>
	</p>
	<p><input type="submit" value="Grabar" style="font-weight:bold; color:black">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" value="Limpiar" style="font-weight:bold; color:black">  
	</p>
	</form>';
} 
else{
	$nombre=$_POST["nombUnidad"];
	$nombnuevo=$_POST["nuevoNomb"];
	$aula=$_POST["Aula"];
	$diat=$_POST["diaTutoria"];
	$horat=$_POST["horaTutoria"];
	//mysqli_select_db($conexion, "colegio");
	$sql="SELECT ID_GRUPOSA FROM grupos_a WHERE NOMBRE='$nombre'";
	$result=mysqli_query($conexion, $sql);
	$id=mysqli_fetch_array($result);
	$num=$id[0];

	if (($nombnuevo == "") && ($aula == "") && ($diat == "") && ($horat == "")){
		$output='<br><br><font color="red"><b>Atenci&oacute;n</b></font><br><br><p>No ha introducido ning&uacute;n dato para actualizar el registro seleccionado:&nbsp;<b>' . $nombre . '</b></p>&nbsp;';
		$output=$output . '<br><p align="center">Para volver a intentarlo&nbsp;<a href="http://localhost/drupal/oficina/cursos_oficiales/unidades/modificar_unidad">pulse aqu&iacute;</a></p>';
	} 
	else{
		$output= '<br><br><p><b>Actualizaci&oacute;n del registro seleccionado.</b></p>'; 
		if ($nombnuevo <> ""){
			$sql="UPDATE grupos_a SET NOMBRE= '$nombnuevo' WHERE ID_GRUPOSA= '$id[0]'";
			if(mysqli_query($conexion, $sql)){
				$output=$output . '<p>Nombre actualizado:&nbsp;<b>' . $nombnuevo . '</b></p>';
			} 
			else{
				$error=true;	 
			}
		} 
		if ($aula <> ""){
			$sql="UPDATE grupos_a SET AULA= '$aula' WHERE ID_GRUPOSA= '$id[0]'";
			if(mysqli_query($conexion, $sql)){
				$output= $output . '<p>Aula actualizada::&nbsp;<b>' . $aula . '</b></p>';
			} 
			else{
				$error=true;	 
			}
		} 
		if ($diat <> ""){	
			$sql="UPDATE grupos_a SET DIA_TUTORIA= '$diat' WHERE ID_GRUPOSA= '$id[0]'";
			if(mysqli_query($conexion, $sql)){
				$output=$output . '<p>D&iacute;a de tutor&iacute;a actualizado:&nbsp;<b>' . $diat . '</b></p>';
			} 
			else{
				$error=true;	 
			}
		} 
		if ($horat <> ""){	
			$sql="UPDATE grupos_a SET HORA_TUTORIA= '$horat' WHERE ID_GRUPOSA= '$id[0]'";
			if(mysqli_query($conexion, $sql)){
				$output=$output . '<p>Hora de tutor&iacute;a actualizado:&nbsp;<b>' . $horat . '</b></p>';
			} 
			else{
				$error=true;	 
			}
		}

		if ($error){
			$output='<p><b>Se ha producido un Error al actualizar el registro con el nombre:&nbsp;' . $nombre . '</b></p>';
			$output=$output . '<p>'. mysqli_error($conexion) . '</p>';
		}
		else{
			$output=$output . '<br><p align="center">Si desea modificar otra Uniad&nbsp;<a href="http://localhost/drupal/oficina/cursos_oficiales/unidades/modificar_unidad">pulse aqu&iacute;</a></p>';
		}
	}
	
} 
mysqli_close($conexion);
return $output;

}	/** end modificar_unidad **/

/**********
		*********************** Departamentos ***********************
***********/

function listar_departamentos() {
$output="";
$tamano_pagina="15";

if(array_key_exists('pagina', $_GET)){
	$pagina=$_GET["pagina"];
}
else{
	$pagina=1;
}

$conexion=mysqli_connect("localhost", "colegio", "colegio", "colegio");//400
if (!$conexion){
	die("Conexión ha fallado:" . mysqli_connect_error());
}

mysqli_select_db($conexion, "colegio");

$sql="SELECT * FROM departamentos";
$result=mysqli_query($conexion, $sql);
$total_filas=mysqli_num_rows($result);
$total_paginas=ceil($total_filas / $tamano_pagina);

$sql="SELECT * FROM departamentos LIMIT " . (($pagina-1) * $tamano_pagina) . "," . $tamano_pagina;
$result=mysqli_query($conexion, $sql);
$output='<p align="center"><b><font size="4">Listado de los Departamentos activos en el centro</font></b></p>';
$output=$output . '<table border="2"><tr><th><font size="2">Identificador</font></th><th><font size="2">Nombre Departamento</font></th></tr>';
if($total_filas > 0){
	while ($row=mysqli_fetch_assoc($result)){
		$output=$output . '<tr><td><font color="blue" size="2">'. $row["ID_DPTO"] . '</font></td><td><font color="blue" size="2">' . $row["NOMBRE"] . '</font></td></tr>';
	}
	$output=$output . '</table><br>';
}

mysqli_close($conexion);

if ($total_paginas > 1){
	for ($i=1;$i<=$total_paginas;$i++){
		if($pagina == $i){
			$output=$output . 'P&aacute;gina ' . $pagina . "&nbsp;&nbsp;";
		}
		else{
			$output=$output . '<a href="http://localhost/drupal/oficina/departamentos/listar_departamentos?pagina=' . $i . '">P&aacute;gina ' . $i . '</a>&nbsp;&nbsp;';
		}

	}
}

return $output;
}  /** end listar_departamentos **/

function alta_departamento() {
$output="";

if (!$_POST){
$output='<form id="formAltaDpto" action="" method="post" accept-charset="UTF-8" size="100%">
	<p>
	<fieldset form="formAltaDpto">
	<legend align="left"><SPAN style="text-align:top">Introducir un nuevo departamento</SPAN></legend>
        <br><br>
	<p><SPAN style="text-align:center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nombre Departamento:&nbsp;<input type="text" style="color:blue" name="nombDpto" required autofocus></SPAN></p>
	</fieldset>
	</p>
	<p><input type="submit" value="Agregar" style="font-weight:bold; color:black">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" value="Limpiar" style="font-weight:bold; color:black">  
	</p>
	</form>';
 }
elseif ($_POST["nombDpto"] == ""){
		$output='<br><b>Atenci&oacute;n</b><br><br><p>No puede dar de alta un Departamento sin nombre</p><p>Para volver hacia atr&aacute;s&nbsp;<a href="http://localhost/drupal/oficina/departamentos/alta_departamento">pulse aqu&iacute;</a></p>'; 

} 
else{
	$conexion=mysqli_connect("localhost", "colegio", "colegio", "colegio");
	if (!$conexion){
		die("Conexión ha fallado:" . mysqli_connect_error());
	}

	$nombre=$_POST["nombDpto"];
	mysqli_select_db($conexion, "colegio");
	$sql="INSERT INTO departamentos (ID_DPTO, NOMBRE) VALUES (NULL, '$nombre')";
	
	if(mysqli_query($conexion, $sql)){
		$ant_id=mysqli_insert_id($conexion);
		$output= '<p><b>Nuevo departamento registrado satisfactoriamente</b>.</p><p>Identificador de nuevo registro: <b>' . $ant_id . '</b></p> 
		<p>Nombre del nuevo registro: <b>' . $nombre . '</b></p><br><br>
		<p align="center">Si desea agregar otro departamento <a href="http://localhost/drupal/oficina/departamentos/alta_departamento">pulse aqu&iacute;</a></p>'; 
	}
	
	mysqli_close($conexion);
}

return $output;
} /** end alta_departamento **/



function baja_departamento() {
$output="";
$conexion=mysqli_connect("localhost", "colegio", "colegio", "colegio");
	if (!$conexion){
		die("Conexión ha fallado:" . mysqli_connect_error());
	}
mysqli_select_db($conexion, "colegio");	

if (!$_POST){
	$output='<form id="formBajaDpto" action="" method="post" accept-charset="UTF-8" size="100%">
	<p>
	<fieldset form="formBajaDpto">
	<legend align="left"><SPAN style="text-align:top">Eliminar un departamento</SPAN></legend>
        <br><br>
	<p><SPAN style="text-align:top">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Seleccionar un Departamento:&nbsp;<p align="center"><select name="nombDpto" size="5" required>';
	
	$sql="SELECT nombre FROM departamentos";
	$result=mysqli_query($conexion, $sql);
	if (mysqli_num_rows($result) > 0){
		while($row=mysqli_fetch_assoc($result)){
			$output= $output . '<option>' . $row["nombre"] . '</option>';
		}
	}
	else{
		  $output= $output . '<option></option>';
	}
	$output= $output . '</p></select></fieldset>
	</p>
	<p><input type="submit" value="Eliminar" style="font-weight:bold; color:black">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" value="Limpiar" style="font-weight:bold; color:black">  
	</p>
	</form>';
} 
else{
	$nombre=$_POST["nombDpto"];
	mysqli_select_db($conexion, "colegio");
	$sql="SELECT ID_DPTO FROM departamentos WHERE NOMBRE='$nombre'";
	$result=mysqli_query($conexion, $sql);
	$id=mysqli_fetch_array($result);
	$sql="DELETE FROM departamentos WHERE NOMBRE='$nombre'";
	if(mysqli_query($conexion, $sql)){	
		$output= '<p><b>El departamento seleccionado se ha borrado satisfactoriamente</b>.</p>
		<p>Identificador del registro: <b>' .$id[0] . '</b></p> 
		<p>Nombre del registro: <b>' . $nombre . '</b></p><br><br>';
		$output=$output . '<p align="center">Si desea eliminar otro departamento&nbsp;<a href="http://localhost/drupal/oficina/departamentos/baja_departamento">pulse aqu&iacute;</a></p>';		
	}
	else{
		$output='<p><b>Error al eliminar el registro con el nombre:&nbsp;' . $nombre . '<b></p>';
		$output=$output . '<p>'. mysqli_error($conexion) . '</p>';
	}
}
mysqli_close($conexion);
return $output;
 }  /** end baja_departamento **/


function modificar_departamento() {
$output="";

$conexion=mysqli_connect("localhost", "colegio", "colegio", "colegio");
	if (!$conexion){
		die("Conexión ha fallado:" . mysqli_connect_error());
	}
mysqli_select_db($conexion, "colegio");	

if (!$_POST){
	$output='<form id="formModDpto" action="" method="post" accept-charset="UTF-8" size="100%">
	<p>
	<fieldset form="formModDpto">
	<legend align="left"><SPAN style="text-align:top">Cambiar un departamento</SPAN></legend>
        <br><br>
	<p><SPAN style="text-align:center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Seleccionar un Departamento:&nbsp;<p align="center"><select name="nombDpto" size="5" required>';
	
	$sql="SELECT nombre FROM departamentos";
	$result=mysqli_query($conexion, $sql);
	if (mysqli_num_rows($result) > 0){
		while($row=mysqli_fetch_assoc($result)){
			$output= $output . '<option>' . $row["nombre"] . '</option>';
			//$id=$row["id_dpto"];
		}//501
	}
	else{
		  $output= $output . '<option></option>';
	}
	$output= $output . '</p></select>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Indicar el nuevo nombre de departamento:&nbsp; <input type="text" style="color:blue" name="nuevo" required></p></fieldset>
	</p>
	<p><input type="submit" value="Grabar" style="font-weight:bold; color:black">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" value="Limpiar" style="font-weight:bold; color:black">  
	</p>
	</form>';
} 
else{
	$nombre=$_POST["nombDpto"];
	$nombnuevo=$_POST["nuevo"];
	mysqli_select_db($conexion, "colegio");
	$sql="SELECT ID_DPTO FROM departamentos WHERE NOMBRE='$nombre'";
	$result=mysqli_query($conexion, $sql);
	$id=mysqli_fetch_array($result);
	//$num=$id[0];
	if ($nombnuevo == ""){
		$output='<br><br><font color="red"><b>Atenci&oacute;n</b></font><br><br><p>No ha introducido ning&uacute;n dato para actualizar el registro seleccionado:&nbsp;<b>' . $nombre . '</b></p>&nbsp;';
		$output=$output . '<br><p align="center">Para volver a intentarlo&nbsp;<a href="http://localhost/drupal/oficina/departamentos/modificar_departamento">pulse aqu&iacute;</a></p>';
	} 
	else{
		$sql="UPDATE departamentos SET NOMBRE='$nombnuevo' WHERE ID_DPTO= '$id[0]'";
		if(mysqli_query($conexion, $sql)){
			$output= '<p><b>El departamento seleccionado se ha actualizado satisfactoriamente.</b></p> 
			<p>Nombre anterior del registro: <b>' . $_POST["nombDpto"] . '</b></p><p>Se ha actualizado por el nombre: <b>' . $_POST["nuevo"] . '</b></p>
			<p>Identificador de registro: <b>' . $id[0] . '</b></p><br>';
			$output=$output . '<p align="center">Si desea modificar otro departamento&nbsp;<a href="http://localhost/drupal/oficina/departamentos/modificar_departamento">pulse aqu&iacute;</a></p>'; 
		}
		else{
			$output='<p><b>Error al actualizar el registro con el nombre:&nbsp;' . $nombre . '<b></p>';
			$output=$output . '<p>'. mysqli_error($conexion) . '</p>';
		}
	}
} 
mysqli_close($conexion);
return $output;

}  /** end modificar_departamento  **/

function listar_docentes() {
 return ('listar docentes');
 }
function alta_docente() {
 return ('alta docente');
 }
function baja_docente() {
 return ('baja docente');
 }
function modificar_docente() {
 return ('modificar docente');
 }

function alta_estudiante() {
 return ('alta estudiante');
 }
function baja_estudiante() {
 return ('baja estudiante');
 }
function modificar_estudiante() {
 return ('modificar estudiante');
 }



/**********
		************************** Materias *************************
***********/

function listar_materias(){
$output="";
$tamano_pagina="5";

if(array_key_exists('pagina', $_GET)){
	$pagina=$_GET["pagina"];
}
else{
	$pagina=1;
}

$conexion=mysqli_connect("localhost", "colegio", "colegio", "colegio");//400
if (!$conexion){
	die("Conexión ha fallado:" . mysqli_connect_error());
}

mysqli_select_db($conexion, "colegio");

$sql="SELECT * FROM materias";
$result=mysqli_query($conexion, $sql);
$total_filas=mysqli_num_rows($result);
$total_paginas=ceil($total_filas / $tamano_pagina);

$sql="SELECT * FROM materias LIMIT " . (($pagina-1) * $tamano_pagina) . "," . $tamano_pagina;
$result=mysqli_query($conexion, $sql);
$output='<p align="center"><b><font size="4">Listado de las Materias que se imparten en el centro</font></b></p>';
$output=$output . '<table border="2"><tr><th><font size="2">Identificador</font></th><th><font size="3">Nombre Materia</font></th></tr>';
if($total_filas > 0){
	while ($row=mysqli_fetch_assoc($result)){
		$output=$output . '<tr><td><font color="blue" size="2">'. $row["ID_MATERIA"] . '</font></td><td><font color="blue" size="2">' . $row["NOMBRE"] . '</font></td></tr>';
	}
	$output=$output . '</table><br>';
}

mysqli_close($conexion);

if ($total_paginas > 1){
	for ($i=1;$i<=$total_paginas;$i++){
		if($pagina == $i){
			$output=$output . 'P&aacute;gina ' . $pagina . "&nbsp;&nbsp;";
		}
		else{
			$output=$output . '<a href="http://localhost/drupal/oficina/materias/listar_materias?pagina=' . $i . '">P&aacute;gina ' . $i . '</a>&nbsp;&nbsp;';
		}

	}
}

return $output;

}   /** end listar_materias **/


function alta_materia() {
$output="";

$conexion=mysqli_connect("localhost", "colegio", "colegio", "colegio");
if (!$conexion){
	die("Conexión ha fallado:" . mysqli_connect_error());
}
mysqli_select_db($conexion, "colegio");	

if (!$_POST){
	$output='<form id="formAltaMateria" action="" method="post" accept-charset="UTF-8">
	<p>
	<fieldset form="formAltaMateria">
	<legend align="left"><SPAN style="text-align:top">Introducir una materia nueva</SPAN></legend>
        <br><br>
	<p><SPAN style="text-align:center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nombre:&nbsp;<input type="text" name="nombMateria" required autofocus></SPAN></p>
	<p><SPAN style="text-align:top">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Seleccionar un Departamento:</p><p align="center"><select name="nombDpto" size="6" required>';
	
	$sql="SELECT nombre FROM departamentos";
	$result=mysqli_query($conexion, $sql);
	if (mysqli_num_rows($result) > 0){
		while($row=mysqli_fetch_assoc($result)){
			$output= $output . '<option>' . $row["nombre"] . '</option>';
		}
	}
	else{
		  $output= $output . '<option></option>';
	}

	 $output= $output . '</select></p>
	</fieldset>
	</p>
	<p><input type="submit" value="Agregar" style="font-weight:bold; color:black">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" value="Limpiar" style="font-weight:bold; color:black">  
	</p>
	</form>';
}elseif ($_POST["nombMateria"] == ""){
		$output='<br><b>Atenci&oacute;n</b><br><br><p>No puede dar de alta una Materia sin nombre</p><p>Para volver hacia atr&aacute;s&nbsp;<a href="http://localhost/drupal/oficina/materias/alta_materia">pulse aqu&iacute;</a></p>'; 
}
else{
	$nombre=$_POST["nombMateria"];
	$nom_dpto=$_POST["nombDpto"];
	
	$sql="SELECT ID_DPTO FROM departamentos WHERE NOMBRE='$nom_dpto'";	
	$result=mysqli_query($conexion, $sql);
	$id_dpto=mysqli_fetch_array($result);
	$sql="INSERT INTO materias (ID_MATERIA, ID_DPTO, NOMBRE) VALUES (NULL, '$id_dpto[0]', '$nombre')";
		
	if(mysqli_query($conexion, $sql)){
		$ant_id=mysqli_insert_id($conexion);
		$output= '<p><b>Nueva materia registrada satisfactoriamente</b>.</p><p>Identificador de nuevo registro:&nbsp;<b>' . $ant_id . '</b></p> 
		<p>Nombre del nuevo registro:&nbsp;<b>' . $nombre . '</b></p>
		<p>Identificador de departamento&nbsp;<b>' . $id_dpto[0] . '</b></p>
		<p>Nombre del departamento:&nbsp;<b>' . $nom_dpto . '</b></p><br><br>
		<p align="center">Si desea agregar otra materia&nbsp;<a href="http://localhost/drupal/oficina/materias/alta_materia">pulse aqu&iacute;</a></p>'; 
	}
	
	
}
	
mysqli_close($conexion);	
return $output;

}   /** end alta_materia **/

function baja_materia() {
$output="";
$conexion=mysqli_connect("localhost", "colegio", "colegio", "colegio");
	if (!$conexion){
		die("Conexión ha fallado:" . mysqli_connect_error());
	}
mysqli_select_db($conexion, "colegio");	

if (!$_POST){
	$output='<form id="formBajaMateria" action="" method="post" accept-charset="UTF-8" size="100%">
	<p>
	<fieldset form="formBajaMateria">
	<legend align="left"><SPAN style="text-align:top">Eliminar una materia</SPAN></legend>
        <br><br>
	<p><SPAN style="text-align:top">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Seleccionar una Materia:&nbsp;<p align="center"><select name="nombMateria" size="8">';
	
	$sql="SELECT nombre FROM materias";
	$result=mysqli_query($conexion, $sql);
	if (mysqli_num_rows($result) > 0){
		while($row=mysqli_fetch_assoc($result)){
			$output= $output . '<option>' . $row["nombre"] . '</option>';
		}
	}
	else{
		  $output= $output . '<option></option>';
	}
	$output= $output . '</p></select></fieldset>
	</p>
	<p><input type="submit" value="Eliminar" style="font-weight:bold; color:black">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" value="Limpiar" style="font-weight:bold; color:black">  
	</p>
	</form>';
} 
else{
	$nombre=$_POST["nombMateria"];
	mysqli_select_db($conexion, "colegio");
	$sql="SELECT ID_MATERIA FROM departamentos WHERE NOMBRE='$nombre'";
	$result=mysqli_query($conexion, $sql);
	$id=mysqli_fetch_array($result);
	//$sql="DELETE FROM materias WHERE NOMBRE='$nombre'";
	if(mysqli_query($conexion, $sql)){
	//if($result){	
		$output= '<p><b>La materia seleccionada se ha borrado satisfactoriamente</b>.</p>
		<p>Identificador del registro: <b>' .$id[0] . '</b></p> 
		<p>Nombre del registro: <b>' . $nombre . '</b></p><br><br>';
		$output=$output . '<p align="center">Si desea eliminar otra materia&nbsp;<a href="http://localhost/drupal/oficina/materias/baja_materia">pulse aqu&iacute;</a></p>';		
	}
	else{
		$output='<p><b>Error al eliminar el registro con el nombre:&nbsp;' . $nombre . '<b></p>';
		$output=$output . '<p>'. mysqli_error($conexion) . '</p>';
	}
}
mysqli_close($conexion);
return $output;

}   /** end baja_materia **/


function modificar_materia() {
$output="";

$conexion=mysqli_connect("localhost", "colegio", "colegio", "colegio");
	if (!$conexion){
		die("Conexión ha fallado:" . mysqli_connect_error());
	}
mysqli_select_db($conexion, "colegio");	

if (!$_POST){
	$output='<form id="formModMateria" action="" method="post" accept-charset="UTF-8" size="100%">
	<p>
	<fieldset form="formModMateria">
	<legend align="left"><SPAN style="text-align:top">Cambiar nombre de una materia</SPAN></legend>
        <br><br>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Seleccionar una Materia:&nbsp;<p align="center"><select name="nombMateria" size="5" required>';
	
	$sql="SELECT nombre FROM materias";
	$result=mysqli_query($conexion, $sql);
	if (mysqli_num_rows($result) > 0){
		while($row=mysqli_fetch_assoc($result)){
			$output= $output . '<option>' . $row["nombre"] . '</option>';
			//$id=$row["id_dpto"];
		}
	}
	else{
		  $output= $output . '<option></option>';
	}
	$output= $output . '</p></select></p>
	<br><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Indicar el nuevo nombre de materia:&nbsp; <input type="text" style="color:blue" name="nuevo" required></p>
	</fieldset>
	</p>
	<p><input type="submit" value="Grabar" style="font-weight:bold; color:black">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="reset" value="Limpiar" style="font-weight:bold; color:black">  
	</p>
	</form>';
} 
else{
	$nombre=$_POST["nombMateria"];
	$nombnuevo=$_POST["nuevo"];
	mysqli_select_db($conexion, "colegio");
	$sql="SELECT ID_MATERIA FROM materias WHERE NOMBRE='$nombre'";
	$result=mysqli_query($conexion, $sql);
	$id=mysqli_fetch_array($result);
	//$num=$id[0];
	if ($nombnuevo == ""){
		$output='<br><br><font color="red"><b>Atenci&oacute;n</b></font><br><br><p>No ha introducido ning&uacute;n dato para actualizar el registro seleccionado:&nbsp;<b>' . $nombre . '</b></p>&nbsp;';
		$output=$output . '<br><p align="center">Para volver a intentarlo&nbsp;<a href="http://localhost/drupal/oficina/materias/modificar_materia">pulse aqu&iacute;</a></p>';
	} 
	else{
		$sql="UPDATE materias SET NOMBRE='$nombnuevo' WHERE ID_MATERIA= '$id[0]'";
		if(mysqli_query($conexion, $sql)){
			$output= '<p><b>La materia seleccionada se ha actualizado satisfactoriamente.</b></p> 
			<p>Nombre anterior del registro: <b>' . $_POST["nombMateria"] . '</b></p><p>Se ha actualizado por el nombre: <b>' . $_POST["nuevo"] . '</b></p>
			<p>Identificador de registro: <b>' . $id[0] . '</b></p><br>';
			$output=$output . '<p align="center">Si desea modificar otra materia&nbsp;<a href="http://localhost/drupal/oficina/materias/modificar_materia">pulse aqu&iacute;</a></p>'; 
		}
		else{
			$output='<p><b>Error al actualizar el registro con el nombre:&nbsp;' . $nombre . '<b></p>';
			$output=$output . '<p>'. mysqli_error($conexion) . '</p>';
		}
	}
} 
mysqli_close($conexion);
return $output;

}  /** end modificar_materia **/


function expedientes_academicos() {
 return ('expedientes acad&eacute;micos ññññ');
 }

function oficina_matriculas() {

$acento=utf8_encode('Matrículas ñ');
 return $acento;
}