<?php

/**
 * Implementation hook_menu().
 */

function oficina_menu(){

$items=array();

$items['oficina/matriculas']=array(
	'title' => 'Matriculas',
	'access arguments' => array('Matriculas'),
	'page callback' => 'oficina_matriculas',
	'access callback'=> TRUE,
	'type' => MENU_NORMAL_ITEM,
	);
$items['oficina/estudiantes']=array(
	'title' => 'Estudiantes',
	'access arguments'=> array('Estudiantes'),
	'type'=> MENU_NORMAL_ITEM,
	//'weight'=> 0,
	);
$items['oficina/docentes']=array(
	'title' => 'Docentes',
	'access arguments'=> array('Docentes'),
	'page callback' => 'oficina_docentes',
	'type'=> MENU_NORMAL_ITEM,
	//'weight'=> 1,
	);	
$items['oficina/materias']=array(
	'title' => 'Materias',
	'access arguments'=> array('Alta materias'),
	'page callback' => 'alta_materias',
	'access callback'=> TRUE,
	'type'=> MENU_NORMAL_ITEM,
	//'weight'=> 2,
	);	
$items['oficina/materias/alta_materia']=array(
	'title' => 'Alta Materia',
	'access arguments'=> array('Alta Materia'),

	'type'=> MENU_DEFAULT_LOCAL_TASK,
	);
$items['oficina/materias/baja_materia']=array(
	'title' => 'Baja Materia',
	'access arguments'=> array('Baja Materia'),
	'page callback' => 'baja_materias',
	'type'=> MENU_LOCAL_TASK,
	);
$items['oficina/materias/modificar_materia']=array(
	'title' => 'Modificar Materia',
	'access arguments'=> array('Modificar Materia'),
	'page callback' => 'modificar_materias',
	'type'=> MENU_LOCAL_TASK,
	);
$items['oficina/departamentos']=array(
	'title' => 'Departamentos',
	'access arguments'=> array('Alta Departamentos'),
	'page callback' => 'alta_departamentos',
	'type'=> MENU_NORMAL_ITEM,
	//'weight'=> 3,
	);
$items['oficina/departamentos/alta_departamentos']=array(
	'title' => 'Alta Departamentos',
	'access arguments'=> array('Alta Departamentos'),
	'type'=> MENU_DEFAULT_LOCAL_TASK,
	);
$items['oficina/departamentos/baja_departamentos']=array(
	'title' => 'Baja Departamentos',
	'access arguments'=> array('Baja Departamentos'),
	'page callback' => 'baja_departamentos',
	'type'=> MENU_LOCAL_TASK,
	);
$items['oficina/departamentos/modificar_departamentos']=array(
	'title' => 'Modificar Departamentos',
	'access arguments'=> array('Modificar Departamentos'),
	'page callback' => 'modificar_departamentos',
	'type'=> MENU_LOCAL_TASK,
	);
return $items;	
}

/**
función borrar caché
**/
function bdexterna_clear_cache() {
  $core = array('cache', 'cache_path', 'cache_filter', 'cache_bootstrap', 'cache_page');
  $cache_tables = array_merge(module_invoke_all('flush_caches'), $core);
  foreach ($cache_tables as $table) {
   cache_clear_all('*', $table, TRUE);
  }
}





function oficina_matriculas(){

return "matriculas";
}
function oficina_estudiantes(){

return "hola";
}

function oficina_docentes(){

return "hola";
}

function oficina_materias(){

return "hola";
}

function alta_materias(){
$output="";
/*$db=array(
	'database'=>'colegio',
	'username'=>'colegio',
	'password'=>'colegio',
	'host'=>'localhost',
	'driver'=>'mysql',
	);
*/
if (!$_POST){
$output='<form id="formAltaMateria" action="?" method="post" accept-charset="UTF-8">
	<p>
	<fieldset form="formAltaMateria">
	<legend align="left"><SPAN style="text-align:top">Introducir una materia nueva</SPAN></legend>
       <br><br>
	<p><SPAN style="text-align:center">   Nombre:   <input type="text" name="nombMateria" size="70"></SPAN></p>
	</fieldset>
	</p>
	<p><input type="submit" value="Grabar" style="font-weight:bold; color:black">  <input type="reset" value="Borrar" style="font-weight:bold; color:black">  
	</p>
	</form>';
 } 
	else{

db_set_active('extbd');		
		$nombre=$_POST["nombMateria"];
		$sql="INSERT INTO MATERIAS (ID_MATERIA, NOMBRE) VALUES (NULL, $nombre)";
		$results=db_query($sql);
		$output= "Se ha insertado satisfactoriamente una nueva materia con el nombre: " . $nombre . "<br><br>";
		$output= $output . '<p>Si desea agragar otra materia pulse a Volver: <input type="button" onClick=" location.href="http://localhost/drupal/oficina/materias/alta_materia" value="Volver"></p>';
		
		db_set_ative('default'); 
	}
return $output;
}

function baja_materias(){

return "hola";
}

function modificar_materias(){

return "hola";
}


function alta_departamentos(){
$output="";
/*$db=array(
	'database'=>'colegio',
	'username'=>'colegio',
	'password'=>'colegio',
	'host'=>'localhost',
	'driver'=>'mysql',
	);
*/



if (!$_POST){
$output='<form id="formAltaDpto" action="?" method="post" accept-charset="UTF-8">
	<p>
	<fieldset form="formAltaDpto">
	<legend align="left"><SPAN style="text-align:top">Introducir un departamento nuevo</SPAN></legend>
       <br><br>
	<p><SPAN style="text-align:center">   Nombre:   <input type="text" name="nombDpto" size="70"></SPAN></p>
	</fieldset>
	</p>
	<p><input type="submit" value="Grabar" style="font-weight:bold; color:black">  <input type="reset" value="Borrar" style="font-weight:bold; color:black">  
	</p>
	</form>';
 } 
	else{

db_set_active('extbd');		

		$nombre=$_POST["nombDpto"];
		$sql="INSERT INTO DEPARTAMENTOS (ID_DPTO, NOMBRE) VALUES (NULL, $nombre)";
		$results=db_query($sql);
		$output= "Se ha insertado satisfactoriamente un nuevo departamento con el nombre: " . $nombre . "<br><br>";
		$output= $output . '<p>Si desea agragar otro departamento pulse el botón  Volver: <input type="button" onClick=" location.href="http://localhost/drupal/oficina/materias/alta_materia" value="Volver"></p>';
		db_set_ative('default'); 
	}
return $output;

}

function baja_departamentos(){
GLOBAL $databases;


$guardar=$databases['dbext']['default']['username'];
$databases['extdb']['default']['username']='o';
$salida=$databases['dbext']['default']['username'];
$databases['extdb']['default']['username']=$guardar;
return $guardar;
}



function modificar_departamentos(){
$output="";
/***

bdexterna_clear_cache();
//db_set_active();

db_set_active('dbext');	

Database::openConnection('dbext','default');
Database::getConnection('default','dbext');
***/

	$servername="localhost";
	$username="colegio";
	$password="colegio";
	$dbname="colegio";

	$conn=mysqli_connect($servername, $username, $password, $dbname);
	if (!$conn){
		die("Conexión ha fallado:" . mysqli_connect_error());
	}
	$sql= "SELECT nombre FROM departamentos";
	$result=mysqli_query($conn, $sql);

	$output="<p>Visualizar departamentos:<select>";
	if (mysqli_num_rows($result) > 0){
		while($row=mysqli_fetch_assoc($result)){
			$output=$output .  "<option>" . $row["nombre"] . "</option>";
		}
	}else{
		echo "<option></option>";
	}
	mysqli_close($conn);
	/***$sql="SELECT NOMBRE FROM COLEGIO.DEPARTAMENTOS";
	//$results=db_query($sql);
	//foreach($results as $res){
	//	$output= $output . '<option>' . $res . '</option>';
	}
	
db_set_ative('default');
drupal_set_message(t('the queries have been made'));
***/

return $output;
}