<?php


/**
 * Implementation hook_menu().
 */

function oficina_menu(){

$items=array();

$items['oficina/matriculas']=array(
	'title' => 'Matriculas',
	'access arguments' => array('Matriculas'),
	'page callback' => 'oficina_matriculas',
	'access callback'=> TRUE,
	'type' => MENU_NORMAL_ITEM,
	);
$items['oficina/expedientes_academicos']=array(
	'title' => 'Expedientes Academicos',
	'access arguments' => array('Expedientes Academicos'),
	'page callback' => 'expedientes_academicos',
	'access callback'=> TRUE,
	'type' => MENU_NORMAL_ITEM,
	);
$items['oficina/estudiantes']=array(
	'title' => 'Estudiantes',
	'access arguments'=> array('Alta Estudiante'),
	'page callback' => 'alta_estudiante',
	'access callback'=> TRUE,
	'type'=> MENU_NORMAL_ITEM,
	//'weight'=> 0,
	);
$items['oficina/estudiantes/alta_estudiante']=array(
	'title' => 'Alta Estudiante',
	'access arguments'=> array('Alta Estudiante'),
	'type'=> MENU_DEFAULT_LOCAL_TASK,
	);
$items['oficina/estudiantes/baja_estudiante']=array(
	'title' => 'Baja Estudiante',
	'access arguments'=> array('Baja Estudiante'),
	'access callback'=> TRUE,
	'page callback' => 'baja_estudiante',
	'type'=> MENU_LOCAL_TASK,
	);
$items['oficina/estudiantes/modificar_estudiante']=array(
	'title' => 'Modificar Estudiante',
	'access arguments'=> array('Modificar Estudiante'),
	'access callback'=> TRUE,
	'page callback' => 'modificar_estudiante',
	'type'=> MENU_LOCAL_TASK,
	);
$items['oficina/docentes']=array(
	'title' => 'Docentes',
	'access arguments'=> array('Alta Docentes'),
	'page callback' => 'alta_docente',
	'access callback'=> TRUE,
	'type'=> MENU_NORMAL_ITEM,
	//'weight'=> 1,
	);
$items['oficina/docentes/alta_docente']=array(
	'title' => 'Alta Docente',
	'access arguments'=> array('Alta Docente'),
	'type'=> MENU_DEFAULT_LOCAL_TASK,
	);
$items['oficina/docentes/baja_docente']=array(
	'title' => 'Baja Docente',
	'access arguments'=> array('Baja Docente'),
	'access callback'=> TRUE,
	'page callback' => 'baja_docente',
	'type'=> MENU_LOCAL_TASK,
	);
$items['oficina/docentes/modificar_docente']=array(
	'title' => 'Modificar Docente',
	'access arguments'=> array('Modificar Docente'),
	'access callback'=> TRUE,
	'page callback' => 'modificar_docente',
	'type'=> MENU_LOCAL_TASK,
	);		
$items['oficina/materias']=array(
	'title' => 'Materias',
	'access arguments'=> array('Alta materia'),
	'page callback' => 'alta_materia',
	'access callback'=> TRUE,
	'type'=> MENU_NORMAL_ITEM,
	//'weight'=> 2,
	);	
$items['oficina/materias/alta_materia']=array(
	'title' => 'Alta Materia',
	'access arguments'=> array('Alta Materia'),
	'type'=> MENU_DEFAULT_LOCAL_TASK,
	);
$items['oficina/materias/baja_materia']=array(
	'title' => 'Baja Materia',
	'access arguments'=> array('Baja Materia'),
	'access callback'=> TRUE,
	'page callback' => 'baja_materia',
	'type'=> MENU_LOCAL_TASK,
	);
$items['oficina/materias/modificar_materia']=array(
	'title' => 'Modificar Materia',
	'access arguments'=> array('Modificar Materia'),
	'access callback'=> TRUE,
	'page callback' => 'modificar_materia',
	'type'=> MENU_LOCAL_TASK,
	);
$items['oficina/departamentos']=array(
	'title' => 'Departamentos',
	'access arguments'=> array('Alta Departamento'),
	'page callback' => 'alta_departamento',
	'access callback'=> TRUE,
	'type'=> MENU_NORMAL_ITEM,
	//'weight'=> 3,
	);
$items['oficina/departamentos/alta_departamento']=array(
	'title' => 'Alta Departamento',
	'access arguments'=> array('Alta Departamento'),
	'type'=> MENU_DEFAULT_LOCAL_TASK,
	);
$items['oficina/departamentos/baja_departamentos']=array(
	'title' => 'Baja Departamento',
	'access arguments'=> array('Baja Departamento'),
	'access callback'=> TRUE,
	'page callback' => 'baja_departamento',
	'type'=> MENU_LOCAL_TASK,
	);
$items['oficina/departamentos/modificar_departamento']=array(
	'title' => 'Modificar Departamento',
	'access arguments'=> array('Modificar Departamento'),
	'access callback'=> TRUE,
	'page callback' => 'modificar_departamento',
	'type'=> MENU_LOCAL_TASK,
	);
$items['oficina/cursos_oficiales']=array(
	'title' => 'Cursos Oficiales',
	'access arguments'=> array('Unidades'),
	'page callback' => 'unidades',
	'access callback'=> TRUE,
	'type'=> MENU_NORMAL_ITEM,
	//'weight'=> 0,
	);
$items['oficina/cursos_oficiales/unidades']=array(
	'title' => 'Unidades',
	'access arguments'=> array('Unidades'),
	'type'=> MENU_DEFAULT_LOCAL_TASK,
	);
 $items['oficina/cursos_oficales/unidades/alta_unidad'] = array(
 	'title' => 'Alta Unidad',
	'access arguments' => array('Alta Unidad'),
 	'page callback' => 'alta_unidad',
 	'page arguments' => array(2), // Pass 'fruity'.
	 'type' => MENU_LOCAL_TASK,
 	);
$items['oficina/cursos_oficales/unidades/baja_unidad'] = array(
 	'title' => 'Baja Unidad',
	'access arguments' => array('Baja Unidad'),
 	'page callback' => 'baja_unidad',
 	'page arguments' => array(2), // Pass 'fruity'.
	'type' => MENU_LOCAL_TASK,
 	);
$items['oficina/cursos_oficales/unidades/modificar_unidad'] = array(
 	'title' => 'Modificar Unidad',
	'access arguments' => array('Modificar Unidad'),
 	'page callback' => 'modificar_unidad',
 	'page arguments' => array(2), // Pass 'fruity'.
	'type' => MENU_LOCAL_TASK,
 	);
$items['oficina/cursos_oficiales/cursos']=array(
	'title' => 'Cursos',
	'access arguments'=> array('Cursos'),
	'page callback' => 'cursos',
	'type'=> MENU_LOCAL_TASK,
	);
 $items['oficina/cursos_oficales/cursos/alta_curso'] = array(
 	'title' => 'Alta Curso',
	'access arguments' => array('Alta Curso'),
 	'page callback' => 'alta_curso',
 	'page arguments' => array(2), // Pass 'fruity'.
	'type' => MENU_LOCAL_TASK,
 	);
$items['oficina/cursos_oficales/cursos/baja_curso'] = array(
 	'title' => 'Baja Curso',
	'access arguments' => array('Baja Curso'),
 	'page callback' => 'baja_curso',
 	'page arguments' => array(2), // Pass 'fruity'.
	'type' => MENU_LOCAL_TASK,
 	);
$items['oficina/cursos_oficales/cursos/modificar_curso'] = array(
 	'title' => 'Modificar Curso',
	'access arguments' => array('Modificar Curso'),
 	'page callback' => 'modificar_curso',
 	'page arguments' => array(2), // Pass 'fruity'.
	'type' => MENU_LOCAL_TASK,
 	);
$items['oficina/cursos_oficiales/niveles']=array(
	'title' => 'Niveles',
	'access arguments'=> array('Niveles'),
	'page callback' => 'niveles',
	'type'=> MENU_LOCAL_TASK,
	);
 $items['oficina/cursos_oficales/niveles/alta_nivel'] = array(
 	'title' => 'Alta Nivel',
	'access arguments' => array('Alta Nivel'),
 	'page callback' => 'alta_nivel',
 	'page arguments' => array(2), 
	'type' => MENU_LOCAL_TASK,
 	);
$items['oficina/cursos_oficales/niveles/baja_nivel'] = array(
 	'title' => 'Baja Nivel',
	'access arguments' => array('Baja Nivel'),
 	'page callback' => 'baja_nivel',
 	'page arguments' => array(2), 
	'type' => MENU_LOCAL_TASK,
 	);
$items['oficina/cursos_oficales/niveles/modificar_nivel'] = array(
 	'title' => 'Modificar Nivel',
	'access arguments' => array('Modificar Nivel'),
 	'page callback' => 'modificar_nivel',
 	'page arguments' => array(2), 
	'type' => MENU_LOCAL_TASK,
 	);

return $items;	
}

/**** funciones tareas ****/

function oficina_matriculas(){

return "hola";
}

function expedientes_academicos(){

return "hola";
}
function alta_estudiante(){

return "hola";
}

function baja_estudiante(){

return "hola";
}
function modificar_estudiante(){

return "hola";
}

function alta_docente(){

return "hola";
}

function baja_docente(){

return "hola";
}
function modificar_docente(){

return "hola";
}


function alta_materia(){
$output="";

if (!$_POST){
$output='<form id="formAltaMateria" action="http://localhost/drupal/oficina/materias" method="post" accept-charset="UTF-8">
	<p>
	<fieldset form="formAltaMateria">
	<legend align="left"><SPAN style="text-align:top">Introducir una materia nueva</SPAN></legend>
       <br><br>
	<p><SPAN style="text-align:center">   Nombre:   <input type="text" name="nombMateria" size="70"></SPAN></p>
	</fieldset>
	</p>
	<p><input type="submit" value="Grabar" style="font-weight:bold; color:black">  <input type="reset" value="Borrar" style="font-weight:bold; color:black">  
	</p>
	</form>';
 } 
	else{
		$nombre=$_POST["nombMateria"];
		//$sql="INSERT INTO MATERIAS (ID_MATERIA, NOMBRE) VALUES (NULL, $nombre)";
		//$results=db_query($sql);

		$output= "Se ha insertado satisfactoriamente una nueva materia con el nombre: " . $nombre . "<br><br>";
		$output= $output . '<p>Si desea agragar otra materia <a href="http://localhost/drupal/oficina/materias"> pulse aqu&iacute;</a></p>';	
	}
return $output;
}

function baja_materia(){

return "hola";
}

function modificar_materia(){

return "hola";
}


function alta_departamento(){
$output="hola";

return ("hola");
}

function baja_departamento(){


return ("hola");

}

function modificar_departamento(){


return ("hola");
}

function unidades(){
$output="hola";



return ("hola");
}

function alta_unidad(){


return ("hola");

}

function baja_unidad(){


return ("hola");

}
function modificar_unidad(){


return ("hola");
}

function cursos(){
$output="hola";



return ("hola");
}

function alta_curso(){


return ("hola");

}

function baja_curso(){


return ("hola");

}
function modificar_curso(){


return ("hola");
}

function niveles(){
$output="hola";



return ("hola");
}

function alta_nivel(){


return ("hola");

}

function baja_nivel(){


return ("hola");

}
function modificar_nivel(){


return ("hola");
}

