<?php


/**
 * Implementation hook_menu().
 */

function oficina_menu(){

$items=array();

$items['oficina/matriculas']=array(
	'title' => 'Matriculas',
	'access arguments' => array('Matriculas'),
	'page callback' => 'oficina_matriculas',
	'access callback'=> TRUE,
	'type' => MENU_NORMAL_ITEM,
	);
$items['oficina/estudiantes']=array(
	'title' => 'Estudiantes',
	'access arguments'=> array('Alta Estudiante'),
	'page callback' => 'alta_estudiante',
	'access callback'=> TRUE,
	'type'=> MENU_NORMAL_ITEM,
	//'weight'=> 0,
	);
$items['oficina/estudiantes/alta_estudiante']=array(
	'title' => 'Alta Estudiante',
	'access arguments'=> array('Alta Estudiante'),
	'type'=> MENU_DEFAULT_LOCAL_TASK,
	);
$items['oficina/estudiantes/baja_estudiante']=array(
	'title' => 'Baja Estudiante',
	'access arguments'=> array('Baja Estudiante'),
	'access callback'=> TRUE,
	'page callback' => 'baja_estudiante',
	'type'=> MENU_LOCAL_TASK,
	);
$items['oficina/estudiantes/modificar_estudiante']=array(
	'title' => 'Modificar Estudiante',
	'access arguments'=> array('Modificar Estudiante'),
	'access callback'=> TRUE,
	'page callback' => 'modificar_estudiante',
	'type'=> MENU_LOCAL_TASK,
	);
$items['oficina/docentes']=array(
	'title' => 'Docentes',
	'access arguments'=> array('Alta Docentes'),
	'page callback' => 'alta_docente',
	'access callback'=> TRUE,
	'type'=> MENU_NORMAL_ITEM,
	//'weight'=> 1,
	);
$items['oficina/docentes/alta_docente']=array(
	'title' => 'Alta Docente',
	'access arguments'=> array('Alta Docente'),
	'type'=> MENU_DEFAULT_LOCAL_TASK,
	);
$items['oficina/docentes/baja_docente']=array(
	'title' => 'Baja Docente',
	'access arguments'=> array('Baja Docente'),
	'access callback'=> TRUE,
	'page callback' => 'baja_docente',
	'type'=> MENU_LOCAL_TASK,
	);
$items['oficina/docentes/modificar_docente']=array(
	'title' => 'Modificar Docente',
	'access arguments'=> array('Modificar Docente'),
	'access callback'=> TRUE,
	'page callback' => 'modificar_docente',
	'type'=> MENU_LOCAL_TASK,
	);	
$items['oficina/materias']=array(
	'title' => 'Materias',
	'access arguments'=> array('Alta materia'),
	'page callback' => 'alta_materia',
	'access callback'=> TRUE,
	'type'=> MENU_NORMAL_ITEM,
	//'weight'=> 2,
	);	
$items['oficina/materias/alta_materia']=array(
	'title' => 'Alta Materia',
	'access arguments'=> array('Alta Materia'),
	'type'=> MENU_DEFAULT_LOCAL_TASK,
	);
$items['oficina/materias/baja_materia']=array(
	'title' => 'Baja Materia',
	'access arguments'=> array('Baja Materia'),
	'access callback'=> TRUE,
	'page callback' => 'baja_materia',
	'type'=> MENU_LOCAL_TASK,
	);
$items['oficina/materias/modificar_materia']=array(
	'title' => 'Modificar Materia',
	'access arguments'=> array('Modificar Materia'),
	'access callback'=> TRUE,
	'page callback' => 'modificar_materia',
	'type'=> MENU_LOCAL_TASK,
	);
$items['oficina/departamentos']=array(
	'title' => 'Departamentos',
	'access arguments'=> array('Alta Departamentos'),
	'page callback' => 'alta_departamentos',
	'access callback'=> TRUE,
	'type'=> MENU_NORMAL_ITEM,
	//'weight'=> 3,
	);
$items['oficina/departamentos/alta_departamentos']=array(
	'title' => 'Alta Departamentos',
	'access arguments'=> array('Alta Departamentos'),
	'type'=> MENU_DEFAULT_LOCAL_TASK,
	);
$items['oficina/departamentos/baja_departamentos']=array(
	'title' => 'Baja Departamentos',
	'access arguments'=> array('Baja Departamentos'),
	'access callback'=> TRUE,
	'page callback' => 'baja_departamentos',
	'type'=> MENU_LOCAL_TASK,
	);
$items['oficina/departamentos/modificar_departamentos']=array(
	'title' => 'Modificar Departamentos',
	'access arguments'=> array('Modificar Departamentos'),
	'access callback'=> TRUE,
	'page callback' => 'modificar_departamentos',
	'type'=> MENU_LOCAL_TASK,
	);
$items['oficina/cursos_oficiales']=array(
	'title' => 'Cursos Oficiales',
	'access arguments'=> array('Unidades'),
	'page callback' => 'alta_estudiante',
	'access callback'=> TRUE,
	'type'=> MENU_NORMAL_ITEM,
	//'weight'=> 0,
	);
$items['oficina/cursos_oficiales/Unidades']=array(
	'title' => 'Unidades',
	'access arguments'=> array('Alta Departamentos'),
	'type'=> MENU_DEFAULT_LOCAL_TASK,
	);
$items['oficina/cursos_oficiales/cursos']=array(
	'title' => 'Cursos',
	'access arguments'=> array('Alta Departamentos'),
	'type'=> MENU_LOCAL_TASK,
	);
return $items;	
}



function oficina_matriculas(){

return "matriculas";
}
function alta_estudiante(){

return "hola";
}
function baja_estudiante(){

return "hola";
}

function modificar_estudiante(){

return "hola";
}

function oficina_docentes(){

return "hola";
}

function oficina_materias(){

return "hola";
} //100

function alta_materia(){
$output="";

if (!$_POST){
$output='<form id="formAltaMateria" action="http://localhost/drupal/oficina/materias" method="post" accept-charset="UTF-8">
	<p>
	<fieldset form="formAltaMateria">
	<legend align="left"><SPAN style="text-align:top">Introducir una materia nueva</SPAN></legend>
       <br><br>
	<p><SPAN style="text-align:center">   Nombre:   <input type="text" name="nombMateria" size="70"></SPAN></p>
	</fieldset>
	</p>
	<p><input type="submit" value="Grabar" style="font-weight:bold; color:black">  <input type="reset" value="Borrar" style="font-weight:bold; color:black">  
	</p>
	</form>';
 } 
	else{
		$nombre=$_POST["nombMateria"];
		//$sql="INSERT INTO MATERIAS (ID_MATERIA, NOMBRE) VALUES (NULL, $nombre)";
		//$results=db_query($sql);
		$url='http://localhost/drupal/node/27';
		$output= "Se ha insertado satisfactoriamente una nueva materia con el nombre: " . $nombre . "<br><br>";
		$output= $output . '<p>Si desea agragar otra materia <a href="http://localhost/drupal/oficina/materias"> pulse aqu&iacute;</a></p>';	
	}
return $output;
}

function baja_materia(){

return "hola";
}

function modificar_materia(){

return "hola";
}


function alta_departamentos(){
$output="";

$servername="localhost";
$username="colegio";
$password="colegio";
$dbname="colegio";

if (!$_POST){

$output='<form id="formAltaDpto" action="" method="post" accept-charset="UTF-8">
	<p>
	<fieldset form="formAltaDpto">
	<legend align="left"><SPAN style="text-align:top">Introducir un nuevo departamento</SPAN></legend>
       <br><br>
	<p><SPAN style="text-align:center">Nombre Departamento:  <input type="text" name="nombDpto" size="70"></SPAN></p>
	</fieldset>
	</p>
	<p><input type="submit" value="Grabar" style="font-weight:bold; color:black">  <input type="reset" value="Borrar" style="font-weight:bold; color:black">  
	</p>
	</form>';
 } 
else{
	$conn=mysqli_connect($servername, $username, $password, $dbname);
	if (!$conn){
		die("Conexión ha fallado:" . mysqli_connect_error());
	}
	//$acentos=mysql_query("SET NAMES 'utf8'");
	$nombre=$_POST["nombDpto"];
	$sql="INSERT INTO departamentos (ID_DPTO, NOMBRE) VALUES (NULL, '$nombre')";
	
	if (mysqli_query($conn, $sql)){
		$ant_id=mysqli_insert_id($conn);
		$output= '<p>Nuevo departamento registrado satisfactoriamente.</p><p>Identificador de registro: ' . $ant_id . '</p>'; 
	}
	else{
		$output= 'Error: ' . $sql . '<br>' . mysqli_error($conn);
	}
	
	mysqli_close($conn);//81

	$output= $output . '<p>El nombre del nuevo departamento es: ' . $nombre . '</p><br><br>';
	$output= $output . '<p>Si desea agregar otro departamento <a href="http://localhost/drupal/oficina/departamentos"> pulse aqu&iacute;</a></p>'; 
}

return ($output);

}

function baja_departamentos(){
$output="";

$servername="localhost";
$username="colegio";
$password="colegio";
$dbname="colegio";

if (!$_POST){

$output='<form id="formBajaDpto" action="" method="post" accept-charset="UTF-8">
	<p>
	<fieldset form="formAltaDpto">
	<legend align="left"><SPAN style="text-align:top">Seleccinar el departamento a eliminar</SPAN></legend>
        <br><br>
	<p><SPAN style="text-align:center">   Nombre Departamento:   <input type="text" name="nombDpto" size="70"></SPAN></p>
	</fieldset>
	</p>
	<p><input type="submit" value="Grabar" style="font-weight:bold; color:black">  <input type="reset" value="Borrar" style="font-weight:bold; color:black">  
	</p>
	</form>';
 } 
	else{
		$nombre=$_POST["nombDpto"];
		$sql="INSERT INTO departamentos (id_dpto, nombre) VALUES (NULL, '$nombre')";
		$results=db_query($sql);
		$output= "Se ha insertado satisfactoriamente un nuevo departamento con el nombre: " . $nombre . "<br><br>";
		$output= $output . '<p>Si desea agragar otro departamento pulse el botón  Volver: <input type="button" onClick="location.href="http://localhost/drupal/oficina/materias/baja_materia"" value="Volver"></p>'; 
	}
return $output;

}



function modificar_departamentos(){
$output="";

$servername="localhost";
$username="colegio";
$password="colegio";
$dbname="colegio";


$conn=mysqli_connect($servername, $username, $password, $dbname);
if (!$conn){
	die("Conexión ha fallado:" . mysqli_connect_error());
}

if (!$_POST){
	
	$output='<form id="formModDpto" action="" method="post" accept-charset="UTF-8">
	<p>
	<fieldset form="formModDpto">
	<legend align="left"><SPAN style="text-align:top">Seleccionar el departamento a modificar: </SPAN></legend>
        <br><br>
	<p><SPAN style="text-align:center">   Nombre Departamento: <br>';
	
	$sql= "SELECT nombre FROM departamentos";
	$result=mysqli_query($conn, $sql);

	$output= $output . '<select name="nombDpto" size="6">';
	if (mysqli_num_rows($result) > 0){
		while($row=mysqli_fetch_assoc($result)){
			$output=$output .  '<option>' . $row["nombre"] . '</option>';
		}
	}else{
		$output=$output . '<option></option>';
	}

	$output=$output . '</select></fieldset></p>
	<p><input type="submit" value="Grabar" style="font-weight:bold; color:black">  <input type="reset" value="Borrar" style="font-weight:bold; color:black">  
	</p>
	</form>';
 } 
else{
	$nombre=$_POST["nombDpto"];

$output= $output . '<br><br>' . '<p>Si desea volver a modificar otro departamento</p>'; 
mysqli_close($conn);


return ($output);
}