<?php


/**
 * Implementation hook_menu().
 */
 function oficina_menu() {
 $items=array();

 $items['oficina/cursos_oficiales'] = array(	//Cursos Académicos
 'title' => 'CURSOS OFICIALES',
 'page callback' => 'agregare',
 'page arguments' => array('Unidades'),
 'access callback' => TRUE,
 'type' => MENU_NORMAL_ITEM,
 'weight' => -1,
 );
 $items['oficina/cursos_oficiales/unidades'] = array(
 'title' => 'Unidades',
 'access arguments' => array('Unidades'),
 'type' => MENU_DEFAULT_LOCAL_TASK,
 'weight' => 0,
 );
 $items['oficina/cursos_oficiales/cursos'] = array(
 'title' => 'Cursos',
 'access arguments' => array('Cursos'),
 'page callback' => 'agregare',
 'type' => MENU_LOCAL_TASK,
 'weight' => 1,
 ); 
$items['oficina/cursos_oficiales/niveles'] = array(
 'title' => 'Niveles',
 'access arguments' => array('Niveles'),
 'page callback' => 'agregare',
 'type' => MENU_LOCAL_TASK,
 'weight' => 2,
 );

$items['oficina/cursos_oficiales/cursos/listar_cursos'] = array(
 'title' => 'Listar Cursos',
 'access arguments' => array('Cursos'),
 'page callback' => 'listare',
 'page arguments' => array(2),
 'type' => MENU_LOCAL_TASK,
 'weight'=> 0,
 ); 
$items['oficina/cursos_oficiales/cursos/alta_curso'] = array(
 'title' => 'Alta Curso',
 'access arguments' => array('Cursos'),
 'page callback' => 'listare',//50
 'page arguments' => array(2), 
 'type' => MENU_LOCAL_TASK,
 'weight'=> 2,	
 );
 $items['oficina/cursos_oficiales/cursos/baja_curso'] = array(
 'title' => 'Baja Curso',
 'access arguments' => array('Cursos'),
 'page callback' => 'baja_est',
 'page arguments' => array(2), 
 'type' => MENU_LOCAL_TASK,
 'weight'=> 3,
 );
$items['oficina/cursos_oficiales/cursos/modificar_curso'] = array(
 'title' => 'Modificar Curso',
 'access arguments' => array('Cursos'),
 'page callback' => 'listare',
 'page arguments' => array(2),
 'type' => MENU_LOCAL_TASK,
 'weight'=> 1,
 );


$items['oficina/cursos_oficiales/niveles/listar_niveles'] = array(
 'title' => 'Listar Niveles',
 'access arguments' => array('Niveles'),
 'page callback' => 'listare',
 'page arguments' => array(2),
 'type' => MENU_LOCAL_TASK,
 'weight'=> 0,
 ); 
$items['oficina/cursos_oficiales/niveles/alta_nivel'] = array(
 'title' => 'Alta Nivel',
 'access arguments' => array('Niveles'),
 'page callback' => 'al_departamento',
 'page arguments' => array(2), 
 'type' => MENU_LOCAL_TASK,
 'weight'=> 2,
 );
 $items['oficina/cursos_oficiales/niveles/baja_nivel'] = array(
 'title' => 'Baja Nivel',
 'access arguments' => array('Niveles'),
 'page callback' => 'ba_departamento',
 'page arguments' => array(2), 
 'type' => MENU_LOCAL_TASK,
 'weight'=> 3,
 );
$items['oficina/cursos_oficiales/niveles/modificar_nivel'] = array(
 'title' => 'Modificar Nivel',
 'access arguments' => array('Niveles'),
 'page callback' => 'mo_departamento',//100
 'page arguments' => array(2),
 'type' => MENU_LOCAL_TASK,
 'weight'=> 1,
 );

$items['oficina/cursos_oficiales/unidades/listar_unidades'] = array(
 'title' => 'Listar Unidades',
 'access arguments' => array('Unidades'),
 'page callback' => 'listare',
 'page arguments' => array(2),
 'type' => MENU_LOCAL_TASK,
 'weight'=> 0,
 ); 
$items['oficina/cursos_oficiales/unidades/alta_unidad'] = array(
 'title' => 'Alta Unidad',
 'access arguments' => array('Unidades'),
 'page callback' => 'al_departamento',
 'page arguments' => array(2), 
 'type' => MENU_LOCAL_TASK,
 'weight'=> 2,
 );
 $items['oficina/cursos_oficiales/unidades/baja_unidad'] = array(
 'title' => 'Baja Unidad',
 'access arguments' => array('Unidades'),
 'page callback' => 'ba_departamento',
 'page arguments' => array(2), 
 'type' => MENU_LOCAL_TASK,
 'weight'=> 3,
 );
$items['oficina/cursos_oficiales/unidades/modificar_unidad'] = array(
 'title' => 'Modificar Unidad',
 'access arguments' => array('Unidades'),
 'page callback' => 'mo_departamento',
 'page arguments' => array(2), 
 'type' => MENU_LOCAL_TASK,
 'weight'=> 1,
 );

$items['oficina/departamentos']=array(		//Departamentos
	'title' => 'DEPARTAMENTOS',
	'access arguments'=> array('Listar Departamentos'),
	'page callback' => 'listar_departamentos',
	'access callback'=> TRUE,
	'type'=> MENU_NORMAL_ITEM,
	'weight'=> -1,
	);

$items['oficina/departamentos/listar_departamentos']=array(
	'title' => 'Listar Departamentos',
	'access arguments'=> array('Listar Departamentos'),//150
	'type'=> MENU_DEFAULT_LOCAL_TASK,
	'weight'=> 0,
	);
$items['oficina/departamentos/alta_departamento'] = array(
 	'title' => 'Alta Departamento',
 	'access arguments' => array('Alta Departamento'),
 	'page callback' => 'alta_departamento',
 	'type' => MENU_LOCAL_TASK,
	'weight'=> 1,
 	); 
$items['oficina/departamentos/baja_departamentos']=array(
	'title' => 'Baja Departamento',
	'access arguments'=> array('Baja Departamento'),
	'access callback'=> TRUE,
	'page callback' => 'ba_departamento',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 2,
	);
$items['oficina/departamentos/modificar_departamento']=array(
	'title' => 'Modificar Departamento',
	'access arguments'=> array('Modificar Departamento'),
	'access callback'=> TRUE,
	'page callback' => 'mo_departamento',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 3,
	);

$items['oficina/docentes']=array(	//Docentes
	'title' => 'DOCENTES',
	'access arguments'=> array('Listar Docentes'),
	'page callback' => 'listar_docentes',
	'access callback'=> TRUE,
	'type'=> MENU_NORMAL_ITEM,
	'weight'=> -1,
	);
$items['oficina/docentes/listar_docentes']=array(
	'title' => 'Listar Docentes',
	'access arguments'=> array('Listar Docentes'),
	'type'=> MENU_DEFAULT_LOCAL_TASK,
	'weight'=> 0,
	);
$items['oficina/docentes/alta_docente']=array(
	'title' => 'Alta Docente',
	'access arguments'=> array('Alta Docente'),
	'access callback'=> TRUE,
	'page callback' => 'alta_docente',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 1,
	);//200
$items['oficina/docentes/baja_docente']=array(
	'title' => 'Baja Docente',
	'access arguments'=> array('Baja Docente'),
	'access callback'=> TRUE,
	'page callback' => 'baja_docente',
	'type'=> MENU_LOCAL_TASK,
 	'weight'=> 2,
	);
$items['oficina/docentes/modificar_docente']=array(
	'title' => 'Modificar Docente',
	'access arguments'=> array('Modificar Docente'),
	'access callback'=> TRUE,
	'page callback' => 'modificar_docente',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 3,
	);	

$items['oficina/estudiantes']=array(		//Estudiantes
	'title' => 'ESTUDIANTES',
	'access arguments'=> array('Listar estudiantes'),
	'page callback' => 'alta_estudiante',
	'access callback'=> TRUE,
	'type'=> MENU_NORMAL_ITEM,
	'weight'=> -1,
	);
$items['oficina/estudiantes/listar_estudiantes']=array(
	'title' => 'Listar Estudiantes',
	'access arguments'=> array('Listar estudiantes'),
	'type'=> MENU_DEFAULT_LOCAL_TASK,
	'weight'=> 0,
	);
$items['oficina/estudiantes/alta_estudiante']=array(
	'title' => 'Alta Estudiante',
	'access arguments'=> array('Alta Estudiante'),
	'access callback'=> TRUE,
	'page callback' => 'alta_estudiante',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 1,
	);
$items['oficina/estudiantes/baja_estudiante']=array(
	'title' => 'Baja Estudiante',
	'access arguments'=> array('Baja Estudiante'),
	'access callback'=> TRUE,
	'page callback' => 'baja_estudiante',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 2,
	);
$items['oficina/estudiantes/modificar_estudiante']=array(
	'title' => 'Modificar Estudiante',
	'access arguments'=> array('Modificar Estudiante'),//250
	'access callback'=> TRUE,
	'page callback' => 'modificar_estudiante',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 3,
	);	

$items['oficina/historial_de_expedientes']=array(		//Expedientes 
	'title' => 'HISTORIAL DE EXPEDIENTES',
	'access arguments' => array('Historial de Expedientes'),
	'page callback' => 'expedientes_academicos',
	'access callback'=> TRUE,
	'type' => MENU_NORMAL_ITEM,
	'weight'=> -1,
	);

$items['oficina/materias']=array(		//Materias
	'title' => 'MATERIAS',
	'access arguments'=> array('Listar Materias'),
	'page callback' => 'alta_materia',
	'access callback'=> TRUE,
	'type'=> MENU_NORMAL_ITEM,
	'weight'=> -1,
	);	
$items['oficina/materias/listar_materias']=array(
	'title' => 'Listar Materias',
	'access arguments'=> array('Listar Materias'),
	'type'=> MENU_DEFAULT_LOCAL_TASK,
	'weight'=> 0,
	);
$items['oficina/materias/alta_materia']=array(
	'title' => 'Alta Materia',
	'access arguments'=> array('Alta Materia'),
	'access callback'=> TRUE,
	'page callback' => 'alta_materia',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 1,
	);
$items['oficina/materias/baja_materia']=array(
	'title' => 'Baja Materia',
	'access arguments'=> array('Baja Materia'),
	'access callback'=> TRUE,
	'page callback' => 'baja_materia',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 2,
	);
$items['oficina/materias/modificar_materia']=array(
	'title' => 'Modificar Materia',
	'access arguments'=> array('Modificar Materia'),
	'access callback'=> TRUE,
	'page callback' => 'modificar_materia',//300
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 3,
	);
$items['oficina/registro_de_cursos']=array(		//Registro (matrículas)
	'title' => 'REGISTRO DE CURSOS',
	'access arguments'=> array('Registro de Cursos'),
	'page callback' => 'alta_materia',
	'access callback'=> TRUE,
	'type'=> MENU_NORMAL_ITEM,
	'weight'=> -1,
	);	
$items['oficina/registro_de_cursos/alta_registro']=array(
	'title' => 'Alta Registro',
	'access arguments'=> array('Alta Registro'),
	'type'=> MENU_DEFAULT_LOCAL_TASK,
	'weight'=> 0,
	);
$items['oficina/registro_de_cursos/baja_registro']=array(
	'title' => 'Baja Registro',
	'access arguments'=> array('Baja Registro'),
	'access callback'=> TRUE,
	'page callback' => 'baja_materia',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 1,
	);
$items['oficina/registro_de_cursos/modificar_registro']=array(
	'title' => 'Modificar Registro',
	'access arguments'=> array('Modificar Registro'),
	'access callback'=> TRUE,
	'page callback' => 'modificar_materia',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 2,
	);
$items['oficina/registro_de_cursos/Listar_registros']=array(
	'title' => 'Listar Registros',
	'access arguments'=> array('Listar Registros'),
	'access callback'=> TRUE,
	'page callback' => 'modificar_materia',
	'type'=> MENU_LOCAL_TASK,
	'weight'=> 3,
	);
 return $items;
 }

/**
 * Page callback
 
function menufun_greeting($first_name = '', $last_name = ''){
 return t('Hello @first_name @last_name', array('@first_name' => $first_name, '@last_name' => $last_name));
}*/ 
//351

function overvie() {
 $output = t('The following flavors are available...');
 // ... more code here
 return $output;
 }
 
function agregare() {

if (!$_POST){
$output='<form id="formAlta" action="http://localhost/drupal/colegio/inicia/dptos" method="post" accept-charset="UTF-8">
	<p>
	<fieldset form="formAlta">
	<legend align="left"><SPAN style="text-align:top">Introducir el nuevo departamento</SPAN></legend>
       <br><br>
	<p><SPAN style="text-align:center">   Nombre:   <input type="text" name="nombDpto" size="70"></SPAN></p>
	</fieldset>
	</p>
	<p><input type="submit" value="Grabar" style="font-weight:bold; color:black">  <input type="reset" value="Borrar" style="font-weight:bold; color:black">  <input type="button" style="font-wight:bold" value="Salir">
	</p>
	</form>';
}
else{

$output = "Departamento nuevo: " . $_POST["nombDpto"];
}
 //return t('A handy form to add flavors might go here...');
return $output;
 }
 
 function listare($type) {
 return t('List @type flavors', array('@type' => $type));
 }
function baja_est() {
 return ('hola');
 }


function listar_departamentos() {
$output="";
$tamano_pagina="15";
if (!$_GET["pagina"]){ 
	$inicio=0;
	$pagina=1;
	/*$output='<form id=formPag action="http://localhost/drupal/oficina/departamentos/listar_departamentos" method="get" accept-charset="UTF-8">
	<p>Seleccionar el tamaño de p&aacute;gina a mostrar:&nbsp;
	<select name="tampag">
	<option selected>5</option><option>10</option><option>15</option><option>20</option></select>
	<input type="text" name="pagina" value="1"></p>
	&nbsp;&nbsp;&nbsp;<input type="submit" value="Listar" style="font-weight:bold; color:black">
	</form>';*/
$output='<form id=formPag action="http://localhost/drupal/oficina/departamentos/listar_departamentos" method="get" accept-charset="UTF-8">
	
	</form>';
//401
		
}
else{ 
	$pagina=$_GET["pagina"];
	//$tamno_pagina=$_GET["tampag"];
	$inicio=($pagina-1) * $tamano_pagina;//400
}

$conexion=mysqli_connect("localhost", "colegio", "colegio", "colegio");
if (!$conexion){
	die("Conexión ha fallado:" . mysqli_connect_error());
}

mysqli_select_db($conexion, "colegio");

/*$sql="SELECT COUNT(*) AS total FROM departamentos";
$result=mysqli_query($connexion, $sql);
$fila=mysqli_fetch_array($result,MYSQLI_ASSOC);
$num_total=$fila["total"];*/


$sql="SELECT * FROM departamentos";
$result=mysqli_query($conexion, $sql);
$total_filas=mysqli_num_rows($result);
$total_paginas=ceil($total_filas / $tamano_pagina);

$sql="SELECT * FROM departamentos LIMIT " . $inicio . "," . $tamano_pagina;
$result=mysqli_query($conexion, $sql);
$output=$output . '<p align="center"><b><font size="4">Listado de los Departamentos activos en el centro</font></b></p>';
$output=$output . '<table border="2"><tr><th><font size="2">Identificador</font></th><th><font size="3">Nombre Departamento</font></th></tr>';
if($total_filas > 0){
	while ($row=mysqli_fetch_assoc($result)){
		$output=$output . '<tr><td><font color="blue" size="2">'. $row["ID_DPTO"] . '</font></td><td><font color="blue" size="2">' . $row["NOMBRE"] . '</font></td></tr>';
	}
	$output=$output . '</table><br>';
}

mysqli_close($conexion);

if ($total_paginas > 1){
	for ($i=1;$i<=$total_paginas;$i++){
		if($pagina == $i){
			$output=$output . 'P&aacute;gina ' . $pagina . " ";
		}
		else{
			$output=$output . '<a href="http://localhost/drupal/oficina/departamentos/listar_departamentos?pagina=' . $i . '">P&aacute;gina ' . $i . '</a>';
		}
	}
}

return $output;
}//end listar_departamentos

function alta_departamento() {
$output="";
//$conexion;


if (!$_POST){
$output='<form id="formAltaDpto" action="" method="post" accept-charset="UTF-8">
	<p>
	<fieldset form="formAltaDpto">
	<legend align="left"><SPAN style="text-align:top">Introducir un nuevo departamento</SPAN></legend>
       <br><br>
	<p><SPAN style="text-align:center">&nbsp;&nbsp;Nombre Departamento:&nbsp;<input type="text" name="nombDpto" size="70"></SPAN></p>
	</fieldset>
	</p>
	<p><input type="submit" value="Grabar" style="font-weight:bold; color:black">  <input type="reset" value="Borrar" style="font-weight:bold; color:black">  
	</p>
	</form>';
 } 
else{
	$conexion=mysqli_connect("localhost", "colegio", "colegio", "colegio");
	if (!$conexion){
		die("Conexión ha fallado:" . mysqli_connect_error());
	}

	$nombre=$_POST["nombDpto"];
	mysqli_select_db($conexion, "colegio");
	$sql="INSERT INTO departamentos (ID_DPTO, NOMBRE) VALUES (NULL, '$nombre')";
	
	if(mysqli_query($conexion, $sql)){
		$ant_id=mysqli_insert_id($conexion);
		$output= '<p><b>Nuevo departamento registrado satisfactoriamente</b>.</p><p>Identificador de nuevo registro: <b>' . $ant_id . '</b></p>'; 
		$output= $output . '<p>Nombre del nuevo registro: <b>' . $nombre . '</b></p><br><br>';
		$output= $output . '<p>Si desea agregar otro departamento <a href="http://localhost/drupal/oficina/departamentos/alta_departamento"> pulse aqu&iacute;</a></p>'; 
	}
	
	mysqli_close($conexion);
}

return $output;
}//end alta_departamentos



function ba_departamento() {
 return ('baja departameno');
 }
function mo_departamento() {
 return ('modificar departamento');
 }

function listar_docentes() {
 return ('listar docentes');
 }
function alta_docente() {
 return ('alta docente');
 }
function baja_docente() {
 return ('baja docente');
 }
function modificar_docente() {
 return ('modificar docente');
 }

function alta_estudiante() {
 return ('alta estudiante');
 }
function baja_estudiante() {
 return ('baja estudiante');
 }
function modificar_estudiante() {
 return ('modificar estudiante');
 }

function alta_materia() {
$output="";

if (!$_POST){
$output='<form id="formAltaMateria" action="http://localhost/drupal/oficina/materias" method="post" accept-charset="UTF-8">
	<p>
	<fieldset form="formAltaMateria">
	<legend align="left"><SPAN style="text-align:top">Introducir una materia nueva</SPAN></legend>
       <br><br>
	<p><SPAN style="text-align:center">   Nombre:   <input type="text" name="nombMateria" size="70"></SPAN></p>
	</fieldset>
	</p>
	<p><input type="submit" value="Grabar" style="font-weight:bold; color:black">  <input type="reset" value="Borrar" style="font-weight:bold; color:black">  
	</p>
	</form>';
 } 
	else{
		$nombre=$_POST["nombMateria"];
		//$sql="INSERT INTO MATERIAS (ID_MATERIA, NOMBRE) VALUES (NULL, $nombre)";
		//$results=db_query($sql);

		$output= "Se ha insertado satisfactoriamente una nueva materia con el nombre: " . $nombre . "<br><br>";
		$output= $output . '<p>Si desea agragar otra materia <a href="http://localhost/drupal/oficina/materias"> pulse aqu&iacute;</a></p>';	
	}
return $output;
 }

function baja_materia() {
 return ('baja materia');
 }
function modificar_materia() {
 return ('modificar materia');
 }
function expedientes_academicos() {
 return ('expedientes acad&eacute;micos ññññ');
 }

function oficina_matriculas() {

$acento=utf8_encode('Matrículas ñ');
 return $acento;
}